### PR TITLE
Es/anomaly hpo save model bug fix

### PR DESCRIPTION
**Pull request by eunwoosh**
This PR solves bug that error raises when run HPO on anomaly tasks.
It's same with previous one but for OTX and Geti's develop branch.

### CODE REVIEW

**Comment by eunwoosh** [comment]
run ote-test

**Comment by eunwoosh** [comment]
run ote-test

**Comment by goodsong81** [comment]
Could you run some local HPO tests for Anomaly tasks?

**Comment by eunwoosh** [comment]
@ashwinvaidya17 This PR is same with [this PR]([https://github.com/openvinotoolkit/training_extensions/pull/1300](https://github.com/openvinotoolkit/training_extensions/pull/url), but for develop branch.
I also reflect your bug fix [PR](https://github.com/openvinotoolkit/training_extensions/pull/1346).
Could you check that there is some problem in the implementation?

**Comment by eunwoosh** [comment]
> Could you run some local HPO tests for Anomaly tasks?

Ok I'm checking now.

**Review by ashwinvaidya17 — COMMENTED** [review]
Looks good. But I think you need to update `_set_metadata` as well.
```python
def _set_metadata(self, output_model: ModelEntity):
        if hasattr(self.model, "image_threshold"):
            output_model.set_data("image_threshold", self.model.image_threshold.value.cpu().numpy().tobytes())
        if hasattr(self.model, "pixel_threshold"):
            output_model.set_data("pixel_threshold", self.model.pixel_threshold.value.cpu().numpy().tobytes())
        if hasattr(self.model, "normalization_metrics"):
            output_model.set_data("min", self.model.normalization_metrics.state_dict()["min"].cpu().numpy().tobytes())
            output_model.set_data("max", self.model.normalization_metrics.state_dict()["max"].cpu().numpy().tobytes())
        else:
            logger.warning(
                "The model was not trained before saving. This will lead to incorrect normalization of the heatmaps."
            )
```

**Comment by eunwoosh** [comment]
> Could you run some local HPO tests for Anomaly tasks?

I checked that any errors didn't arise when run anomaly task with HPO.

**Comment by goodsong81** [comment]
@ashwinvaidya17 Thank you for comment.
@eunwoosh But the changes are included in https://github.com/openvinotoolkit/training_extensions/pull/1337/files.
We don't need to replicate.

**Comment by eunwoosh** [comment]
> @ashwinvaidya17 Thank you for comment. @eunwoosh But the changes are included in https://github.com/openvinotoolkit/training_extensions/pull/1337/files. We don't need to replicate.

I see. then, I'll revert it.

**Comment by eunwoosh** [comment]
run ote-test

**Review by ashwinvaidya17 — APPROVED** [review]

**Pull request closed without merging**
