### PR TITLE
Fliter NaN score prediction in inference

### PR DESCRIPTION
**Pull request by eugene123tw**
Fliter NaN score prediction in inference

### CODE REVIEW

**Comment by eugene123tw** [comment]
run ote-test

**Comment by eugene123tw** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/362/

**Comment by eugene123tw** [comment]
run ote-test

**Comment by eugene123tw** [comment]
run ote-test

**Review by goodsong81 — COMMENTED** [review]
What do you think of adding an input exception handling in OTE SDK (ScoredLabel, maybe) side as well as preventing NaN in inference side as Andru's suggestion?

> add checking in the ScoredLabel implementation of OTE that the probability can only be within this range: [0, 1.0]

**Comment by eugene123tw** [comment]
run ote-test

**Comment by eugene123tw** [comment]
Wrong submodule commit. I've created a new PR

**Pull request closed without merging**
