### PR TITLE
[CVS-84981] openvino.model_zoo.model_api.models.model.WrapperError: There is no model with name "blur_segmentation" in list

### PR DESCRIPTION
**Pull request by JihwanEom**
### Summary
- Resolve CVS-84981 for classification, which expect three output when export.

### CODE REVIEW

**Review by goodsong81 — APPROVED** [review]
LGTM.

**Review by jaegukhyun — APPROVED** [review]
LGTM

**Comment by JihwanEom** [comment]
FYI, this PR will be merged after checking other tasks, too.

**Comment by JihwanEom** [comment]
This issue can be resolved by #1158, so I'll close this PR.

**Pull request closed without merging**
