### PR TITLE
CVS-76978 marking OTE SDK tests  as unit tests

### PR DESCRIPTION
**Pull request by aiarkinx**

### CODE REVIEW

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
There are a lot of warnings such as 

```
09:31:04  ote_sdk/tests/utils/test_shape_factory.py:147
09:31:04    /home/jenkins/b/workspace/ote/precommit/ote_sdk_tests_runner/src/ote_sdk/ote_sdk/tests/utils/test_shape_factory.py:147: PytestUnknownMarkWarning: Unknown pytest.mark.unit - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
09:31:04      @pytest.mark.unit
```

**Comment by aiarkinx** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Pull request merged**
