### PR TITLE
[FIX] Avoid duplicate stacking for used_labels in Seg, Det

### PR DESCRIPTION
**Pull request by sungmanc**
# Summary
* This PR includes that hot-fix for [CVS-103676](https://jira.devtools.intel.com/browse/CVS-103676).
* Avoid duplicate stacking of used_labels.
* Remove wrong dataset (voc_dataset2). It didn't include the imagefile

### CODE REVIEW

**Review by jaegukhyun — APPROVED** [review]
Is there any reason to remove data in tests/asset?

**Comment by sungmanc** [comment]
> Is there any reason to remove data in tests/asset?

voc_dataset2 is weird. It didn't include the imagefile this is the reason why I removed

**Review by sungchul1 — COMMENTED** [review]
LGTM.
Although it seems that action, anomaly, and cls don't remove unused labels, isn't there the same issue with those tasks? If not, this PR can be merged.

**Comment by sungmanc** [comment]
> LGTM. Although it seems that action, anomaly, and cls don't remove unused labels, isn't there the same issue with those tasks? If not, this PR can be merged.

For those tasks, we aren't using the concept of `used_labels`

**Review by sungchul1 — APPROVED** [review]

**Pull request merged**
