### PR TITLE
[NNCF][Classification] Pruning+Quantization optimization

### PR DESCRIPTION
**Pull request by alexsu52**

### CODE REVIEW

**Comment by sovrasov** [comment]
@alexsu52 please rebase your branch of d-o-r to the latest ote and open corresponding PR to d-o-r.

**Comment by sovrasov** [comment]
run ote-tests

**Comment by sovrasov** [comment]
run ote_sdk tests

**Comment by sovrasov** [comment]
run ote-test

**Comment by alexsu52** [comment]
BMM: 28312

**Comment by alexsu52** [comment]
run ote-tests

**Comment by alexsu52** [comment]
run ote_sdk tests

**Comment by alexsu52** [comment]
run ote-test

**Comment by alexsu52** [comment]
run ote_sdk tests

**Comment by alexsu52** [comment]
run ote-test

**Comment by Ilya-Krylov** [comment]
run ote-test

**Comment by Ilya-Krylov** [comment]
@sovrasov please review

**Review by sovrasov — APPROVED** [review]

**Pull request merged**
