### PR TITLE
[FIX] unpatch recursive patcher

### PR DESCRIPTION
**Pull request by cih9088**
### Change
- fixed a bug when unpatch patched functions (thanks to @nikita-savelyevv)
- added more test cases to avoid mis-behaviour

### Unit test
image

### CODE REVIEW

**Review by goodsong81 — DISMISSED** [review]

**Review by nikita-savelyevv — DISMISSED** [review]

**Comment by cih9088** [comment]
Sorry for the bothering. I have fixed pre-commit style error.

**Review by nikita-savelyevv — DISMISSED** [review]

**Review by goodsong81 — DISMISSED** [review]
Nice catch!

**Comment by cih9088** [comment]
image
Failed unit tests are not related to the PR.
I can tell that they are failed on develop branch as well.

**Comment by sungmanc** [comment]
> image Failed unit tests are not related to the PR. I can tell that they are failed on develop branch as well.

@cih9088 , Could you rebase and re launch the CI tests? all issues from develop branch were resolved.

**Review by JihwanEom — APPROVED** [review]

**Review by sungmanc — APPROVED** [review]

**Pull request merged**
