### PR TITLE
[MISC] Remove image classification

### PR DESCRIPTION
**Pull request by morkovka1337**
Remove not working image classification test case. Test case was updated in master branch and is no more needed in the misc one.

### CODE REVIEW

**Comment by morkovka1337** [comment]
run tests

**Comment by morkovka1337** [comment]
run tests

**Comment by morkovka1337** [comment]
run tests

**Comment by kprokofi** [comment]
I think we can remove all classification tests and even the whole template. We will not support it anymore. 
The same is related to OD

**Comment by morkovka1337** [comment]
run tests

**Comment by morkovka1337** [comment]
run tests

**Comment by Ilya-Krylov** [comment]
run tests

**Comment by morkovka1337** [comment]
run tests

**Pull request merged**
