### PR TITLE
[CLASSIFICATION] Move classification models weights to openvino storage

### PR DESCRIPTION
**Pull request by sovrasov**

### CODE REVIEW

**Comment by sovrasov** [comment]
run ote-test

**Comment by sovrasov** [comment]
run ote-test

**Comment by sovrasov** [comment]
BMM 28039: [tests/models/test_basic_flow.py::TestBasicFlow::test_train_model_rest[detection-GPU] failed

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Pull request merged**
