### PR TITLE
[OTE] Fix indexing in hierarchical classification inference

### PR DESCRIPTION
**Pull request by sovrasov**

### CODE REVIEW

**Comment by sovrasov** [comment]
run ote-test

**Comment by sovrasov** [comment]
run ote-test

**Comment by sovrasov** [comment]
Build:  https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/883/

**Review by goodsong81 — APPROVED** [review]
Nice catch!
I also did similar fix in `feature/otx` PR (not yet merged) but this looks better. :)

**Review by jaegukhyun — APPROVED** [review]

**Pull request merged**
