### PR TITLE
hotfix

### PR DESCRIPTION
**Pull request by Ilya-Krylov**

### CODE REVIEW

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
BMM 23540 🕐

**Review by druzhkov-paul — APPROVED** [review]
Awesome! 🔥

**Comment by Ilya-Krylov** [comment]
BMM 23575 🕐

**Comment by Ilya-Krylov** [comment]
BMM 23575 ✔️

**Pull request merged**
