### PR TITLE
Fix coordinates normalization for segmentation (release)

### PR DESCRIPTION
**Pull request by kprokofi**
duplicate: https://github.com/openvinotoolkit/training_extensions/pull/2146

### CODE REVIEW

**Review by eunwoosh — COMMENTED** [review]
Nice catch! I think it's hard to find.
I have a one question. Don't we have to deal with the case where value of width or height is 1?
There's little chance but it's possible case. How do you think about?

**Comment by goodsong81** [comment]
@kprokofi Could you please fix some unit test failures?

**Comment by kprokofi** [comment]
> Nice catch! I think it's hard to find. I have a one question. Don't we have to deal with the case where value of width or height is 1? There's little chance but it's possible case. How do you think about?

If an image equals to 1x1 pixel, then coordinates will be (0,0) only, 1 pixel - it is right. But I am not sure that 1 pixel image is a valid example

**Comment by eunwoosh** [comment]
> >
> If an image equals to 1x1 pixel, then coordinates will be (0,0) only, 1 pixel - it is right. But I am not sure that 1 pixel image is a valid example

Yes, Actually (0, 0) won't be a problem but zero division can be. How to add a code to handle that case?

**Comment by kprokofi** [comment]
> > > 
> > 
> > 
> > If an image equals to 1x1 pixel, then coordinates will be (0,0) only, 1 pixel - it is right. But I am not sure that 1 pixel image is a valid example
> 
> Yes, Actually (0, 0) won't be a problem but zero division can be. How to add a code to handle that case?

For instance segmentation we have this check if the length of contour more than 2. We also use it for semantic segmentation exportable code. I added same check for segmentation utils. If our contour less than 2 it will be skipped
It will prevent division by 0. 
Overall, masks won't be appeared on image with 1 pixel - we can consider to change this behavior everywhere, but I don't think it is necessary. 1 pixel image it is more a bug than a use case

image

**Review by goodsong81 — APPROVED** [review]

**Review by sungmanc — APPROVED** [review]

**Review by eunwoosh — APPROVED** [review]

**Pull request merged**
