### PR TITLE
[ANOMALY CLASSIFICATION] Fix exportable code normalization

### PR DESCRIPTION
**Pull request by ashwinvaidya17**
Fix exportable code

### CODE REVIEW

**Comment by ashwinvaidya17** [comment]
run ote_sdk tests

**Comment by ashwinvaidya17** [comment]
run ote_sdk tests

**Comment by samet-akcay** [comment]
run one_sdk tests

**Comment by samet-akcay** [comment]
run ote_sdk tests

**Review by samet-akcay — APPROVED** [review]

**Pull request merged**
