### PR TITLE
Enable instance segmentation data pipeline

### PR DESCRIPTION
**Pull request by sungchul1**
### Summary

This PR includes:
- [x] Update/Add transforms to enable masks and polygons for iseg
    - [x] Resize
    - [x] Pad
    - [x] RandomFlip
    - [x] CachedMosaic
    - [x] CachedMixUp
    - [x] RandomResize
    - [x] RandomCrop
    - [x] FilterAnnotations
- [x] Update recipes
    - [x] maskrcnn_efficientnetb2b
    - [x] maskrcnn_r50
    - [x] maskrcnn_swint
    - [x] rtmdet_inst_tiny
- [x] Update base dataset to avoid `None` results
- [x] Refactoring time consumer
- [x] Fix bugs
    - [x] `img_info.img_shape` -> `img_info.pad_shape` when wrapping them with `BitmapMasks`

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have ran e2e tests and there is no issues.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Comment by eugene123tw** [comment]
Hi @sungchul2, could you please verify if resizing and padding are functioning correctly? I'm getting inconsistent shapes. You can reproduce the issue using the provided code. And, you can access the test data: [Test Data](https://intel.sharepoint.com/:u:/s/IOTGVMCAVA/EYC58xLhff1GtdaBCRRHFZYBkBdyhkL7WUoIMF5teRioyg?email=sungchul.kim%40intel.com&e=i56Wbd)

Additionally, it'd be great if you could include some unit tests to validate this.

```py
from otx.engine.engine import Engine

recipe_path = "src/otx/recipe/instance_segmentation/rtmdet_inst_tiny_tv.yaml"
data_root = "BlueBerry23.v1i.coco-mmdetection"

task_type = "INSTANCE_SEGMENTATION"

engine = Engine.from_config(
    config_path=recipe_path,
    data_root=data_root,
    task=task_type,
)

pad_shapes = []
datamodule = engine._datamodule
datamodule.prepare_data()
for batch in datamodule.train_dataloader():
    for img_info in batch.imgs_info:
        pad_shapes.append(img_info.pad_shape)

assert len(set(pad_shapes)) == 1, "All images should have the same pad shape"
```

**Comment by sungchul1** [comment]
> Hi @sungchul2, could you please verify if resizing and padding are functioning correctly? I'm getting inconsistent shapes. You can reproduce the issue using the provided code. And, you can access the test data: [Test Data](https://intel.sharepoint.com/:u:/s/IOTGVMCAVA/EYC58xLhff1GtdaBCRRHFZYBkBdyhkL7WUoIMF5teRioyg?email=sungchul.kim%40intel.com&e=i56Wbd)
> 
> Additionally, it'd be great if you could include some unit tests to validate this.
> 
> ```python
> from otx.engine.engine import Engine
> 
> recipe_path = "src/otx/recipe/instance_segmentation/rtmdet_inst_tiny_tv.yaml"
> data_root = "BlueBerry23.v1i.coco-mmdetection"
> 
> task_type = "INSTANCE_SEGMENTATION"
> 
> engine = Engine.from_config(
>     config_path=recipe_path,
>     data_root=data_root,
>     task=task_type,
> )
> 
> pad_shapes = []
> datamodule = engine._datamodule
> datamodule.prepare_data()
> for batch in datamodule.train_dataloader():
>     for img_info in batch.imgs_info:
>         pad_shapes.append(img_info.pad_shape)
> 
> assert len(set(pad_shapes)) == 1, "All images should have the same pad shape"
> ```

Thanks for reporting, @eugene123tw 
I took a look at this and it seems that `img_shape` is updated by `CachedMixUp`.
Current `pad_shape` is calculated by `img_shape` and `padding`, but I think `pad_shape` looks too dependent on `img_shape`.
https://github.com/openvinotoolkit/training_extensions/blob/ff9d98350cd6dfd2c63ca2785180fdf3889e4de9/src/otx/core/data/entity/base.py#L194-L199
For example, if an image is padded from (10, 10) to (16, 12), `padding` will be (0, 0, 2, 6) but `img_shape` remains as (10, 10).
In this case, `pad_shape` can be obtained as (16, 12) by getter.
However, if `img_shape` is updated to (16, 12) by `CachedMixUp`, `padding` remains as (0, 0, 2, 6), so `pad_shape` will become (22, 14), not (16, 12).
This is the reason why some `pad_shape` are shown differently.


So I tried to remove it because AFAIK `pad_shape` is not used anywhere in otx and even mmcv is setting `pad_shape` and `img_shape` with the same value during `Pad`.
I thought we can replace `pad_shape` with `img_shape`.
https://github.com/open-mmlab/mmcv/blob/v2.1.0/mmcv/transforms/processing.py#L385-L388

But, I didn't because I'm not sure that there is any other task that can be affected.
Could you share your thoughts? What do you think about `pad_shape`?
@harimkang @jaegukhyun Thanks if giving your opinion as well about this topic.

**Review by harimkang — APPROVED** [review]

**Comment by eugene123tw** [comment]
> > Hi @sungchul2, could you please verify if resizing and padding are functioning correctly? I'm getting inconsistent shapes. You can reproduce the issue using the provided code. And, you can access the test data: [Test Data](https://intel.sharepoint.com/:u:/s/IOTGVMCAVA/EYC58xLhff1GtdaBCRRHFZYBkBdyhkL7WUoIMF5teRioyg?email=sungchul.kim%40intel.com&e=i56Wbd)
> > Additionally, it'd be great if you could include some unit tests to validate this.
> > ```python
> > from otx.engine.engine import Engine
> > 
> > recipe_path = "src/otx/recipe/instance_segmentation/rtmdet_inst_tiny_tv.yaml"
> > data_root = "BlueBerry23.v1i.coco-mmdetection"
> > 
> > task_type = "INSTANCE_SEGMENTATION"
> > 
> > engine = Engine.from_config(
> >     config_path=recipe_path,
> >     data_root=data_root,
> >     task=task_type,
> > )
> > 
> > pad_shapes = []
> > datamodule = engine._datamodule
> > datamodule.prepare_data()
> > for batch in datamodule.train_dataloader():
> >     for img_info in batch.imgs_info:
> >         pad_shapes.append(img_info.pad_shape)
> > 
> > assert len(set(pad_shapes)) == 1, "All images should have the same pad shape"
> > ```
> 
> Thanks for reporting, @eugene123tw I took a look at this and it seems that `img_shape` is updated by `CachedMixUp`. Current `pad_shape` is calculated by `img_shape` and `padding`, but I think `pad_shape` looks too dependent on `img_shape`.
> 
> https://github.com/openvinotoolkit/training_extensions/blob/ff9d98350cd6dfd2c63ca2785180fdf3889e4de9/src/otx/core/data/entity/base.py#L194-L199
> 
> 
> For example, if an image is padded from (10, 10) to (16, 12), `padding` will be (0, 0, 2, 6) but `img_shape` remains as (10, 10).
> In this case, `pad_shape` can be obtained as (16, 12) by getter.
> However, if `img_shape` is updated to (16, 12) by `CachedMixUp`, `padding` remains as (0, 0, 2, 6), so `pad_shape` will become (22, 14), not (16, 12).
> This is the reason why some `pad_shape` are shown differently.
> So I tried to remove it because AFAIK `pad_shape` is not used anywhere in otx and even mmcv is setting `pad_shape` and `img_shape` with the same value during `Pad`. I thought we can replace `pad_shape` with `img_shape`. https://github.com/open-mmlab/mmcv/blob/v2.1.0/mmcv/transforms/processing.py#L385-L388
> 
> But, I didn't because I'm not sure that there is any other task that can be affected. Could you share your thoughts? What do you think about `pad_shape`? @harimkang @jaegukhyun Thanks if giving your opinion as well about this topic.

Thank you, @sungchul2, for the analysis.

I'm asking for clarification as it's important to have the correct shape (pad_shape or img_shape) for decoding polygons into masks during inst-seg training (otherwise we can't concatenate bit masks due to different mask shapes). While this might not be an issue for detection since there's no shape-related decoding involved, I've seen inconsistencies in the current pipeline where img_shape varies while pad_shape remains constant or vise versa.

Below is a case I found during training:
```py
{'img_id': 51, 'img_shape': (640, 640), 'ignored_labels': [], 'ori_shape': (1040, 780), 'pad_shape': (640, 640), 'scale_factor': None}
{'img_id': 15, 'img_shape': (530, 640), 'ignored_labels': [], 'ori_shape': (1080, 1920), 'pad_shape': (640, 640), 'scale_factor': None}
{'img_id': 26, 'img_shape': (640, 640), 'ignored_labels': [], 'ori_shape': (1080, 1920), 'pad_shape': (640, 640), 'scale_factor': None}
{'img_id': 29, 'img_shape': (640, 640), 'ignored_labels': [], 'ori_shape': (1040, 780), 'pad_shape': (640, 640), 'scale_factor': None}
```

As far as I'm aware, both YOLO and RTMDET utilize mosaic, which consistently returns square input images. Thus, img_shape and pad_shape should ideally always be (640, 640). I'm okay with replace pad_shape with img_shape, but I just need the img_shape to be correct (in this case `squared` as we specified in recipe  `pad_to_square: true`)

**Comment by sungchul1** [comment]
@eugene123tw You're right. `CachedMosaic` usually returns square images after the cache has > 4 images.
If there are <= 4 images in the cache, it will return data entity as it is.
https://github.com/openvinotoolkit/training_extensions/blob/ff9d98350cd6dfd2c63ca2785180fdf3889e4de9/src/otx/core/data/transform_libs/torchvision.py#L1439-L1440
mmdet implementation : https://github.com/open-mmlab/mmdetection/blob/v3.2.0/mmdet/datasets/transforms/transforms.py#L3457-L3458

And this returned entity which has an unsquared image will be used the next transforms, such as resize and crop, etc.
Before padding, `img_shape` remains unsquared shape because we use `keep_ratio=True` for resize.

Here is the log about img_idx=62. (I don't know what 62nd image is in the dataset you shared :D) 
```
CachedMosaic - img_info : ImageInfo(img_idx=62, img_shape=(3264, 2448), ori_shape=(3264, 2448), padding=(0, 0, 0, 0), scale_factor=(1.0, 1.0), normalized=False, norm_mean=(0.0, 0.0, 0.0), norm_std=(1.0, 1.0, 1.0), image_color_channel=ImageColorChannel.RGB,
ignored_labels=[]) - pad_shape : (3264, 2448)  <---------------- CachedMosaic isn't executed

RandomResize - img_info : ImageInfo(img_idx=62, img_shape=(748, 561), ori_shape=(3264, 2448), padding=(0, 0, 0, 0), scale_factor=(0.22916666666666666, 0.22916666666666666), normalized=False, norm_mean=(0.0, 0.0, 0.0), norm_std=(1.0, 1.0, 1.0), 
image_color_channel=ImageColorChannel.RGB, ignored_labels=[]) - pad_shape : (748, 561)

RandomCrop - img_info : ImageInfo(img_idx=62, img_shape=(640, 561), ori_shape=(3264, 2448), padding=(0, 0, 0, 0), scale_factor=None, normalized=False, norm_mean=(0.0, 0.0, 0.0), norm_std=(1.0, 1.0, 1.0), image_color_channel=ImageColorChannel.RGB, 
ignored_labels=[]) - pad_shape : (640, 561)

YOLOXHSVRandomAug - img_info : ImageInfo(img_idx=62, img_shape=(640, 561), ori_shape=(3264, 2448), padding=(0, 0, 0, 0), scale_factor=None, normalized=False, norm_mean=(0.0, 0.0, 0.0), norm_std=(1.0, 1.0, 1.0), image_color_channel=ImageColorChannel.RGB, 
ignored_labels=[]) - pad_shape : (640, 561)

RandomFlip - img_info : ImageInfo(img_idx=62, img_shape=(640, 561), ori_shape=(3264, 2448), padding=(0, 0, 0, 0), scale_factor=None, normalized=False, norm_mean=(0.0, 0.0, 0.0), norm_std=(1.0, 1.0, 1.0), image_color_channel=ImageColorChannel.RGB, 
ignored_labels=[]) - pad_shape : (640, 561)

Pad - img_info : ImageInfo(img_idx=62, img_shape=(640, 561), ori_shape=(3264, 2448), padding=(0, 0, 79, 0), scale_factor=None, normalized=False, norm_mean=(0.0, 0.0, 0.0), norm_std=(1.0, 1.0, 1.0), image_color_channel=ImageColorChannel.RGB, 
ignored_labels=[]) - pad_shape : (640, 640)  <--------------- pad_shape is updated

CachedMixUp - img_info : ImageInfo(img_idx=62, img_shape=(640, 640), ori_shape=(3264, 2448), padding=(0, 0, 79, 0), scale_factor=None, normalized=False, norm_mean=(0.0, 0.0, 0.0), norm_std=(1.0, 1.0, 1.0), image_color_channel=ImageColorChannel.RGB, 
ignored_labels=[]) - pad_shape : (640, 719)  <--------------- pad_shape is also updated because img_shape is updated
```

**Comment by sungchul1** [comment]
@eugene123tw 
And the last log shows `img_shape=(640, 640)` and `pad_shape=(640, 719)`.
Using `padding=(0, 0, 79, 0)`, `pad_shape` is calculated to (640+0+0, 640+0+79)=(640, 719) because `img_shape` is updated in `CachedMixUp`.
However, in this case, real image shape is (640, 640) so any crop and resize are not executed in `CachedMixUp`.
So the value should be maintained in this case, but updating `img_info` is needed for other cases (when using images with different shapes).
https://github.com/openvinotoolkit/training_extensions/blob/ff9d98350cd6dfd2c63ca2785180fdf3889e4de9/src/otx/core/data/transform_libs/torchvision.py#L1802-L1805
As a result, I think removing `pad_shape` would be good due to the reasons I said above.

**Review by jaegukhyun — APPROVED** [review]

**Pull request merged**
