### PR TITLE
Vsaltykovx/add mmdetection input parameters validation 2

### PR DESCRIPTION
**Pull request by hlewando**
Added input parameters validations for functions and methods in external/mmdetection/detection_tasks directory

### CODE REVIEW

**Comment by hlewando** [comment]
Tests results:
Unit tests are failing in below execution:
http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=ote-test-1809&environment=iotg-dev-workstation-10

**Comment by hlewando** [comment]
Tests results:

http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=ote-test-1809&environment=iotg-dev-workstation-10

**Comment by sstrehlk** [comment]
In fact in http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=ote-test-1809&environment=iotg-dev-workstation-10 all parameters validation unit tests passed. There are two failed api_other tests, but it seems, that they are not related to implemented functionality and tests. I run separate build on develop branch with these two tests for cross check. 
https://ci-ote.iotg.sclab.intel.com/job/ote/job/ote-test/1812/

**Review by sstrehlk — APPROVED** [review]

**Comment by sstrehlk** [comment]
Fix added.
tests for previously failed tests: https://ci-ote.iotg.sclab.intel.com/job/ote/job/ote-test/1822/ 
repeated tests with previous scope: https://ci-ote.iotg.sclab.intel.com/job/ote/job/ote-test/1823/
"short" performance tests: https://ci-ote.iotg.sclab.intel.com/job/ote/job/ote-test/1826/
reference "short" performance tests on develop branch https://ci-ote.iotg.sclab.intel.com/job/ote/job/ote-test/1825/

**Comment by sstrehlk** [comment]
Previously failed tests passed:
http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=ote-test-1822&environment=iotg-dev-workstation-12

**Comment by hlewando** [comment]
@goodsong81 could you look into this PR ? Tests which where failed are fixed by @sstrehlk, tests passed, looks good.

**Review by goodsong81 — APPROVED** [review]
LGTM

**Pull request merged**
