### PR TITLE
Fix to allow Scheduler to be configured as a list and fix a bug in the AdaptiveTrainingCallback

### PR DESCRIPTION
**Pull request by harimkang**
### Summary

- Fix wrong update the frequency of the warmup-scheduler (This is the cause of a bug from `AdaptiveTrainingCallback`. -> Longer warmup times in small-dataset)

| Model            | Dataset         | Before (map_50) | After (map_50) | seed |
|------------------|-----------------|-----------------|----------------|------|
| ATSS_MobilenetV2 | Pothole_small_0 |             0.0 |           0.46 |    0 |

- Fixes an issue where `overrides` would throw an error if `configs.callbacks` came in as `None`.
- Modify the optimizer and scheduler to receive them as a list.
- `WarmupReduceLROnPlateau` -> `LinearWarmupScheduler + ReduceLROnPlateau`.
- `WarmupPolynomialLR` -> `LinearWarmupScheduler + PolynomialLR`.
- It also modifies it to match the configuration based on OTX1.6 (develop).
    - `max_epochs`, `warmup_iters`, `early-stopping patience`

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Comment by sovrasov** [comment]
@harimkang could you also add results on `tests/assets/car_tree_bug/` to increase confidence that the fix can handle various datasets?

**Comment by harimkang** [comment]
> @harimkang could you also add results on `tests/assets/car_tree_bug/` to increase confidence that the fix can handle various datasets?

For now, it seems to be working fine based on `atss_mobilenetv2`. I've also run a regression test and will share the results when I get them.
image

**Comment by eugene123tw** [comment]
@harimkang Could you also check the accuracy for instance seg algos on `car_tree_bug` dataset?

**Comment by harimkang** [comment]
> @harimkang Could you also check the accuracy for instance seg algos on `car_tree_bug` dataset?

@eugene123tw 
With car_tree_bug dataset

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/harimkan/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/harimkan/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">


  | test/map_50 | best-epochs
-- | -- | --
maskrcnn_efficientnetb2b | 1 | 19
maskrcnn_r50 | 1 | 14



</body>

</html>

I'll also attach the regression result when it's done.

**Comment by harimkang** [comment]
[Small-Dataset Comparison]
WW06.3: e3cc66f17b46d335f96ec842a7411e524a3d7b45 (3 times)
This PR: 53f5dcb2bbbc5611c8620ebc757d2b12e8d5f71a (1 time)
classification (multi-class): multiclass-CUB-small
detection: pothole_small
*WW06.3 is the average of three measurements, so it may vary slightly.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/harimkan/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/harimkan/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">


Task | model | ww | test/score | train/iter_time | duration
-- | -- | -- | -- | -- | --
MULTI_CLASS_CLS | Efficientnet_b0 | ww06.3 | 0.9529 |   | 8
  |   | This   PR | 0.9492 |   | 6.8
  | Efficientnet_v2 | ww06.3 | 0.9962 |   | 13
  |   | This   PR | 0.9831 |   | 15.6333
  | MobileNet_v3_large_1.0 | ww06.3 | 0.9737 |   | 7
  |   | This   PR | 0.9887 |   | 6.8333
  | DeiT-Tiny | ww06.3 | 0.4915 |   | 8
  |   | This   PR | 1 |   | 7.7
  | DINO-v2 | ww06.3 | 0.9661 |   | 11
  |   | This   PR | 0.9661 |   | 13.4667
DETECTION | yolox_x | ww06.3 | 0.2834 | 0.1651 | 56
  |   | This   PR | 0.3015 | 0.1558 | 44
  | yolox_l | ww06.3 | 0.0069 | 0.1763 | 37
  |   | This   PR | 0.3613 | 0.174 | 45
  | yolox_s | ww06.3 | 0 | 0.1181 | 18
  |   | This   PR | 0.1594 | 0.1049 | 35
  | yolox_tiny | ww06.3 | 0.0022 | 0.0948 | 19
  |   | This   PR | 0.3862 | 0.0917 | 24
  | ssd_mobilenetv2 | ww06.3 | 0.006 | 0.1175 | 20
  |   | This   PR | 0.2115 | 0.1137 | 23
  | atss_resnext101 | ww06.3 | 0.494 | 0.2825 | 75
  |   | This   PR | 0.5272 | 0.2831 | 70
  | atss_mobilenetv2 | ww06.3 | 0 | 0.1548 | 18
  |   | This   PR | 0.534 | 0.171 | 31



</body>

</html>

**Review by eugene123tw — APPROVED** [review]

**Review by sungmanc — APPROVED** [review]
Thanks for the fix

**Review by chuneuny-emily — APPROVED** [review]

**Pull request merged**
