### PR TITLE
[OTE_SDK_TESTS] Increase code coverage segmentation_utils.py, basic_operations.py

### PR DESCRIPTION
**Pull request by saltykox**
Test list:
•	ote_sdk/ote_sdk/tests/utils/test_segmentation_utils.py
•	ote_sdk/ote_sdk/tests/usecases/evaluation/test_basic_operations.py

Task: CVS-74513

### CODE REVIEW

**Comment by saltykox** [comment]
run ote_sdk tests

**Comment by saltykox** [comment]
run ote_sdk tests

**Comment by saltykox** [comment]
run ote_sdk tests

**Comment by saltykox** [comment]
@LeonidBeynenson @Ilya-Krylov please review

**Comment by saltykox** [comment]
run ote_sdk tests

**Comment by saltykox** [comment]
run ote_sdk tests

**Comment by druzhkov-paul** [comment]
FYI https://docs.pytest.org/en/6.2.x/reference.html#pytest-approx

**Pull request merged**
