### PR TITLE
[OTX][HOT-FIX] Revert otx cli tools with data.yaml check

### PR DESCRIPTION
**Pull request by harimkang**
## Summary
Due to the effect of that https://github.com/openvinotoolkit/training_extensions/pull/1497, data.yaml of otx-workspace becomes unusable, so I revert this.

### CODE REVIEW

**Comment by cih9088** [comment]
The problem of original implementation was that `./data.yaml` used while testing sometimes does not get removed.
If `./data.yaml` is not removed, all the following tests would be failed. I didn't look into the root cause though.
Revert it for now and if a similar issue comes up, lets fix them then.

**Comment by harimkang** [comment]
> The problem of original implementation was that `./data.yaml` used while testing sometimes does not get removed. If `./data.yaml` is not removed, all the following tests would be failed. I didn't look into the root cause though. Revert it for now and if a similar issue comes up, lets fix them then.

Oh, there was such an issue. Let me take a look.

**Comment by sungmanc** [comment]
@harimkang @cih9088 , Did you execute the parallel tests ? (conduct >= 2 classification/detection/segmentation tests at the same time).

When I executed 2 task tests, I got the same error as @cih9088 's said.

**Comment by harimkang** [comment]
> @harimkang @cih9088 , Did you execute the parallel tests ? (conduct >= 2 classification/detection/segmentation tests at the same time).
> 
> When I executed 2 task tests, I got the same error as @cih9088 's said.

Hi @sungchul2, I think the issue is caused by the function used in the test below. Could you please confirm?
https://github.com/openvinotoolkit/training_extensions/blob/3e5ff263aeb58384c372fd65da0c2c8928edcfbd/tests/integration/cli/classification/test_classification.py#L615

**Comment by cih9088** [comment]
> When I executed 2 task tests, I got the same error as @cih9088 's said.

Yes, exactly. As I said, if you have `.data.yaml` in your CWD, because of whatever reasons, like pytest didn't remove it properly or one executed tests parallel, which means at some point you got `data.yaml` in your CWD, you would have an error.

**Comment by harimkang** [comment]
> > When I executed 2 task tests, I got the same error as @cih9088 's said.
> 
> Yes, exactly. As I said, if you have `.data.yaml` in your CWD, because of whatever reasons, like pytest didn't remove it properly or one executed tests parallel, which means at some point you got `data.yaml` in your CWD, you would have an error.

As sungman said, if we run multiple tests at the same time, it seems to be reproduced. I think maybe the cause I found is correct. I guess this needs to be addressed as I don't think test should affect root.

**Comment by sungmanc** [comment]
> > When I executed 2 task tests, I got the same error as @cih9088 's said.
> 
> Yes, exactly. As I said, if you have `.data.yaml` in your CWD, because of whatever reasons, like pytest didn't remove it properly or one executed tests parallel, which means at some point you got `data.yaml` in your CWD, you would have an error.

Let's assume this case,

test process 1: classification test
test process 2: detection test

Then, test process 1 made `data.yaml` during the `self-sl` test. In the mean time, test process 2 might get error because there was `data.yaml` file made by test process 1.

So, if we don't use parallel tests, then it will be fine

**Comment by sungmanc** [comment]
> > > When I executed 2 task tests, I got the same error as @cih9088 's said.
> > 
> > 
> > Yes, exactly. As I said, if you have `.data.yaml` in your CWD, because of whatever reasons, like pytest didn't remove it properly or one executed tests parallel, which means at some point you got `data.yaml` in your CWD, you would have an error.
> 
> As sungman said, if we run multiple tests at the same time, it seems to be reproduced. I think maybe the cause I found is correct. I guess this needs to be addressed as I don't think test should affect root.

Agreed. and this problem will be resolved after the merge of Datumaro PR. @sungchul2 , @cih9088 , @harimkang .
So, how about keep this as is? 

Because, when we use the Datumaro, we don't need to directly make `data.yaml`  for test case.

Making `.yaml` file will be removed
image

**Comment by sungchul1** [comment]
I agree. After Datumaro integration, I think we can remove the function.

**Review by sungmanc — APPROVED** [review]

**Review by eunwoosh — APPROVED** [review]

**Pull request merged**
