### PR TITLE
[CLASSIFICATION] Update d-o-r

### PR DESCRIPTION
**Pull request by sovrasov**
- FP16 training
- Models replacement
- Improved NNCF integration
- Classification codebase refactoring

BMM 25476 - failed

### CODE REVIEW

**Comment by sovrasov** [comment]
run ote_sdk tests

**Comment by nervana-ff** [comment]
Can one of the admins verify this patch?

**Comment by sovrasov** [comment]
ВMM 25565 - passed

**Comment by sovrasov** [comment]
BMM 25823 - passed

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by sovrasov** [comment]
run ote_sdk tests

**Comment by sovrasov** [comment]
run ote_sdk tests

**Pull request merged**
