### PR TITLE
[Anomaly Task] Set nncf version

### PR DESCRIPTION
**Pull request by ashwinvaidya17**
Sets nncf version to 2.2.0

## Tests
🏃‍♂️ https://ci-ote.iotg.sclab.intel.com/job/ote/job/ote-test/1842/

### CODE REVIEW

**Comment by ashwinvaidya17** [comment]
run ote_sdk tests

**Comment by ashwinvaidya17** [comment]
run ote-test

**Review by sstrehlk — DISMISSED** [review]

**Review by wonjuleee — DISMISSED** [review]
It looks good to me

**Comment by ashwinvaidya17** [comment]
I tried running component tests on this branch and it is failing. Only the build works. I'd like to hold merging it before I figure it out.

**Comment by ashwinvaidya17** [comment]
Here are the tests https://ci-ote.iotg.sclab.intel.com/job/ote/job/ote-test/1843/

**Comment by ashwinvaidya17** [comment]
Anomaly tests have passed. Deep object reid tests are failing but it is not relevant to the changes. https://ci-ote.iotg.sclab.intel.com/job/ote/job/ote-test/1851/console

**Review by goodsong81 — APPROVED** [review]

**Pull request merged**
