### PR TITLE
Add @attrs decorator for base configs

### PR DESCRIPTION
**Pull request by goodsong81**
Test report: http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=pr-ote-test-548&environment=iotg-dev-workstation-17
(Failures are not relevant to this change.)

### CODE REVIEW

**Comment by goodsong81** [comment]
run ote-test

**Comment by goodsong81** [comment]
run ote-test

**Comment by harimkang** [comment]
It was confirmed that the PR was passed in the local ote-cli test.

**Review by ashwinvaidya17 — APPROVED** [review]
lgtm!

**Review by harimkang — APPROVED** [review]

**Pull request merged**
