### PR TITLE
[Anomaly] Use Dict instead of DictConfig in openvino task

### PR DESCRIPTION
**Pull request by AlexanderDokuchaev**
From 2022.1 compression module expected as config only type Dict or structure that can be converted to Dict by `Dict.__init__` method.
`omegaconf.DictConfig` will no be supporting as config.

### CODE REVIEW

**Comment by nervana-ff** [comment]
Can one of the admins verify this patch?

**Comment by AlexanderDokuchaev** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
@AlexanderDokuchaev you need to provide successful build on BMM as well

**Comment by djdameln** [comment]
I repeated these changes in the Anomaly Segmentation PR https://github.com/openvinotoolkit/training_extensions/pull/913 to prevent merge conflicts. The changes there also take effect for the Anomaly Classification task. Once we merge https://github.com/openvinotoolkit/training_extensions/pull/913 we could close this one.

**Review by samet-akcay — APPROVED** [review]

**Pull request merged**
