### PR TITLE
return old reqs for open_model_zoo in mmdetection

### PR DESCRIPTION
**Pull request by akorobeinikov**
need to fix CVS-79292

### CODE REVIEW

**Comment by akorobeinikov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
https://github.com/openvinotoolkit/training_extensions/blob/ak/update_reqs/ote_sdk/ote_sdk/usecases/exportable_code/demo/requirements.txt#L2 ?

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by nervana-ff** [comment]
Can one of the admins verify this patch?

**Pull request merged**
