### PR TITLE
[DEV] Remove CLI datsaets not used anymore

### PR DESCRIPTION
**Pull request by sungmanc**
# Summary
* After Datumaro integration, CLI datasets haven't been used anymore.
* Delete OTX CLI datasets

The result of `tox -re pre-merge`: got all PASS in CLI tests  (FAILs only occurred in API tests)
image

### CODE REVIEW

**Review by jaegukhyun — COMMENTED** [review]
LGTM. Should we delete data.py in otx/algo/**/utils? It is for changing to otx dataset

**Comment by sungmanc** [comment]
> LGTM. Should we delete data.py in otx/algo/**/utils? It is for changing to otx dataset

For that part, let's think more. AFAIK, someone still needs. I'll cleansing `otx/algo/**/utils` on other PR in the near future. Thanks for inform :)

**Review by jaegukhyun — DISMISSED** [review]

**Review by goodsong81 — DISMISSED** [review]

**Review by supersoob — DISMISSED** [review]

**Comment by samet-akcay** [comment]
Thanks for the cleanup!

**Comment by sungmanc** [comment]
Sorry for the inconvenient, since the latest develop branch conflicts with this PR, I resolved and pushed again. 
Could you please re-approve ? @jaegukhyun @goodsong81 @supersoob

**Review by jaegukhyun — APPROVED** [review]

**Review by sovrasov — APPROVED** [review]

**Pull request merged**
