### PR TITLE
Added Multi-label dataset mlc_voc

### PR DESCRIPTION
**Pull request by pfinashx**
Added Multi-label dataset mlc_voc in Real-life tests, and Pre-commit (shortened dataset)
Please see pfinashx-1455-test and pfinashx-1458-test

### CODE REVIEW

**Comment by aiarkinx** [comment]
run ote-test

**Comment by LeonidBeynenson** [comment]
run ote-test

**Review by LeonidBeynenson — APPROVED** [review]
LGTM

**Comment by LeonidBeynenson** [comment]
run ote_sdk tests

**Comment by LeonidBeynenson** [comment]
2 @pfinashx : please, check the result of the OTE SDK tests -- especially the linter results.
Probably, the linter issues will have to be fixed.

**Comment by Ilya-Krylov** [comment]
@LeonidBeynenson probably not

**Comment by Ilya-Krylov** [comment]
run ote-test

**Pull request merged**
