### PR TITLE
[OTE][release] Fix handling ignored samples in hierarchical head

### PR DESCRIPTION
**Pull request by sovrasov**
Replaces https://github.com/openvinotoolkit/training_extensions/pull/1590

### CODE REVIEW

**Comment by sovrasov** [comment]
run ote-test

**Comment by sovrasov** [comment]
run ote-test

**Comment by sovrasov** [comment]
run ote-test

**Review by goodsong81 — APPROVED** [review]

**Comment by goodsong81** [comment]
Let's merge once the tests complete. (MPA -> commit update -> OTE merge)
http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=pr-ote-test-913&environment=iotg-dev-workstation-09

Could you apply this change to `develop` branch, too?

**Comment by sovrasov** [comment]
> Let's merge once the tests complete. (MPA -> commit update -> OTE merge) http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=pr-ote-test-913&environment=iotg-dev-workstation-09
> 
> Could you apply this change to `develop` branch, too?

Sure, I also will check filtering in other cases.

**Review by JihwanEom — APPROVED** [review]

**Comment by goodsong81** [comment]
Ah, I wanted to merge the MPA PR first to apply the merged commit, but let's just keep it as-is.
It's the last release w/ submodules anyway.

**Pull request merged**
