### PR TITLE
Update deep-object-reid for release v0.1.1

### PR DESCRIPTION
**Pull request by LeonidBeynenson**

### CODE REVIEW

**Comment by LeonidBeynenson** [comment]
Build lbeynens-632-test in progress 🏃‍♂️

**Comment by LeonidBeynenson** [comment]
Build 632 is cancelled
Build lbeynens-634-test is running 🏃‍♂️

**Comment by sovrasov** [comment]
BMM 23016

**Comment by LeonidBeynenson** [comment]
Build lbeynens-634-test is passed ✔️ 
BMM build 23016 is failed with only one error:
```
____ ERROR at setup of TestUsers.test_delete_account_by_administrator[gql] _____
```
Since it is not related to our changes, I think that BMM is passed for us.

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Pull request merged**
