### PR TITLE
[TEST] Remove unused files: mae.py in detection & FreezeLayers in segmentation

### PR DESCRIPTION
**Pull request by JihwanEom**
## This PR includes:
- Remove unused mae.py in detection, FreezeLayers legacies in segmentation

- [x] Pass unit tests for all TCs except known issue
- [x] Pass local e2e tests for detection/segmentation

### CODE REVIEW

**Comment by JihwanEom** [comment]
Unit test: passed except known issues
```
FAILED tests/unit/algorithms/anomaly/tasks/test_inference.py::TestInferenceTask::test_inference[ANOMALY_CLASSIFICATION] - RuntimeError: expand(torch.FloatTensor{[1, 1, 1, 33, 33]}, size=[1, -1, -1, -1]): the number of sizes pro...
FAILED tests/unit/algorithms/anomaly/tasks/test_nncf.py::TestNNCFTask::test_nncf[ANOMALY_CLASSIFICATION] - RuntimeError: expand(torch.FloatTensor{[1, 1, 1, 33, 33]}, size=[1, -1, -1, -1]): the number of sizes pro...
FAILED tests/unit/algorithms/anomaly/tasks/test_openvino.py::TestOpenVINOTask::test_openvino[ANOMALY_CLASSIFICATION] - RuntimeError: expand(torch.FloatTensor{[1, 1, 1, 33, 33]}, size=[1, -1, -1, -1]): the number of sizes pro...
FAILED tests/unit/algorithms/anomaly/tasks/test_train.py::TestTrainTask::test_train_and_load[ANOMALY_CLASSIFICATION] - RuntimeError: expand(torch.FloatTensor{[1, 1, 1, 33, 33]}, size=[1, -1, -1, -1]): the number of sizes pro...
FAILED tests/unit/algorithms/anomaly/tasks/test_inference.py::TestInferenceTask::test_inference[ANOMALY_DETECTION] - RuntimeError: expand(torch.FloatTensor{[1, 1, 1, 33, 33]}, size=[1, -1, -1, -1]): the number of sizes pro...
FAILED tests/unit/algorithms/anomaly/tasks/test_nncf.py::TestNNCFTask::test_nncf[ANOMALY_DETECTION] - RuntimeError: expand(torch.FloatTensor{[1, 1, 1, 33, 33]}, size=[1, -1, -1, -1]): the number of sizes pro...
FAILED tests/unit/algorithms/anomaly/tasks/test_openvino.py::TestOpenVINOTask::test_openvino[ANOMALY_DETECTION] - RuntimeError: expand(torch.FloatTensor{[1, 1, 1, 33, 33]}, size=[1, -1, -1, -1]): the number of sizes pro...
FAILED tests/unit/algorithms/anomaly/tasks/test_train.py::TestTrainTask::test_train_and_load[ANOMALY_DETECTION] - RuntimeError: expand(torch.FloatTensor{[1, 1, 1, 33, 33]}, size=[1, -1, -1, -1]): the number of sizes pro...
FAILED tests/unit/algorithms/anomaly/tasks/test_inference.py::TestInferenceTask::test_inference[ANOMALY_SEGMENTATION] - RuntimeError: expand(torch.FloatTensor{[1, 1, 1, 33, 33]}, size=[1, -1, -1, -1]): the number of sizes pro...
FAILED tests/unit/algorithms/anomaly/tasks/test_nncf.py::TestNNCFTask::test_nncf[ANOMALY_SEGMENTATION] - RuntimeError: expand(torch.FloatTensor{[1, 1, 1, 33, 33]}, size=[1, -1, -1, -1]): the number of sizes pro...
FAILED tests/unit/algorithms/anomaly/tasks/test_openvino.py::TestOpenVINOTask::test_openvino[ANOMALY_SEGMENTATION] - RuntimeError: expand(torch.FloatTensor{[1, 1, 1, 33, 33]}, size=[1, -1, -1, -1]): the number of sizes pro...
FAILED tests/unit/algorithms/anomaly/tasks/test_train.py::TestTrainTask::test_train_and_load[ANOMALY_SEGMENTATION] - RuntimeError: expand(torch.FloatTensor{[1, 1, 1, 33, 33]}, size=[1, -1, -1, -1]): the number of sizes pro...
```
image

Detection E2E local test: Passed except `TestToolsMPAInstanceSegmentation.test_otx_eval_openvino[Custom_Counting_Instance_Segmentation_MaskRCNN_EfficientNetB2B]: AssertionError: trained_performance[k]=0.12499999999999992, exported_performance[k]=0.0`, seems like not related with this PR.
image


Segmentation E2E local test: Passed
image

**Review by goodsong81 — APPROVED** [review]
LGTM w/ a question: layer freezing is permanently disabled?
(Sounds like nice optional feature)

**Comment by JihwanEom** [comment]
> LGTM w/ a question: layer freezing is permanently disabled? (Sounds like nice optional feature)

Yes, it was only used for `Lite-HRNet-18` (deprecated) model, current OTX does not use layer freezing model. 
I think we can expand layer freezing feature to Parameter Efficient Fine Tuning (PEFT), which is known as showing better speed-accuracy trade off in academia than freezing.

**Review by harimkang — APPROVED** [review]
@eugene123tw We don't use MAE, right?

**Pull request merged**
