### PR TITLE
[OTE] Added training tests for Object Counting Instance Segmentation

### PR DESCRIPTION
**Pull request by saltykox**
Added precommit and reallife training tests for Object Counting Instance Segmentation models:
- Custom_Counting_Instance_Segmentation_MaskRCNN_ResNet50
1. precommit training run: ote-test/1489: NNCF tests are failed due to an issue CVS-81952
2. reallife training run ote-test/1492: same issues for NNCF as for precommit tests. issue CVS-81952
- Custom_Counting_Instance_Segmentation_MaskRCNN_EfficientNetB2B
1. precommit training run: ote-test/1490: tests are failed due to an issue CVS-81996
2. reallife training run ote-test/1442 (old build before moving tests from mmdetection to training_extensions): same issues as for precommit tests. issue CVS-81996

Task: CVS-78920

### CODE REVIEW

**Comment by Ilya-Krylov** [comment]
@LeonidBeynenson please review

**Comment by Ilya-Krylov** [comment]
@LeonidBeynenson please review

**Comment by Ilya-Krylov** [comment]
run ote-test

**Comment by Ilya-Krylov** [comment]
run ote-test

**Comment by Ilya-Krylov** [comment]
run ote-test

**Comment by saltykox** [comment]
run ote-test

**Comment by yunchu** [comment]
closed due to clean up the stale branches

**Pull request closed without merging**
