### PR TITLE
[TEST] Segmentation adapters unit-tests

### PR DESCRIPTION
**Pull request by GalyaZalesskaya**
otx/algorithms/segmentation/adapters/mmseg/data
- [x] dataset.py - 88% 
- [x] pipelines.py - 99%

image

otx/algorithms/segmentation/adapters/openvino/model_wrappers
- [x] blur.py - 91% 

image

otx/algorithms/segmentation/adapters/mmseg/utils/
- [x] config_utils.py - 77%
- [x] data_utils.py - 94% 
- [x] builder.py - 35% 

image

### CODE REVIEW

**Review by supersoob — DISMISSED** [review]
Thanks for your efforts! I think it's okay to remove "_validation" in file name. Could you?

**Review by sungmanc — DISMISSED** [review]
I agree with @supersoob 's opinion, please change the filenames.
Maybe we can also remove `**_mmseg_**` since the folder name is `mmseg`.

e.g. `test_mmseg_config_utils_validation.py` --> `test_config_utils.py`

**Comment by GalyaZalesskaya** [comment]
@supersoob @sungmanc Thank you so much, I renamed files

**Review by jaegukhyun — APPROVED** [review]
LGTM, It would be much better if you add some docstrings to test functions

**Review by supersoob — APPROVED** [review]

**Review by supersoob — COMMENTED** [review]
Could you check the pre-merge integration test result?

**Comment by jaegukhyun** [comment]
> Could you check the pre-merge integration test result?

This may be resolved by rebase

**Pull request merged**
