### PR TITLE
[OTE_SDK][OTE_CLI][ANOMALY][CLASSIFICATION][DETECTION][SEGMENTATION] No model status management

### PR DESCRIPTION
**Pull request by druzhkov-paul**
Build 554 🙈 
BMM 22703 ✔️ 
BMM 22751 ✔️ 
BMM 22799 ✔️

### CODE REVIEW

**Comment by druzhkov-paul** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
Could you BMM it?

**Comment by druzhkov-paul** [comment]
run ote_sdk tests

**Comment by druzhkov-paul** [comment]
run ote_sdk tests

**Comment by druzhkov-paul** [comment]
run ote_sdk tests

**Review by Ilya-Krylov — DISMISSED** [review]

**Comment by druzhkov-paul** [comment]
run ote_sdk tests

**Comment by druzhkov-paul** [comment]
run ote_sdk tests

**Comment by druzhkov-paul** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Pull request merged**
