### PR TITLE
[DOC] added api tutorials

### PR DESCRIPTION
**Pull request by kprokofi**
This PR provides API tutorials for OTX

### CODE REVIEW

**Review by goodsong81 — CHANGES_REQUESTED** [review]
Thank you for all the effort of yours on the documentation.
Could you rebase? Emily refined the documentation structure as per Mark's request. You may want to refine the structure itself, too :)

**Comment by sungmanc** [comment]
@kprokofi , there is a conflict in this PR, could you check?

**Comment by kprokofi** [comment]
> @kprokofi , there is a conflict in this PR, could you check?

Yes, of course. I will rebase it soon

**Comment by kprokofi** [comment]
> @kprokofi , there is a conflict in this PR, could you check?

done

**Review by goodsong81 — APPROVED** [review]
Thank you, Kirill.
It's like almost notebook :)

**Review by sungmanc — APPROVED** [review]

**Pull request merged**
