### PR TITLE
Fix CVS-85318

### PR DESCRIPTION
**Pull request by vinnamkim**
- Related issue: https://jira.devtools.intel.com/browse/CVS-85318
 - Running optimize then subsequently export makes `output_model` has `FP32` precision which should be `INT8`.
 - CI result: https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/336/

### CODE REVIEW

**Comment by eugene123tw** [comment]
run ote-test

**Comment by goodsong81** [comment]
run ote-test

**Comment by eugene123tw** [comment]
LGTM. Waiting on the test result

**Comment by goodsong81** [comment]
> run ote-test

Test after rebase: https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/341/

**Comment by goodsong81** [comment]
run ote-test

**Comment by goodsong81** [comment]
> run ote-test

Retried due to many 'CUDA out of memory' errors.
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/345

**Comment by wonjuleee** [comment]
This PR contains build, dist files from mmdet, I will create new PR without these.

**Pull request closed without merging**
