### PR TITLE
🧪 Add Anomaly unit tests

### PR DESCRIPTION
**Pull request by ashwinvaidya17**
### Summary

- Add unit tests
- Rename/Move one file

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Comment by ashwinvaidya17** [comment]
I can't see for which file the pre-commit check has failed. Locally ruff checks pass for the committed files.

**Review by harimkang — COMMENTED** [review]
Thanks!
But in my opinion, tests should be added in other parts as well.
- otx.data.anomaly
- otx.core.data.dataset.anomaly
- otx.core.data.entity.anomaly
- otx.algo.anomaly.openvino_model

Could you please add the above as well?

**Comment by harimkang** [comment]
> I can't see for which file the pre-commit check has failed. Locally ruff checks pass for the committed files.

Also, the ruff issue is probably a ruff version difference, could you try `tox -e pre-commit` to check?

**Comment by harimkang** [comment]
Please modify the target with this to the releases/2.0.0 branch.

**Comment by ashwinvaidya17** [comment]
> > I can't see for which file the pre-commit check has failed. Locally ruff checks pass for the committed files.
> 
> Also, the ruff issue is probably a ruff version difference, could you try `tox -e pre-commit` to check?

When I do that it changes a bunch of unrelated files 
image

**Comment by harimkang** [comment]
I reapplied pre-commit in my environment. - https://github.com/openvinotoolkit/training_extensions/pull/3160/commits/66e9875a61ca13aad9534f35af4496ec1a918b42

**Comment by harimkang** [comment]
> Thanks! But in my opinion, tests should be added in other parts as well.
> 
> * otx.data.anomaly
> * otx.core.data.dataset.anomaly
> * otx.core.data.entity.anomaly
> * otx.algo.anomaly.openvino_model
> 
> Could you please add the above as well?

@ashwinvaidya17 
I fixed the RUFF issue. Can you add a test for the code I mentioned here?

**Comment by ashwinvaidya17** [comment]
@harimkang I've added test for AnomalyDataModule. Because internally it uses anomaly dataset and data entity, I guess it should cover the required lines. Let me know if you need anything more.

**Review by harimkang — APPROVED** [review]

**Review by jaegukhyun — APPROVED** [review]

**Pull request merged**
