### PR TITLE
[MPA Detection] Change model optimization hyperparameters and final validation

### PR DESCRIPTION
**Pull request by jaegukhyun**
This PR includes

- Change YOLOX model's optimization hyperparameters
- Anchors update when the model, whose anchors are re-clustered, is evaluated
- Change final validation checkpoint to the best epoch's weights

### CODE REVIEW

**Review by goodsong81 — CHANGES_REQUESTED** [review]
All the newly added code blocks could be refactored into _xxxx_anchors() methods. Anchor clustering is only for current SSD and I think it should be removed later.
In addition, anchors -> _anchors would be better unless it is intended as public variable.

**Comment by jaegukhyun** [comment]
@goodsong81, thank you for your review, I changed variable name, and I made _update_anchors function to refactor added code block

**Review by harimkang — APPROVED** [review]
LGTM

**Review by goodsong81 — APPROVED** [review]
LGTM.

**Pull request merged**
