### PR TITLE
[OTE_SDK] Update networkx requirements.txt

### PR DESCRIPTION
**Pull request by Ilya-Krylov**

### CODE REVIEW

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
BMM 21485 🕐

**Review by druzhkov-paul — COMMENTED** [review]
Test ote_sdk/tests/entities/test_graph.py should be fixed, I guess.

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
22028 🕐

**Pull request merged**
