### PR TITLE
[CVS-90400, CVS-91015] NNCF pruning supported tweaks

### PR DESCRIPTION
**Pull request by nikita-savelyevv**
Tweaked some pruning related parameters:
- CVS-90400 Disabled pruning for EfficientNet-V2-S as it is not working as expected
- CVS-91015 Turned off `pruning_supported` parameter visibility for anomaly models

### CODE REVIEW

**Comment by nikita-savelyevv** [comment]
run ote-test

**Comment by nikita-savelyevv** [comment]
OTE test build: https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/582/
Instance (build in progress): 10.211.120.60

**Review by alexsu52 — APPROVED** [review]
LGTM

**Review by samet-akcay — APPROVED** [review]
lgtm, thanks!

**Review by wonjuleee — APPROVED** [review]
It looks good to me too.

**Comment by samet-akcay** [comment]
@wonjuleee, @nikita-savelyevv have yet to check the changes on a BMM. Do you guys think it's safe to merge this without checking on the UI side?

**Pull request merged**
