### PR TITLE
[OTE][Develop][XAI] Detection fix two stage bbox_head error

### PR DESCRIPTION
**Pull request by dongkwan-kim01**
This is the fix of the error issued in [issue](https://github.com/openvinotoolkit/training_extensions/pull/1402#issuecomment-1336631895), which fixes the `simple_test` function in the class`SAMDetectorMixin`.
And resolving the tiling detection length Error regarding the output size assertion.

### CODE REVIEW

**Comment by dongkwan-kim01** [comment]
run ote-test

**Comment by dongkwan-kim01** [comment]
run ote-test

**Comment by dongkwan-kim01** [comment]
run ote-test

**Review by wonjuleee — COMMENTED** [review]
The changes are same with https://github.com/openvinotoolkit/training_extensions/pull/1414/files, but please resolve the conflicts first.

**Comment by sungmanc** [comment]
As Wonju's said, could you resolve the conflict? @dongkwan-kim01

**Comment by dongkwan-kim01** [comment]
@wonjuleee Maybe it's because of commit head of MPA, so if we merge the MPA then it'll be resolved, I think?

**Comment by dongkwan-kim01** [comment]
run ote-test

**Comment by sungmanc** [comment]
> @wonjuleee Maybe it's because of commit head of MPA, so if we merge the MPA then it'll be resolved, I think?

I merged your PR for MPA develop. (https://github.com/openvinotoolkit/model_preparation_algorithm)

**Comment by dongkwan-kim01** [comment]
@sungmanc @wonjuleee Sorry but I'll make another PR because of different MPA commit head(1 develop and 1 release)

**Pull request closed without merging**
