### PR TITLE
Cvs 85318 nncf precision

### PR DESCRIPTION
**Pull request by wonjuleee**
- Related issue: https://jira.devtools.intel.com/browse/CVS-85318
- Running optimize then subsequently export makes output_model has FP32 precision which should be INT8.
- CI result: https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/347/

### CODE REVIEW

**Comment by wonjuleee** [comment]
run ote-test

**Comment by wonjuleee** [comment]
run ote-test

**Comment by wonjuleee** [comment]
run ote-test

**Comment by wonjuleee** [comment]
run ote-test

**Review by goodsong81 — APPROVED** [review]
LGTM.
Tests are failing due to CI issue. Related test failures would be handled later, if any.

**Pull request merged**
