### PR TITLE
Fix and update Semi-SL Object Detection algorithms

### PR DESCRIPTION
**Pull request by kprokofi**
### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Comment by kprokofi** [comment]
- [x] Fix models initialization for student and teacher model. Fixed current Semi-SL solution
- [x] Investigated problem of underperformance of current solution. Added images filtering and tuned hyperparameters
- [x] Checked that Instance Segmentation still works better than supervised. Tuned EfficientNet
- [x] Remove RepeatDataset from instance segmentation. Teacher model as the main model trains smoother and overfits less. This allows us to reach the same perfomance as with repeat dataset
- [x] Depreciated YOLO models for Semi-SL for now since it doesn't work. The problem is unclear, but we deprioritized this task due to other more important tasks. Need to enable it as well as DETR models in the future.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/kprokofi/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/kprokofi/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



  | Pascal Tiny (150 labeled) | WGISD (12 labeled)
-- | -- | --
mobilenetV2 SSD |   |  
release 1.2.4 | 32.4 | 3.9
now | 37.9 | 33.5
  |   |  
mobilenetV2 ATSS |   |  
release 1.2.4 | 58.7 | 41.8
now | 65.4 | 45.4



</body>

</html>

**Review by jaegukhyun — DISMISSED** [review]
Generally, it seems nice. 
Could you check unit tests failure?
And one more thing, it looks like we are gonna change main model of mean-teacher model from student to teacher. What is the convention for semi-supervised model?

**Comment by kprokofi** [comment]
> Generally, it seems nice. Could you check unit tests failure? And one more thing, it looks like we are gonna change main model of mean-teacher model from student to teacher. What is the convention for semi-supervised model?

If we look at articles in that area authors stick to teacher model to be the main one. Actually, in release 1.2.4 we had teacher model as the main as well. I checked it again now and teacher model is more beneficial in object detection scenario, it trains smoother and overfits less. I also checked IS solution since it was my main concern about this changing. However, after fixing problem with student-teacher initialization, teacher model can show good results on validation for IS as well

**Comment by goodsong81** [comment]
> > Generally, it seems nice. Could you check unit tests failure? And one more thing, it looks like we are gonna change main model of mean-teacher model from student to teacher. What is the convention for semi-supervised model?
> 
> If we look at articles in that area authors stick to teacher model to be the main one. Actually, in release 1.2.4 we had teacher model as the main as well. I checked it again now and teacher model is more beneficial in object detection scenario, it trains smoother and overfits less. I also checked IS solution since it was my main concern about this changing. However, after fixing problem with student-teacher initialization, teacher model can show good results on validation for IS as well

Yeah, EMA-ed teacher models are known to be more stable and "unbiased" ;)

**Review by jaegukhyun — APPROVED** [review]

**Review by goodsong81 — APPROVED** [review]

**Pull request merged**
