### PR TITLE
[OTE][Develop][XAI] Detection fix two stage bbox_head error

### PR DESCRIPTION
**Pull request by dongkwan-kim01**
This is the fix of the error issued in [issue](https://github.com/openvinotoolkit/training_extensions/pull/1402#issuecomment-1336631895), which fixes the `simple_test` function in the class`SAMDetectorMixin`.
And resolving the tiling detection length Error regarding the output size assertion.

### CODE REVIEW

**Comment by dongkwan-kim01** [comment]
@sungmanc @wonjuleee Could you please check this PR? Because the base MPA branch is different, I've created another PR from each base MPA, but same code.

**Review by sungmanc — DISMISSED** [review]
LGTM

**Comment by sungmanc** [comment]
run ote-test
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/817/

**Review by sungmanc — APPROVED** [review]

**Review by harimkang — APPROVED** [review]

**Comment by dongkwan-kim01** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/817

This test has passed except the `test_ote_deploy` related error, which is dealing in #1421

**Pull request merged**
