### PR TITLE
[ANOMALY_CLASSIFICATION] temporal workaround to test anomaly

### PR DESCRIPTION
**Pull request by Ilya-Krylov**

### CODE REVIEW

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Review by samet-akcay — APPROVED** [review]

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by samet-akcay** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by samet-akcay** [comment]
run ote_sdk tests

**Comment by samet-akcay** [comment]
run ote_sdk tests

**Comment by samet-akcay** [comment]
run ote_sdk tests

**Comment by samet-akcay** [comment]
run ote_sdk tests

**Comment by samet-akcay** [comment]
run ote_sdk tests

**Comment by samet-akcay** [comment]
run ote_sdk tests

**Comment by samet-akcay** [comment]
run ote_sdk tests

**Comment by samet-akcay** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by samet-akcay** [comment]
run ote_sdk tests

**Comment by samet-akcay** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Pull request merged**
