### PR TITLE
[OTE_SDK] Added global variables for tasks of a certain label group type

### PR DESCRIPTION
**Pull request by AlbertvanHouten**
Added global variables for tasks that either label on a global or on a local level

### CODE REVIEW

**Comment by nervana-ff** [comment]
Can one of the admins verify this patch?

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by aiarkinx** [comment]
run ote-test

**Comment by nervana-ff** [comment]
Tests FAILED

**Comment by AlbertvanHouten** [comment]
run ote-test

**Comment by AlbertvanHouten** [comment]
run ote_sdk tests

**Comment by aiarkinx** [comment]
run ote-test

**Comment by nervana-ff** [comment]
Tests FAILED

**Comment by AlbertvanHouten** [comment]
run ote_sdk tests

**Comment by AlbertvanHouten** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
23:14:03  isort (ote_sdk)..........................................................Failed
23:14:03  - hook id: isort
23:14:03  - files were modified by this hook
23:14:03  
23:14:03  Fixing /home/jenkins/b/workspace/ote/precommit/ote_sdk_tests_runner/src/ote_sdk/ote_sdk/entities/model_template.py
23:14:03  
23:14:03  isort (ote_cli|external).................................................Passed
23:14:06  black (ote_sdk|ote_cli)..................................................Passed
23:14:07  black (rest).............................................................Passed
23:14:10  flake8...................................................................Passed
23:14:10  prettier.................................................................Passed
23:14:16  mypy (ote_sdk)...........................................................Passed
23:14:16  mypy (ote_cli)...........................................................Passed
23:14:17  mypy (external)..........................................................Passed
23:14:44  pylint...................................................................Passed
23:14:44  [Pipeline] }
23:14:44  ERROR: script returned exit code 1

**Comment by AlbertvanHouten** [comment]
I don't have the repo set up yet with style tools but tried running this file with sc platform style checker but apparently they are different. I will cancel this MR for now since there will be some changes to local/global labels with anomaly detection and segmentation having both local and global labels for anomalous label.

**Pull request closed without merging**
