### PR TITLE
[DETECTION] CVS-82196, CVS-82366

### PR DESCRIPTION
**Pull request by bognabylicka**
Fix accuracy drop of yolox after export to OV

### CODE REVIEW

**Comment by bognabylicka** [comment]
run ote-test

**Comment by bognabylicka** [comment]
run ote_sdk tests

**Comment by druzhkov-paul** [comment]
run ote-test

**Comment by Ilya-Krylov** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/ote-test/1692/

**Comment by Ilya-Krylov** [comment]
run ote-test

**Review by druzhkov-paul — APPROVED** [review]

**Pull request merged**
