### PR TITLE
Add FP16 support

### PR DESCRIPTION
**Pull request by eugene123tw**

### CODE REVIEW

**Comment by eugene123tw** [comment]
run ote-test

**Comment by eugene123tw** [comment]
run ote_sdk tests

**Comment by druzhkov-paul** [comment]
@eugene123tw please take a look at failed tests.

**Comment by druzhkov-paul** [comment]
run ote-test

**Comment by druzhkov-paul** [comment]
run ote_sdk tests

**Comment by eugene123tw** [comment]
run ote-test

**Comment by eugene123tw** [comment]
run ote_sdk tests

**Comment by druzhkov-paul** [comment]
Tests failed.

**Comment by eugene123tw** [comment]
@druzhkov-paul the CI failed for this #PR1038-77-test , however, all the tests passed according to the test report.

**Comment by druzhkov-paul** [comment]
> 14:48:22  external/mmdetection/tests/ote_cli/test_instance_segmentation.py::TestToolsInstanceSegmentation::test_ote_export[Custom_Counting_Instance_Segmentation_MaskRCNN_EfficientNetB2B] FAILED [ 61%]
14:50:23  external/mmdetection/tests/ote_cli/test_instance_segmentation.py::TestToolsInstanceSegmentation::test_ote_eval_openvino[Custom_Counting_Instance_Segmentation_MaskRCNN_EfficientNetB2B] FAILED [ 65%]
14:52:32  external/mmdetection/tests/ote_cli/test_instance_segmentation.py::TestToolsInstanceSegmentation::test_ote_demo_openvino[Custom_Counting_Instance_Segmentation_MaskRCNN_EfficientNetB2B] FAILED [ 70%]
14:53:43  external/mmdetection/tests/ote_cli/test_instance_segmentation.py::TestToolsInstanceSegmentation::test_ote_deploy_openvino[Custom_Counting_Instance_Segmentation_MaskRCNN_EfficientNetB2B] FAILED [ 72%]
14:55:37  external/mmdetection/tests/ote_cli/test_instance_segmentation.py::TestToolsInstanceSegmentation::test_ote_eval_deployment[Custom_Counting_Instance_Segmentation_MaskRCNN_EfficientNetB2B] FAILED [ 75%]
14:56:46  external/mmdetection/tests/ote_cli/test_instance_segmentation.py::TestToolsInstanceSegmentation::test_ote_demo_deployment[Custom_Counting_Instance_Segmentation_MaskRCNN_EfficientNetB2B] FAILED [ 77%]
15:02:41  external/mmdetection/tests/ote_cli/test_rotated_detection.py::TestToolsRotatedDetection::test_ote_export[Custom_Rotated_Detection_via_Instance_Segmentation_MaskRCNN_EfficientNetB2B] FAILED [ 82%]
15:04:45  external/mmdetection/tests/ote_cli/test_rotated_detection.py::TestToolsRotatedDetection::test_ote_eval_openvino[Custom_Rotated_Detection_via_Instance_Segmentation_MaskRCNN_EfficientNetB2B] FAILED [ 87%]
15:06:53  external/mmdetection/tests/ote_cli/test_rotated_detection.py::TestToolsRotatedDetection::test_ote_demo_openvino[Custom_Rotated_Detection_via_Instance_Segmentation_MaskRCNN_EfficientNetB2B] FAILED [ 92%]
15:08:01  external/mmdetection/tests/ote_cli/test_rotated_detection.py::TestToolsRotatedDetection::test_ote_deploy_openvino[Custom_Rotated_Detection_via_Instance_Segmentation_MaskRCNN_EfficientNetB2B] FAILED [ 94%]
15:10:08  external/mmdetection/tests/ote_cli/test_rotated_detection.py::TestToolsRotatedDetection::test_ote_eval_deployment[Custom_Rotated_Detection_via_Instance_Segmentation_MaskRCNN_EfficientNetB2B] FAILED [ 96%]
15:11:19  external/mmdetection/tests/ote_cli/test_rotated_detection.py::TestToolsRotatedDetection::test_ote_demo_deployment[Custom_Rotated_Detection_via_Instance_Segmentation_MaskRCNN_EfficientNetB2B] FAILED [ 98%]

**Comment by eugene123tw** [comment]
run ote-test

**Comment by eugene123tw** [comment]
run ote_sdk tests

**Comment by eugene123tw** [comment]
run ote-test

**Comment by eugene123tw** [comment]
run ote_sdk tests

**Comment by eugene123tw** [comment]
run ote-test

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by eugene123tw** [comment]
run ote-test

**Comment by eugene123tw** [comment]
run ote_sdk tests

**Comment by eugene123tw** [comment]
run ote-test

**Comment by eugene123tw** [comment]
run ote_sdk tests

**Comment by eugene123tw** [comment]
run ote-test

**Comment by eugene123tw** [comment]
run ote_sdk tests

**Comment by eugene123tw** [comment]
run ote_sdk tests

**Comment by eugene123tw** [comment]
run ote-test

**Comment by eugene123tw** [comment]
run ote-test

**Comment by eugene123tw** [comment]
run ote-test

**Comment by eugene123tw** [comment]
run ote-test

**Review by goodsong81 — APPROVED** [review]
CI test failure due to anomaly pylint would be resolved by https://github.com/openvinotoolkit/training_extensions/pull/1056.

Is this PR need to be included in SC1.1 / OTE 0.2.0?

**Comment by eugene123tw** [comment]
@goodsong81 yes, this model is in the plan of SC1.1. Perhaps, I can run the test after merging #1056 ?

**Comment by goodsong81** [comment]
I think it's verified.

**Pull request merged**
