### PR TITLE
[OTE_SDK] expand ModelTemplate.is_global

### PR DESCRIPTION
**Pull request by leoll2**
Add anomaly classification to the list of global tasks

### CODE REVIEW

**Comment by leoll2** [comment]
run ote_sdk tests

**Comment by nervana-ff** [comment]
Can one of the admins verify this patch?

**Review by druzhkov-paul — APPROVED** [review]

**Review by druzhkov-paul — CHANGES_REQUESTED** [review]
@leoll2 Please fix `ote_sdk/tests/entities/test_model_template.py::TestModelTemplate::test_model_template_is_task_global` test.

**Comment by druzhkov-paul** [comment]
run ote_sdk tests

**Comment by leoll2** [comment]
e2e: https://ci.iotg.sclab.intel.com/job/IMPT/job/IMPTOps/26949/

**Comment by leoll2** [comment]
run ote_sdk tests

**Comment by AlbertvanHouten** [comment]
Hey, I have addressed this by updating the TaskType enum (https://jira.devtools.intel.com/browse/CVS-81165) here https://github.com/openvinotoolkit/training_extensions/pull/983. I think this MR can be closed in favour mine.

**Comment by leoll2** [comment]
@AlbertvanHouten Thanks for adding the attribute to `TaskType`. Rather than closing this MR, I suggest instead to merge it (because `ModelTemplate.is_global` is currently wrong, we don't want broken code) and immediately open a new ticket to deprecate/remove it and replace any usage in SC and OTE.

**Review by druzhkov-paul — APPROVED** [review]

**Pull request merged**
