### PR TITLE
Fix mpa - d-o-r export discrepancy

### PR DESCRIPTION
**Pull request by sovrasov**
MPA PR: https://github.com/openvinotoolkit/model_preparation_algorithm/pull/83
build: http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=pr-ote-test-725&environment=iotg-dev-workstation-10 (see TestToolsMPAMultilabelClassification::test_ote_eval_openvino)

### CODE REVIEW

**Comment by sovrasov** [comment]
run ote-test

**Comment by supersoob** [comment]
it fails at classification export test. could you check? http://validationreports.sclab.intel.com:8006/reports/test_result/636e6cee1018704b64db7a94

**Comment by sovrasov** [comment]
run ote-test

**Comment by sovrasov** [comment]
run ote-test

**Comment by sovrasov** [comment]
@supersoob tests are passed http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=pr-ote-test-750&environment=iotg-dev-workstation-10
Now only anomaly tests fail sometimes.

**Review by supersoob — APPROVED** [review]
LGTM

**Review by JihwanEom — APPROVED** [review]

**Review by kprokofi — APPROVED** [review]

**Pull request merged**
