### PR TITLE
sstrehlk/Changed directories structure for anomaly templates.

### PR DESCRIPTION
**Pull request by sstrehlk**
Changed directories structure for anomaly templates to be in line with other backends.

### CODE REVIEW

**Comment by sstrehlk** [comment]
Jenkins build for anomaly tests:
https://ci-ote.iotg.sclab.intel.com/job/ote/job/ote-test/1784/

**Review by samet-akcay — DISMISSED** [review]
Thanks for refactoring this. I'll approve this. Let's see if the CI passes 🤞

**Comment by sstrehlk** [comment]
Jenkins build retriggered after update in ote_reference_root_dir_fx fixture 
https://ci-ote.iotg.sclab.intel.com/job/ote/job/ote-test/1786/

**Comment by sstrehlk** [comment]
There are fails for padim model on build https://ci-ote.iotg.sclab.intel.com/job/ote/job/ote-test/1786/, but the same fails are for develop branch https://ci-ote.iotg.sclab.intel.com/job/ote/job/ote-test/1788/ @samet-akcay please check if we should enter a bug for it.

**Comment by sstrehlk** [comment]
The https://ci-ote.iotg.sclab.intel.com/job/ote/job/ote-test/1792/ triggered after fixing issue related to early_stopping.

**Review by samet-akcay — DISMISSED** [review]

**Comment by sstrehlk** [comment]
One more correction related to paths added
- There are no fails in anomaly component tests - http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=ote-test-1798&environment=iotg-dev-workstation-09
- There are three fails in Unit tests - http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=ote-test-1799&environment=iotg-dev-workstation-09 , but these fails are not related to current change  
- There are no fails in anomaly performance tests - http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=ote-test-1797&environment=iotg-dev-workstation-12

@samet-akcay please approve once again.

**Review by samet-akcay — APPROVED** [review]

**Pull request merged**
