### PR TITLE
Enable `deterministic` for anomalib and visual prompting

### PR DESCRIPTION
**Pull request by sungchul1**
### Summary

Those tasks are implemented based on pytorch lightning.
In order to use `deterministic=True`, it should be set as `deterministic=warn` for `Trainer` (because otx supports `torch==1.13`), but otx only gets `deterministic` argument as `bool`.
So, inner patching in `task.train` is required to use `deterministic=True`.

Reference:
https://github.com/Lightning-AI/lightning/blob/a020506a81a671e380872aa5e435647b549e14e6/src/pytorch_lightning/trainer/connectors/accelerator_connector.py#L222-L227

- [x] Update `deterministic` from `False` to `True`
- [x] Remove unused pot test modules in visual prompting e2e test

### How to test

```shell
$ tox -e tests-ano-py310 -- tests/integration/cli/anomaly
================================================================= short test summary info ==================================================================FAILED tests/integration/cli/anomaly/test_anomaly_classification.py::TestToolsAnomalyClassification::test_nncf_optimize[ote_anomaly_classification_stfpm] - AssertionError: Traceback (most recent call last):
FAILED tests/integration/cli/anomaly/test_anomaly_classification.py::TestToolsAnomalyClassification::test_nncf_optimize[ote_anomaly_classification_padim] - AssertionError: Traceback (most recent call last):
FAILED tests/integration/cli/anomaly/test_anomaly_detection.py::TestToolsAnomalyDetection::test_nncf_optimize[ote_anomaly_detection_stfpm] - AssertionError: Traceback (most recent call last):
FAILED tests/integration/cli/anomaly/test_anomaly_detection.py::TestToolsAnomalyDetection::test_nncf_optimize[ote_anomaly_detection_padim] - AssertionError: Traceback (most recent call last):
FAILED tests/integration/cli/anomaly/test_anomaly_segmentation.py::TestToolsAnomalySegmentation::test_nncf_optimize[ote_anomaly_segmentation_stfpm] - AssertionError: Traceback (most recent call last):
FAILED tests/integration/cli/anomaly/test_anomaly_segmentation.py::TestToolsAnomalySegmentation::test_nncf_optimize[ote_anomaly_segmentation_padim] - AssertionError: Traceback (most recent call last):
=================================================== 6 failed, 57 passed, 1 warning in 723.59s (0:12:03) ====================================================
-> All fails occurred because nvcc is unavailable in ikvensx010

$ tox -e tests-visprompt-py310 -- tests/integration/cli/visual_prompting
=================================================== 8 passed, 2 skipped, 1 warning in 169.33s (0:02:49) ====================================================

$ tox -e tests-ano-py310 -- tests/e2e/cli/anomaly
-WIP-

$ tox -e tests-visprompt-py310 -- tests/e2e/cli/visual_prompting
========================================================= 7 passed, 1 warning in 176.92s (0:02:56) =========================================================
```

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Comment by sungchul1** [comment]
@harimkang Is there anything to test if it works well? I already tested it on visual prompting.

**Comment by harimkang** [comment]
> @harimkang Is there anything to test if it works well? I already tested it on visual prompting.

As far as I know, most tasks use deterministic as True in their integration tests. I think we just need to change that.
What do you think @jaegukhyun ?

**Comment by sungchul1** [comment]
> > @harimkang Is there anything to test if it works well? I already tested it on visual prompting.
> 
> As far as I know, most tasks use deterministic as True in their integration tests. I think we just need to change that. What do you think @jaegukhyun ?

It can be a candidate. I'll add it.

**Comment by jaegukhyun** [comment]
Could you update intg, e2e, regression tests for anomalib task?

**Comment by sungchul1** [comment]
> Could you update intg, e2e, regression tests for anomalib task?

I'll update them for anomalib and visual prompting after merging 1.4.0 to develop.

**Review by jaegukhyun — DISMISSED** [review]

**Comment by sungchul1** [comment]
@harimkang @jaegukhyun I updated integration and e2e tests.
And I occurred GPU related errors in anomaly tests, so I try to check it in CI.

**Review by jaegukhyun — DISMISSED** [review]

**Comment by harimkang** [comment]
@ashwinvaidya17 @djdameln This modifies the deterministic of the anomaly task. Could you take a look and see if there are any problems?

**Review by sungmanc — APPROVED** [review]

**Review by ashwinvaidya17 — APPROVED** [review]
Thanks. Looks good to me

**Pull request merged**
