### PR TITLE
[Anomaly Task] Move to learning parameters

### PR DESCRIPTION
**Pull request by ashwinvaidya17**
Move all HPO parameters to learning parameters

🧪https://ci-ote.iotg.sclab.intel.com/job/ote/job/ote-test/1892/

### CODE REVIEW

**Comment by ashwinvaidya17** [comment]
run ote_test

**Comment by ashwinvaidya17** [comment]
run ote-test

**Comment by ashwinvaidya17** [comment]
Test failed http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=ote-test-1891&environment=iotg-dev-workstation-12. I'll try to run it locally

**Review by yunchu — APPROVED** [review]
checked with SC build (https://ci.iotg.sclab.intel.com/job/IMPT/job/IMPTOps/34223/) and work as expected.

**Review by eunwoosh — APPROVED** [review]

**Pull request merged**
