### PR TITLE
Adds support of NNCF for OTESeg

### PR DESCRIPTION
**Pull request by evgeny-izutov**
Build on BMM: 21415 ✔️
Train on BMM: finished ✔️
NNCF optimization: need to update NNCF version on SC

### CODE REVIEW

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by evgeny-izutov** [comment]
Build on BMM: 21415 ✔️
Train on BMM: finished ✔️
NNCF optimization: need to update NNCF version on SC

**Comment by druzhkov-paul** [comment]
@MaximProshin Do you confirm that you are going to drive NNCF update?

**Comment by MaximProshin** [comment]
@druzhkov-paul , there is currently a discussion about NNCF requirements on SC side. @alexsu52 , is driving the discussion. Let's sort it out before the merge. 
cc @AlexanderDokuchaev

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
@MaximProshin we don't mind to merge it as is, as soon as it does not break anything. 
But it is your (with @alexsu52 ) responsibility to update nncf dependencies where it is needed.
The same for https://github.com/openvinotoolkit/training_extensions/pull/780 (to be tested on BMM)

What do you think?

**Comment by MaximProshin** [comment]
> @MaximProshin we don't mind to merge it as is, as soon as it does not break anything. But it is your (with @alexsu52 ) responsibility to update nncf dependencies where it is needed. The same for #780 (to be tested on BMM)
> 
> What do you think?

Ok, I think it's fair.

**Pull request merged**
