### PR TITLE
Added unit tests for 3d Object Detection, fix linter for the rest of the files.

### PR DESCRIPTION
**Pull request by kprokofi**
### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have ran e2e tests and there is no issues.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Comment by kprokofi** [comment]
This PR includes unit tests for dataset and algo part. Also, linter fixes for dataset, KITTI utils and metric validation. 
However, one serious limitation was found with 3d AP, which needs to be investigated and fixed. For now, I didn't add unit tests for evaluation part due to that fact.

**Review by sovrasov — DISMISSED** [review]

**Comment by sovrasov** [comment]
@kprokofi it looks like 3d od integration tests are failing

**Comment by kprokofi** [comment]
> @kprokofi it looks like 3d od integration tests are failing

fixed

**Review by chuneuny-emily — APPROVED** [review]

**Review by sovrasov — APPROVED** [review]

**Comment by sovrasov** [comment]
Unit tests are actually passed: 
image
However, job name doesn't match, so the status can not be updated

**Pull request merged**
