### PR TITLE
[ANOMALY] 🐞 Remove hard-coded label names from the task.

### PR DESCRIPTION
**Pull request by samet-akcay**
# Description
This PR removes hard-coded `Normal` and `Anomalous` labels from the anomaly tasks. 

- Fixes [CVS-86968](https://jira.devtools.intel.com/browse/CVS-86968)
- BMM [33907](https://ci.iotg.sclab.intel.com/job/IMPT/job/IMPTOps/33907/) ✅
- SC [Project](https://10.211.120.59/)
- [CI](http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=pr-ote-test-441&environment=iotg-dev-workstation-08)

### CODE REVIEW

**Comment by samet-akcay** [comment]
run ote_tests

**Comment by goodsong81** [comment]
run ote_test

**Review by ashwinvaidya17 — APPROVED** [review]
Thanks for addressing this!

**Comment by goodsong81** [comment]
run ote-test

**Comment by goodsong81** [comment]
Waiting for the test result: https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/421/

**Comment by samet-akcay** [comment]
run ote-test

**Comment by samet-akcay** [comment]
run ote-test

**Pull request closed without merging**
