### PR TITLE
[Dev] Convert all dataset to dummy data and move them into tests/assets

### PR DESCRIPTION
**Pull request by sungmanc**
# Summary
* Convert all datasets to dummy dataset
* Move all datasets to `tests/assets/`
* Change the tests to apply the changing of data path

### CODE REVIEW

**Review by goodsong81 — DISMISSED** [review]
Looks far much better.

**Comment by sungmanc** [comment]
FYI. @supersoob , @jaegukhyun , This PR affects to unit-tests, So I edited some codes (https://github.com/openvinotoolkit/training_extensions/pull/1640/commits/574c7d50c57f4706bb4e3790dcbfa1e4ed9144ce).

**Review by supersoob — DISMISSED** [review]
Looks good to me. Thanks for revising the affected codes.

**Review by jaegukhyun — APPROVED** [review]
LGTM, but I'd like to check integration test before merge this PR

**Comment by sungmanc** [comment]
It all passes CI tests. @jaegukhyun , @supersoob , @goodsong81  could you recheck this?
image

**Review by goodsong81 — APPROVED** [review]

**Pull request merged**
