### PR TITLE
[DEV] Add MPA pyx files to source distribution

### PR DESCRIPTION
**Pull request by vinnamkim**
- Fix source distribution for *.pyx files, https://github.com/openvinotoolkit/model_preparation_algorithm/pull/127.

Signed-off-by: Kim, Vinnam <vinnam.kim@intel.com>

### CODE REVIEW

**Comment by vinnamkim** [comment]
run ote-test

**Review by goodsong81 — CHANGES_REQUESTED** [review]
Sorry for inconvenience, but could you apply the latest commit? I've just merged the MPA PR.

**Comment by goodsong81** [comment]
No need for re-run CI tests as they are actually identical.

**Review by goodsong81 — DISMISSED** [review]
LGTM. Will merge after CI test.
BTW, I would change the PR title more specifically to identify actual change.

**Comment by sungmanc** [comment]
run ote-test

**Comment by sungmanc** [comment]
Previous CI test was failed(https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/877/), I'm not sure about the reason. I just re-triggered.

Let's check this result: https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/878/

**Comment by vinnamkim** [comment]
run ote-test

**Comment by vinnamkim** [comment]
Because of https://github.com/openvinotoolkit/training_extensions/pull/1529#issuecomment-1384687950, rebased to the latest develop branch and re-ran tests.

**Review by goodsong81 — DISMISSED** [review]
http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=pr-ote-test-881&environment=iotg-dev-workstation-08
Test result looks good.

@vinnamkim Somehow this PR was not merged and missing in releases/v0.5.0. Is it OK? Or, we might need to replicate this change to release branch.

**Pull request merged**
