### PR TITLE
Fix rotated detection data pipeline

### PR DESCRIPTION
**Pull request by eugene123tw**
### Summary

Fix rotated detection data pipeline

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have ran e2e tests and there is no issues.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Review by sovrasov — APPROVED** [review]

**Comment by sovrasov** [comment]
Can we use `src/otx/algorithms/detection/configs/base/data/iseg_efficientnet_data_pipeline.py` and other similar configs as a data pipeline for rotated det as well?

**Comment by sovrasov** [comment]
Thanks for the prompt fix!

**Comment by eugene123tw** [comment]
> Can we use `src/otx/algorithms/detection/configs/base/data/iseg_efficientnet_data_pipeline.py` and other similar configs as a data pipeline for rotated det as well?

It makes sense to use the same file; however, I didn't use it because different tasks have different domain names in the training pipeline. Thus, I can't use the same file without finding a way to overwrite the domain (see the pipeline below). To avoid further breaking changes, I only fixed the keep_ratio part.
```
train_pipeline = [
    dict(
        type="LoadResizeDataFromOTXDataset",
        load_ann_cfg=dict(
            type="LoadAnnotationFromOTXDataset",
            domain="rotated_detection",
            with_bbox=True,
            with_mask=True,
            poly2mask=False,
        ),
        resize_cfg=dict(
            type="Resize",
            img_scale=__img_size,
            keep_ratio=False,
        ),
        enable_memcache=True,  # Cache after resizing image & annotations
    ),
]
```

**Review by sungchul1 — APPROVED** [review]

**Comment by chuneuny-emily** [comment]
@eugene123tw - Could you ensure future refactoring aligns with previous configurations or provide experiment results on changes? This would help in tracking changes and preventing potential issues like the recent performance drop. https://github.com/openvinotoolkit/training_extensions/blob/releases/1.2.4/otx/algorithms/detection/configs/rotated_detection/efficientnetb2b_maskrcnn/data_pipeline.py

**Comment by chuneuny-emily** [comment]
@eugene123tw - If this issue reproduces with OTX2.0.0, please make sure to create one more fix for develop branch.

**Pull request merged**
