### PR TITLE
Update references for validation FQs 

### PR DESCRIPTION
**Pull request by AlexanderDokuchaev**

### CODE REVIEW

**Review by sungmanc — CHANGES_REQUESTED** [review]
Thanks for quick correction ! 

When I executed E2E tests with anomaly tasks, I got results below, could you also check with other tasks (classification, anomaly, segmentation)?
image

To execute E2E tests, you could use `pytest -s -v tests/e2e/cli/`

**Comment by alexsu52** [comment]
> Thanks for quick correction !
> 
> When I executed E2E tests with anomaly tasks, I got results below, could you also check with other tasks (classification, anomaly, segmentation)? image
> 
> To execute E2E tests, you could use `pytest -s -v tests/e2e/cli/`

What commit caused the tests to fail?

This PR does not touch classification, anomaly, segmentation tasks. The issue that you mentioned requires analyze and does not stop merge this PR.

**Comment by sungmanc** [comment]
> What commit caused the tests to fail?
> 
> This PR does not touch classification, anomaly, segmentation tasks. The issue that you mentioned requires analyze and does not stop merge this PR.

This PR is just targeting the detection model's references. What I want to tell is we also need to change classification, anomaly, and segmentation's references. Above error is not related with any other commits.

**Comment by alexsu52** [comment]
> This PR is just targeting the detection model's references. What I want to tell is we also need to change classification, anomaly, and segmentation's references. Above error is not related with any other commits.

What do you mean under "Above error is not related with any other commits."? I hope you merged the mentioned tests in the repository based on that tests passed.

**Comment by AlexanderDokuchaev** [comment]
@alexsu52 @sungmanc
With anomaly, It's possible problem with ignored_scope, that was tested on previous openvino version. I will check, and update with PR.

**Comment by AlexanderDokuchaev** [comment]
@alexsu52 @sungmanc 
Yes, problem was in name of layers, as result ignored_scope was incorrected.

Same problem in segmentation models, it will be fixed in another pr.

**Comment by sungmanc** [comment]
> > This PR is just targeting the detection model's references. What I want to tell is we also need to change classification, anomaly, and segmentation's references. Above error is not related with any other commits.
> 
> What do you mean under "Above error is not related with any other commits."? I hope you merged the mentioned tests in the repository based on that tests passed.

Since this PR only changes the references for the detection task except for other tasks (classification, segmentation, ...), I met errors when I executed the E2E tests for overall tasks. So, I shared the error message example (anomaly case, attached above).

"Above error is not related with any other commits" means this PR couldn't cover all tasks. I'm sorry this sentence might be misleading.

@AlexanderDokuchaev , Thanks for checking the anomaly task, as you said, please make another PR for other tasks (segmentation)

**Review by sungmanc — APPROVED** [review]

**Review by goodsong81 — APPROVED** [review]

**Pull request merged**
