### PR TITLE
Assign best score in segmentation train task

### PR DESCRIPTION
**Pull request by JihwanEom**
## This PR includes:
- Assign best score in OTESegmentationTrainingTask

### CODE REVIEW

**Comment by goodsong81** [comment]
run ote-test

**Review by goodsong81 — APPROVED** [review]
LGTM. Let's see the test result.

**Comment by goodsong81** [comment]
Build: https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/384/
Test result: http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=pr-ote-test-384&environment=iotg-dev-workstation-18

**Review by harimkang — APPROVED** [review]
LGTM

**Pull request merged**
