### PR TITLE
[IMAGE_CLASSIFICATION] Updating the deep object reid submodule

### PR DESCRIPTION
**Pull request by alexsu52**
Added NNCF support for the deep object reid.

### CODE REVIEW

**Comment by alexsu52** [comment]
run ote_sdk tests

**Comment by kprokofi** [comment]
@LeonidBeynenson , along with NNCF classification task this PR is going to fix following tickets:

https://jira.devtools.intel.com/browse/CVS-73878
https://jira.devtools.intel.com/browse/CVS-73777
https://jira.devtools.intel.com/browse/CVS-73773

SC build 21422 ✔️

**Review by kprokofi — DISMISSED** [review]

**Comment by kprokofi** [comment]
run ote_sdk tests

**Comment by alexsu52** [comment]
SC build 21442

@Ilya-Krylov please take a look.
tests/models/test_basic_flow.py::TestBasicFlow::test_train_model_rest[detection-GPU] Failed

**Comment by kprokofi** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
@alexsu52 re-build BMM with tests please

**Comment by alexsu52** [comment]
> @alexsu52 re-build BMM with tests please

@Ilya-Krylov Done

SC build 21497

**Comment by Ilya-Krylov** [comment]
@kprokofi could you check on BMM (build 21497) that everything still works as expected?

**Comment by Ilya-Krylov** [comment]
@alexsu52 please don't override BMM as soon as it is built, let @kprokofi to check by himself

**Pull request merged**
