### PR TITLE
[FEATURE] Add FP16 IR export support

### PR DESCRIPTION
**Pull request by sovrasov**
Flag `--half-precision` was added to the export tool.

@harimkang @sungmanc please have a look at CLI changes

### CODE REVIEW

**Comment by harimkang** [comment]
The CLI changes don't seem to be a problem :)

**Review by sungmanc — DISMISSED** [review]
LGTM, no problem with `export` CLI

**Review by goodsong81 — CHANGES_REQUESTED** [review]
LGTM, but I think we should not include this PR in this release as we need additional validation. Let's merge after code fix.
(No request change, but to prevent merge :))

**Comment by sovrasov** [comment]
@goodsong81 @sungmanc I think we could consider merging this, since the release branch was created

**Review by goodsong81 — APPROVED** [review]

**Review by kprokofi — COMMENTED** [review]
Overall looks good to me, but I thing we should create FP16 export test

**Review by kprokofi — APPROVED** [review]

**Comment by sovrasov** [comment]
> Overall looks good to me, but I thing we should create FP16 export test

I'll address this in a separate PR, when FP16 inference on CI will be available.

**Pull request merged**
