### PR TITLE
[NNCF] Requirements

### PR DESCRIPTION
**Pull request by alexsu52**
Added NNCF to requirements.txt

### CODE REVIEW

**Comment by alexsu52** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by nervana-ff** [comment]
Can one of the admins verify this patch?

**Comment by alexsu52** [comment]
test build 976

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Review by AlexanderDokuchaev — DISMISSED** [review]

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by alexsu52** [comment]
run ote_sdk tests

**Comment by alexsu52** [comment]
run ote_sdk tests

**Pull request merged**
