### PR TITLE
Fix soft predictions for Semantic Segmentation

### PR DESCRIPTION
**Pull request by kprokofi**
### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have ran e2e tests and there is no issues.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Review by sovrasov — APPROVED** [review]

**Review by wonjuleee — COMMENTED** [review]
Have you measured the elapsed time? Please provide the comparison.

**Comment by kprokofi** [comment]
> Have you measured the elapsed time? Please provide the comparison.

I will, I can provide some inference FPS benchmark before and after this change, but if we want to obtain probabilities, we can't avoid using softmax. In OTX1.6 we use softmax in forward.

**Comment by wonjuleee** [comment]
> > Have you measured the elapsed time? Please provide the comparison.
> 
> I will, I can provide some inference FPS benchmark before and after this change, but if we want to obtain probabilities, we can't avoid using softmax. In OTX1.6 we use softmax in forward.

Is there any requirement for having probabilities for every pixels?
As I previously mentioned, sseg requires more about argmax because of the computation overhead of softmax.

**Comment by sovrasov** [comment]
@wonjuleee in 1.6 we have a softmax node embedded into all sseg models, so I assume the performance is roughly the same as with 1.6. Geti computes confidence for each polygon and visualizes it, and we have to agree with them to drop that feature before removing softmax.

**Comment by kprokofi** [comment]
w/o softmax: 
Latency:
[ INFO ]    Median:        230.18 ms
[ INFO ]    Average:       231.61 ms
[ INFO ]    Min:           138.25 ms
[ INFO ]    Max:           462.99 ms
[ INFO ] Throughput:   51.70 FPS

With softmax: 
[ INFO ] Latency:
[ INFO ]    Median:        232.39 ms
[ INFO ]    Average:       233.78 ms
[ INFO ]    Min:           100.13 ms
[ INFO ]    Max:           408.05 ms
[ INFO ] Throughput:   51.23 FPS

**Review by harimkang — APPROVED** [review]

**Pull request merged**
