### PR TITLE
[OTE] Comment out time.sleep(2) in EpochRunnerWithCancel

### PR DESCRIPTION
**Pull request by JihwanEom**
### Summary
- Comment out time.sleep(2) in EpochRunnerWithCancel for all tasks. (Deadlock is not worried for single-gpu)

### CODE REVIEW

**Review by goodsong81 — CHANGES_REQUESTED** [review]
Could you add comments?
ex) # TODO: uncomment this line or resolve root cause of deadlock issue if multi-GPUs need to be supported.

**Comment by JihwanEom** [comment]
> Could you add comments? ex) # TODO: uncomment this line or resolve root cause of deadlock issue if multi-GPUs need to be supported.

Revised. Thank you.

**Review by harimkang — APPROVED** [review]
LGTM,
I think there is no problem because the multi-gpu environment is not currently used, but I would like to proceed with the SC test. I would like you to check and comment on this before it is merged with SC.

**Review by goodsong81 — APPROVED** [review]
LGTM

**Pull request merged**
