### PR TITLE
[DEV] Edit the dummy datasets to toy datasets (CVS-103301)

### PR DESCRIPTION
**Pull request by sungmanc**
# Summary
* This PR is a remedy for [CVS-103301](https://jira.devtools.intel.com/browse/CVS-103301)
* Convert the detection dummy datasets to toy datasets
* Convert the segmentation dummy datasets to more easy ones.
* Change the test files
* Had no FAIL cases in instance_segmentation tests even `nncf_optimize` was included. (tests/integration/cli/detection)
image
image

* Got all PASSED in unit tests (tests/unit)

### CODE REVIEW

**Comment by JihwanEom** [comment]
Does this PR not include dataset for semantic segmentation?

**Comment by JihwanEom** [comment]
How about the accuracy? Is it not always 0.0?

**Comment by sungmanc** [comment]
> How about the accuracy? Is it not always 0.0?

In the current stats, some models showed 0.0 F-measure. However, accuracy is not important for NNCF. If there is a single prediction, it is okay regardless of whether it is positive or not

**Comment by JihwanEom** [comment]
> > How about the accuracy? Is it not always 0.0?
> 
> In the current stats, some models showed 0.0 F-measure. However, accuracy is not important for NNCF. If there is a single prediction, it is okay regardless of whether it is positive or not

Sounds good! Thank you for kind explanation.

**Comment by sungmanc** [comment]
image

**Review by goodsong81 — APPROVED** [review]
Nice fix!

**Review by harimkang — APPROVED** [review]

**Pull request merged**
