### PR TITLE
[NNCF/POT] POT and NNCF parameter group UI hiding

### PR DESCRIPTION
**Pull request by nikita-savelyevv**
Disabled visibility of POT and NNCF -related parameter groups for all algo backends #ref 76294

### CODE REVIEW

**Comment by nikita-savelyevv** [comment]
run ote_sdk tests

**Comment by nikita-savelyevv** [comment]
run ote_sdk tests

**Comment by nikita-savelyevv** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
I killed CI job since it was hanging

**Comment by nikita-savelyevv** [comment]
run ote_sdk tests

**Comment by nikita-savelyevv** [comment]
run ote_sdk tests

**Review by AlexanderDokuchaev — APPROVED** [review]

**Comment by nikita-savelyevv** [comment]
@Ilya-Krylov, should be ready for merge, @alexsu52 won't be able to review this week

**Pull request merged**
