### PR TITLE
[OTE_SDK] Default hotkey for empty label

### PR DESCRIPTION
**Pull request by druzhkov-paul**
In the task chain scenario there is more than one empty label and they can't use the same hotkey, so remove the default value.

### CODE REVIEW

**Comment by druzhkov-paul** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
please fix test

**Comment by druzhkov-paul** [comment]
run ote_sdk tests

**Comment by druzhkov-paul** [comment]
BMM 22747 ✔️

**Pull request merged**
