### PR TITLE
Added a getter and a setter for __metadata

### PR DESCRIPTION
**Pull request by A-Artemis**
The metadata property of DatasetItemEntity has been removed and placed with get_metadata() and set_metadata(). Usages of .metadata have been updated.

### CODE REVIEW

**Review by samet-akcay — DISMISSED** [review]
thanks, look good to me

**Comment by samet-akcay** [comment]
run ote-tests

**Comment by A-Artemis** [comment]
429 out of the possible 430 tests have passed. The test which failed is test_prediction_to_annotation_converter.py as my system doesn't have openvino.model_zoo.model. 
image

**Review by goodsong81 — COMMENTED** [review]
Format & test results look good to me.
However, could you let us know why this change is needed?
There are many @property fields w/o explicit get/setter in OTE SDK.
It looks a convention to have @property & @xxxx.setter.

**Review by goodsong81 — APPROVED** [review]

**Review by samet-akcay — APPROVED** [review]

**Comment by goodsong81** [comment]
Merging this PR; test verified by reporter's manual test results.

**Pull request merged**
