### PR TITLE
🐞 Bugfix: Set reverse_input_channels to True in OpenVINO models

### PR DESCRIPTION
**Pull request by ashwinvaidya17**
### Summary

Fixes: CVS-129988

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Review by chuneuny-emily — APPROVED** [review]

**Comment by sovrasov** [comment]
Do we need changes from https://github.com/openvinotoolkit/model_api/pull/152 in this PR?

**Comment by ashwinvaidya17** [comment]
> Do we need changes from [openvinotoolkit/model_api#152](https://github.com/openvinotoolkit/model_api/pull/152) in this PR?

I don't think so as media pipe already passes RGB image to the inference model. But my understanding might be incorrect here.

**Comment by sovrasov** [comment]
OTX also uses RGB for demos and OV tasks: https://github.com/openvinotoolkit/training_extensions/blob/releases/1.4.0/src/otx/api/entities/image.py#L99

**Comment by ashwinvaidya17** [comment]
I'll leave that decision to the maintainers. I agree that OTX's OpenVINO inference is affected by the change in modelAPI but as of now since Geti does not use OTX for OpenVINO inference, the missing modelAPI upgrade should not affect Geti. I guess upgrading modelAPI version in OTX is more challenging given the current timeline of release. 
As for the actual issue, there were two. Turns out the RGB issue was not the actual reason for 0% score on normal images. That was probably a coincidental discovery during the hunt. The actual reason was that normal images also reported anomaly scores. So a good image would report anomaly score of 0. The solution implemented in modelAPI currently flips the score reported when the predicted label is Normal. So the users now see normal score of 100%

**Comment by sovrasov** [comment]
> I'll leave that decision to the maintainers. I agree that OTX's OpenVINO inference is affected by the change in modelAPI but as of now since Geti does not use OTX for OpenVINO inference, the missing modelAPI upgrade should not affect Geti. I guess upgrading modelAPI version in OTX is more challenging given the current timeline of release. As for the actual issue, there were two. Turns out the RGB issue was not the actual reason for 0% score on normal images. That was probably a coincidental discovery during the hunt. The actual reason was that normal images also reported anomaly scores. So a good image would report anomaly score of 0. The solution implemented in modelAPI currently flips the score reported when the predicted label is Normal. So the users now see normal score of 100%

I see, according to the discussion in jira, let's avoid upgrading MAPI here. To be precise, Geti still uses OTX inference tasks for batch inference (see Ludo's comment in CVS-130051). If now in OTX 1.4 anomaly inference task works somehow (probably because it doesn't use MAPI), I'm ok with this solution.

**Review by sovrasov — APPROVED** [review]

**Comment by ashwinvaidya17** [comment]
> Geti still uses OTX inference tasks for batch inference (see Ludo's comment in CVS-130051)

Hmm I wasn't aware. I'll have a closer look at this task later. For now I am merging this. It does not affect the 0% issue but it closes one loose end.

**Pull request merged**
