### PR TITLE
Fixing XAI tests

### PR DESCRIPTION
**Pull request by negvet**
### Summary
Fixing dtype issue in validity tests.

Move xai api tests into corresponding cli directories 

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Comment by negvet** [comment]
@GalyaZalesskaya TestOVDetTilXAIAPI does not pass for me locally. All saliency maps are None. Did it work well for you when you enabled it?

**Comment by jaegukhyun** [comment]
Are all tests in this PR passed locally?

**Comment by negvet** [comment]
> Are all tests in this PR passed locally?

Nope, TestOVDetTilXAIAPI is not yet

**Comment by GalyaZalesskaya** [comment]
> @GalyaZalesskaya TestOVDetTilXAIAPI does not pass for me locally. All saliency maps are None. Did it work well for you when you enabled it?

Thank you for checking this out. I found the reason for this problem. 
The initial generated image for tiling is (480x640), and for PyTorch model, everything goes well. While for IR because `ir_scale_factor` `tile_size` becomes 2243, which is 5 times more than the initial image. The detector doesn't get predictions and saliency maps for each class are None and don't get returned as metadata.

This problem will be fixed after merging this [PR#2337](https://github.com/openvinotoolkit/training_extensions/pull/2337) with restricting `ir_scale_factor` for IR model. But before that, we can disable this test. 

Another temporary solution is to increase generated image size [here](https://github.com/openvinotoolkit/training_extensions/blob/9810ff0d12e3b880a0a7c15f7854ac3f5190b846/tests/integration/api/detection/api_detection.py#L51) to (1480, 1640), but it affects testing time. So it's better to disable the test with a comment to return it after merging PR#2337

**Comment by negvet** [comment]
Thank you @GalyaZalesskaya

**Comment by negvet** [comment]
If pre-commit is passed, can be merged.

**Review by GalyaZalesskaya — APPROVED** [review]

**Review by jaegukhyun — APPROVED** [review]

**Pull request merged**
