### PR TITLE
updating default task configurations

### PR DESCRIPTION
**Pull request by yunchu**
To specify which learning parameters for the task can be used for the target of the auto-hpo.
This PR is for this ticket: [CVS-79795](https://jira.devtools.intel.com/browse/CVS-79795])

### CODE REVIEW

**Comment by yunchu** [comment]
run ote-test

**Comment by yunchu** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
11:08:30  
11:08:30            ##############################################
11:08:30            ########                              ########
11:08:30            ########  ./tests/run_code_checks.sh  ########
11:08:30            ########                              ########
11:08:30            ##############################################
11:08:30  
11:08:30  [INFO] Initializing environment for https://github.com/PyCQA/isort.
11:08:37  [INFO] Initializing environment for https://github.com/psf/black.
11:08:45  [INFO] Initializing environment for https://github.com/PyCQA/flake8.
11:08:50  [INFO] Initializing environment for https://github.com/pre-commit/mirrors-prettier.
11:08:57  [INFO] Initializing environment for https://github.com/pre-commit/mirrors-prettier:prettier@2.3.0.
11:09:02  [INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
11:09:08  [INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy:attrs==21.2.*,numpy==1.19.5,types-Deprecated,types-PyYAML,types-docutils,types-python-dateutil,types-requests,types_futures.
11:09:14  [INFO] Installing environment for https://github.com/PyCQA/isort.
11:09:14  [INFO] Once installed this environment will be reused.
11:09:14  [INFO] This may take a few minutes...
11:09:29  [INFO] Installing environment for https://github.com/psf/black.
11:09:29  [INFO] Once installed this environment will be reused.
11:09:29  [INFO] This may take a few minutes...
11:10:01  [INFO] Installing environment for https://github.com/PyCQA/flake8.
11:10:01  [INFO] Once installed this environment will be reused.
11:10:01  [INFO] This may take a few minutes...
11:10:11  [INFO] Installing environment for https://github.com/pre-commit/mirrors-prettier.
11:10:11  [INFO] Once installed this environment will be reused.
11:10:11  [INFO] This may take a few minutes...
11:10:37  [INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.
11:10:37  [INFO] Once installed this environment will be reused.
11:10:37  [INFO] This may take a few minutes...
11:10:55  [INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.
11:10:55  [INFO] Once installed this environment will be reused.
11:10:55  [INFO] This may take a few minutes...
11:11:07  isort (ote_sdk)..........................................................Passed
11:11:07  isort (ote_cli|external).................................................Passed
11:11:09  black (ote_sdk|ote_cli)..................................................Passed
11:11:09  black (rest).............................................................Passed
11:11:11  flake8...................................................................Failed
11:11:11  - hook id: flake8
11:11:11  - exit code: 1
11:11:11  
11:11:11  ote_sdk/ote_sdk/tests/configuration/elements/test_primitive_parameters.py:19:1: F401 'ote_sdk.configuration.elements.utils.attr_strict_int_validator' imported but unused
11:11:11  
11:11:12  prettier.................................................................Failed
11:11:12  - hook id: prettier
11:11:12  - exit code: 2
11:11:12  
11:11:12  [error] external/mmsegmentation/segmentation_tasks/apis/segmentation/configuration.yaml: SyntaxError: Map keys must be unique; "auto_hpo_state" is repeated (6:5)
11:11:12  [error]    4 | learning_parameters:
11:11:12  [error]    5 |   batch_size:
11:11:12  [error] >  6 |     affects_outcome_of: TRAINING
11:11:12  [error]      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] >  7 |     auto_hpo_state: not_possible
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] >  8 |     auto_hpo_value: null
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] >  9 |     default_value: 8
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 10 |     description:
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 11 |       The number of training samples seen in each iteration of training.
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 12 |       Increasing this value improves training time and may make the training more
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 13 |       stable. A larger batch size has higher memory requirements.
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 14 |     editable: true
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 15 |     header: Batch size
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 16 |     max_value: 64
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 17 |     min_value: 1
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 18 |     type: INTEGER
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 19 |     ui_rules:
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 20 |       action: DISABLE_EDITING
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 21 |       operator: AND
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 22 |       rules: []
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 23 |       type: UI_RULES
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 24 |     value: 8
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 25 |     visible_in_ui: true
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 26 |     warning:
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 27 |       Increasing this value may cause the system to use more memory than available,
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 28 |       potentially causing out of memory errors, please update with caution.
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 29 |     auto_hpo_state: POSSIBLE
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 30 |   description: Learning Parameters
11:11:12  [error]      | ^
11:11:12  [error]   31 |   header: Learning Parameters
11:11:12  [error]   32 |   learning_rate:
11:11:12  [error]   33 |     affects_outcome_of: TRAINING
11:11:12  
11:11:17  mypy (ote_sdk)...........................................................Passed
11:11:18  mypy (ote_cli)...........................................................Passed
11:11:18  mypy (external)..........................................................Passed
11:11:57  pylint...................................................................Passed
11:11:57  [Pipeline] }
11:11:57  ERROR: script returned exit code 1

**Comment by yunchu** [comment]
@Ilya-Krylov, can you let me know how to find such logs? i think there is some pre-processing to update existing 'configuration.yaml' which executed before running the prettier precommit hook so the 'auto_hpo_state' is updated with 'not_possible'.
@ljcornel, do you have any idea about it?

**Comment by Ilya-Krylov** [comment]
@yunchu click on red cross (CI STATUS)

> [](https://github.com/openvino-pushbot)@openvino-pushbot CI STATUS — Build finished. [Details](http://213.221.44.203/job/ote/job/precommit/job/trigger_ote_sdk/862/)

Then Console Output, then click on link that failed
```
11:12:00  Failed: ote_sdk_tests_runner http://213.221.44.203/job/ote/job/precommit/job/ote_sdk_tests_runner/818/
```

Then Console Output again

Then find it in the Console Output:
```
11:11:07  isort (ote_sdk)..........................................................Passed
11:11:07  isort (ote_cli|external).................................................Passed
11:11:09  black (ote_sdk|ote_cli)..................................................Passed
11:11:09  black (rest).............................................................Passed
11:11:11  flake8...................................................................Failed
11:11:11  - hook id: flake8
11:11:11  - exit code: 1
11:11:11  
11:11:11  ote_sdk/ote_sdk/tests/configuration/elements/test_primitive_parameters.py:19:1: F401 'ote_sdk.configuration.elements.utils.attr_strict_int_validator' imported but unused
11:11:11  
11:11:12  prettier.................................................................Failed
11:11:12  - hook id: prettier
11:11:12  - exit code: 2
11:11:12  
11:11:12  [error] external/mmsegmentation/segmentation_tasks/apis/segmentation/configuration.yaml: SyntaxError: Map keys must be unique; "auto_hpo_state" is repeated (6:5)
11:11:12  [error]    4 | learning_parameters:
11:11:12  [error]    5 |   batch_size:
11:11:12  [error] >  6 |     affects_outcome_of: TRAINING
11:11:12  [error]      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] >  7 |     auto_hpo_state: not_possible
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] >  8 |     auto_hpo_value: null
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] >  9 |     default_value: 8
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 10 |     description:
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 11 |       The number of training samples seen in each iteration of training.
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 12 |       Increasing this value improves training time and may make the training more
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 13 |       stable. A larger batch size has higher memory requirements.
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 14 |     editable: true
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 15 |     header: Batch size
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 16 |     max_value: 64
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 17 |     min_value: 1
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 18 |     type: INTEGER
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 19 |     ui_rules:
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 20 |       action: DISABLE_EDITING
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 21 |       operator: AND
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 22 |       rules: []
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 23 |       type: UI_RULES
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 24 |     value: 8
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 25 |     visible_in_ui: true
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 26 |     warning:
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 27 |       Increasing this value may cause the system to use more memory than available,
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 28 |       potentially causing out of memory errors, please update with caution.
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 29 |     auto_hpo_state: POSSIBLE
11:11:12  [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:11:12  [error] > 30 |   description: Learning Parameters
11:11:12  [error]      | ^
11:11:12  [error]   31 |   header: Learning Parameters
11:11:12  [error]   32 |   learning_rate:
11:11:12  [error]   33 |     affects_outcome_of: TRAINING
11:11:12  
11:11:17  mypy (ote_sdk)...........................................................Passed
11:11:18  mypy (ote_cli)...........................................................Passed
11:11:18  mypy (external)..........................................................Passed
11:11:57  pylint...................................................................Passed
11:11:57  [Pipeline] }
11:11:57  ERROR: script returned exit code 1
```

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Pull request merged**
