### PR TITLE
[SEGMENTATION] Updates OTESeg

### PR DESCRIPTION
**Pull request by evgeny-izutov**
Updates OTESeg:
* Adds support of OV based feature dumping

Build on BMM: 26898 ✔️ (except unrelated tests)
Train on BMM: finished ✔️
OTE-test: 1387 ✔️ (except the old nncf-graph test)

### CODE REVIEW

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
@MaximProshin please have a look at POT **time**
http://213.221.44.203/job/ote/job/precommit/job/ote_sdk_tests_runner/743/console

22:51:57  **4932.74s** call     test_ote_cli_tools_segmentation.py::TestToolsSegmentation::test_pot_optimize[Custom_Semantic_Segmentation_Lite-HRNet-x-mod3_OCR]
22:51:57  **1450.87s** call     test_ote_cli_tools_segmentation.py::TestToolsSegmentation::test_pot_optimize[Custom_Semantic_Segmentation_Lite-HRNet-18-mod2_OCR]
22:51:57  **1414.25s** call     test_ote_cli_tools_segmentation.py::TestToolsSegmentation::test_pot_optimize[Custom_Semantic_Segmentation_Lite-HRNet-18_OCR]

**Comment by MaximProshin** [comment]
@Ilya-Krylov , is it 2021.4? If so, there is a known problem with HRNet conversion time by MO.
cc @evgeniya-egupova

**Comment by Ilya-Krylov** [comment]
@MaximProshin openvino==2022.1.0.dev20220302

**Comment by MaximProshin** [comment]
Then it's probably due to https://jira.devtools.intel.com/browse/CVS-80808.
Are these tests passed, and only time is significant?

**Comment by Ilya-Krylov** [comment]
@MaximProshin passed, updating openvino again, let's see what it will show us https://github.com/openvinotoolkit/training_extensions/pull/977

**Pull request merged**
