### PR TITLE
Fix nncf model export bug

### PR DESCRIPTION
**Pull request by ashwinvaidya17**

### CODE REVIEW

**Comment by harimkang** [comment]
@eunwoosh This is a modification of the last code you edited (in https://github.com/openvinotoolkit/training_extensions/pull/1300), could you take a look?

**Comment by eunwoosh** [comment]
I changed this code like this to fix HPO bug in anomaly task which is occurred when saving initial weight of anomaly model before training.
please refer [https://github.com/openvinotoolkit/training_extensions/pull/1300](url)
So, could you fix the bug by the other method?

**Comment by goodsong81** [comment]
This will break HPO in Geti side.
BTW, could you retarget to releases/v0.3.1-geti1.0.0?
RC2 already has been merged.

**Comment by ashwinvaidya17** [comment]
Okay, I'll update the other method and retarget the branch

**Review by eunwoosh — APPROVED** [review]

**Comment by goodsong81** [comment]
LGTM, but could you run local CLI test to verify if this change works for anomaly?
(Screen also might be helpful)

**Comment by ashwinvaidya17** [comment]
Here are the results for the classification tests
image

**Review by samet-akcay — APPROVED** [review]
@ashwinvaidya17 thanks for the effort and quick find!

**Review by goodsong81 — APPROVED** [review]

**Comment by goodsong81** [comment]
Thank you for quick fix. Could you let us know the bug ticket, if any?

**Comment by samet-akcay** [comment]
> Thank you for quick fix. Could you let us know the bug ticket, if any?

@goodsong81, as far as I'm concerned, there is no ticket for this. It was relatively a new issue spotted yesterday. @chuneuny-emily can you confirm this?

**Review by chuneuny-emily — APPROVED** [review]

**Comment by chuneuny-emily** [comment]
> > Thank you for quick fix. Could you let us know the bug ticket, if any?
> 
> @goodsong81, as far as I'm concerned, there is no ticket for this. It was relatively a new issue spotted yesterday. @chuneuny-emily can you confirm this?

Yes. There is no bug ticket yet. It was found in OTE component validation results I was run yesterday. Thank you for quick fix. Please merge it.

**Comment by goodsong81** [comment]
Merged. This could be included RC3, which could be FRC I hope :)

**Pull request merged**
