### PR TITLE
[OTX] Copy model_api from OMZ repo for pip install

### PR DESCRIPTION
**Pull request by goodsong81**
- Temporary code copy to support standalone pypi pip install otx
- To be redirected to the original module once pypi pip install is supported from OMZ side
- (Also applied to ote_sdk & external directories for reference & completeness)

### CODE REVIEW

**Comment by goodsong81** [comment]
image
(CI is not working due to storage issue)
Verified with detection CLI tests including OV tasks. Should work for other tasks.

**Review by ashwinvaidya17 — APPROVED** [review]
Looks good to me but do you know the timeline of the omz team to get it on pypi? I am concerned about having the same code in both otx and ote_sdk. Syncing changes might be a bit tedious.

**Comment by goodsong81** [comment]
> Looks good to me but do you know the timeline of the omz team to get it on pypi? I am concerned about having the same code in both otx and ote_sdk. Syncing changes might be a bit tedious.

No one knows the timeline as the OMZ project was de-prioritized. So, it would take some time and OTE is referring a specific branch (SCv1.1) which has been infrequently updated.
I think we'll have not that much trouble.

**Comment by harimkang** [comment]
From what I've looked at, it doesn't seem to pass the pre-commit test. (Not sure because CI doesn't work.)
Could you please execute this command? `tox -re pre-commit`

**Comment by ashwinvaidya17** [comment]
From the logs it looks like the system on which the CI is running is out of memory

**Pull request closed without merging**
