### PR TITLE
Fix tiling unittest and random max select logic

### LINKED ISSUE #2245: Sporadic failure of tiling max annotation unit test
PR: https://github.com/openvinotoolkit/training_extensions/pull/2243
Run: https://github.com/openvinotoolkit/training_extensions/actions/runs/5268671825/jobs/9525692994?pr=2243

Failure in UT py 3.10 (also observed on other PRs):
FAILED tests/unit/algorithms/detection/tiling/test_tiling_detection.py::TestTilingDetection::test_max_annotation

Locally not reproduced (py 3.8 and 3.10)

### PR DESCRIPTION
**Pull request by eugene123tw**
### Summary
Fix this issue: https://github.com/openvinotoolkit/training_extensions/issues/2245

### Checklist

- [x] I have added unit tests to cover my changes.​
- [x] I have added integration tests to cover my changes.​
- [x] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [x] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [x] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Review by eunwoosh — COMMENTED** [review]
Thanks for your fix. Could you add unit test for this?

**Comment by jaegukhyun** [comment]
> Thanks for your fix. Could you add unit test for this?

I think tests/unit/algorithms/detection/tiling/test_tiling_detection.py. Isn't it @eugene123tw?

**Comment by eugene123tw** [comment]
> Thanks for your fix. Could you add unit test for this?

@eunwoosh I created this PR to fix the unit test. I guess we don't need a unit test to test if a unit test works. :stuck_out_tongue_closed_eyes:

**Review by jaegukhyun — APPROVED** [review]

**Comment by sungmanc** [comment]
https://github.com/openvinotoolkit/training_extensions/pull/2336/files#diff-e36e3cfe0ee30fae0b4bb949815ffcf0a4f8eb472cf88cdb6f74b02cd9d33f8fL423

**Review by sungmanc — APPROVED** [review]

**Pull request merged**
