### PR TITLE
Patch mmaction2 at installation

### PR DESCRIPTION
**Pull request by vinnamkim**
### Summary

- To resolve git cloning error issues in https://github.com/openvinotoolkit/training_extensions/actions/runs/7392433074/job/20111653791#step:5:1408

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Review by jaegukhyun — DISMISSED** [review]
LGTM, How about adding some explanations why do we need this kind of patch.
Docstring of patch_mmaction2 function or docstring of src/otx/cli/patches/mmaction2.patch file would be nice

**Comment by vinnamkim** [comment]
> LGTM, How about adding some explanations why do we need this kind of patch. Docstring of patch_mmaction2 function or docstring of src/otx/cli/patches/mmaction2.patch file would be nice

What's the main reason that we need to patch mmaction2? I don't know exactly.

**Comment by jaegukhyun** [comment]
> > LGTM, How about adding some explanations why do we need this kind of patch. Docstring of patch_mmaction2 function or docstring of src/otx/cli/patches/mmaction2.patch file would be nice
> 
> What's the main reason that we need to patch mmaction2? I don't know exactly.

__init__.py is missing in https://github.com/open-mmlab/mmaction2/tree/v1.2.0/mmaction/models/localizers/drn

**Comment by vinnamkim** [comment]
> > > LGTM, How about adding some explanations why do we need this kind of patch. Docstring of patch_mmaction2 function or docstring of src/otx/cli/patches/mmaction2.patch file would be nice
> > 
> > 
> > What's the main reason that we need to patch mmaction2? I don't know exactly.
> 
> **init**.py is missing in https://github.com/open-mmlab/mmaction2/tree/v1.2.0/mmaction/models/localizers/drn

Fixed in https://github.com/openvinotoolkit/training_extensions/pull/2756/commits/64e961dcf131ab32c886246ee0b9e42a184ba26e

**Review by jaegukhyun — APPROVED** [review]

**Review by sungmanc — APPROVED** [review]

**Review by harimkang — APPROVED** [review]

**Review by wonjuleee — APPROVED** [review]

**Pull request merged**
