### PR TITLE
[MPA] Modify template path of API test in CI

### PR DESCRIPTION
**Pull request by harimkang**
### This PR includes :
- Update template path in API tests
- API & pre-commit tests in MPA: http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=pr-model-preparation-algorithm-test-37&environment=iotg-dev-workstation-12

### CODE REVIEW

**Comment by harimkang** [comment]
run ote-test

**Comment by harimkang** [comment]
CI test (WIP): https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-model-preparation-algorithm-test/38/

**Review by goodsong81 — APPROVED** [review]
LGTM. No MPA test failures.

**Review by JihwanEom — APPROVED** [review]
LGTM.

**Pull request merged**
