### PR TITLE
Fix OTE SDK test

### PR DESCRIPTION
**Pull request by eugene123tw**
Fix ote SDK test

### CODE REVIEW

**Comment by eugene123tw** [comment]
run ote-test

**Comment by eugene123tw** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/646/

**Comment by harimkang** [comment]
> https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/646/

Hi, @eugene123tw  Thanks for the good PR!
There is one FAIL case in the unit-test related to ote_sdk, is this not included?

[ote_sdk/tests/entities/test_dataset_item.py::TestDatasetItemEntity::test_dataset_item_get_annotations](http://validationreports.sclab.intel.com:8006/reports/test_result/635ad6fc16ab2cf2ae27317d)

**Comment by eugene123tw** [comment]
> > https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/646/
> 
> Hi, @eugene123tw Thanks for the good PR! There is one FAIL case in the unit-test related to ote_sdk, is this not included?
> 
> [ote_sdk/tests/entities/test_dataset_item.py::TestDatasetItemEntity::test_dataset_item_get_annotations](http://validationreports.sclab.intel.com:8006/reports/test_result/635ad6fc16ab2cf2ae27317d)

@harimkang I didn't fix the dataset annotation test as this PR fixes only the SDK tests that were impacted by tiling PR. And to be honest, I'm not sure the intention of the failed testcase

**Review by harimkang — APPROVED** [review]
LGTM

**Review by goodsong81 — APPROVED** [review]

**Pull request merged**
