### PR TITLE
[OTX] copy fixes in classification from develop

### PR DESCRIPTION
**Pull request by sovrasov**
- Active score
- Indexing in the hierarchical part

### CODE REVIEW

**Review by goodsong81 — DISMISSED** [review]
Thank you for the fix!

**Review by jaegukhyun — COMMENTED** [review]
Your OTE PR contains a change in external/deep-object-reid/torchreid_tasks/utils.py. Don't this change need to patch here?

**Comment by sovrasov** [comment]
> Your OTE PR contains a change in external/deep-object-reid/torchreid_tasks/utils.py. Don't this change need to patch here?

As far as I know, Sungman has deleted the whole external directory from otx, so we don't need patching d-o-r and other similar folders anymore.

**Comment by sungmanc** [comment]
> > Your OTE PR contains a change in external/deep-object-reid/torchreid_tasks/utils.py. Don't this change need to patch here?
> 
> As far as I know, Sungman has deleted the whole external directory from otx, so we don't need patching d-o-r and other similar folders anymore.

Yes, now we don't use any external modules for OTX :)

**Comment by sovrasov** [comment]
pytest -s -v tests/integration/cli:
image

**Review by JihwanEom — APPROVED** [review]

**Review by jaegukhyun — APPROVED** [review]

**Pull request merged**
