### PR TITLE
[OTX] Refactor stage structure in classification

### PR DESCRIPTION
**Pull request by JihwanEom**
This PR includes refactoring stage in mpa/cls.

- Add trainer and inferrer to mpa/det/incremental
- Move task adapt part to base stage, so that incremental stage is only responsible for incremental learning
- Base trainer, inferrer inherits from base stage
- Semi-SL stage inherits from base stage
- Cleared lwf task_adapt dependencies.

### CODE REVIEW

**Comment by JihwanEom** [comment]
Passed all of the classification cli tests locally. CI is WIP.

image

**Comment by JihwanEom** [comment]
image
FAILED 25 TCs:
16 NNCF fq TCs (`test_nncf_validate_fq`, `test_pot_validate_fq`)
1 MultiLabel ote export score TC (`test_otx_eval_openvino`), will be fixed by #1525 
8 Self-SL for segmentation TCs, will be fixed by #1541 

Passed all of related TCs.

**Review by jaegukhyun — APPROVED** [review]
LGTM

**Review by eunwoosh — APPROVED** [review]
LGTM. Thanks for your effort.

**Review by supersoob — APPROVED** [review]

**Pull request merged**
