### PR TITLE
Fix FP16 issue in Instance Segmentation

### PR DESCRIPTION
**Pull request by eugene123tw**
* Fixed FP16 NNCF issue 
* Added more test for instance segmentation

### CODE REVIEW

**Comment by eugene123tw** [comment]
run ote_sdk tests

**Comment by eugene123tw** [comment]
run ote-test

**Review by goodsong81 — COMMENTED** [review]
Looks good to me. Let's see the test results.

**Review by vinnamkim — COMMENTED** [review]
Hi @eugene123tw, I guess that we need to revert those lines...

https://github.com/openvinotoolkit/training_extensions/blob/cf3e4cf8d14f536302112c69cb933e1686109871/external/mmdetection/detection_tasks/apis/detection/nncf_task.py#L221-L225

**Comment by eugene123tw** [comment]
> Hi @eugene123tw, I guess that we need to revert those lines...
> 
> https://github.com/openvinotoolkit/training_extensions/blob/cf3e4cf8d14f536302112c69cb933e1686109871/external/mmdetection/detection_tasks/apis/detection/nncf_task.py#L221-L225

Hi @vinnamkim 

`input_` and `scale` have different data types for this Op: 
https://github.com/openvinotoolkit/nncf/blob/develop/nncf/torch/quantization/quantize_functions.py#L183

We need to cast scale to FP16 with `scale = scale.to(dtype=input_.dtype)`

Do we have someone in MPA maintaining NNCF?

**Comment by vinnamkim** [comment]
> Hi @vinnamkim
> 
> `input_` and `scale` have different data types for this Op: https://github.com/openvinotoolkit/nncf/blob/develop/nncf/torch/quantization/quantize_functions.py#L183
> 
> We need to cast scale to FP16 with `scale = scale.to(dtype=input_.dtype)`
> 
> Do we have someone in MPA maintaining NNCF?

We have NNCF maintainers: https://github.com/orgs/openvinotoolkit/teams/nncf_pytorch-maintainers/members

However, do you mean that https://github.com/openvinotoolkit/nncf/blob/develop/nncf/torch/quantization/quantize_functions.py#L183 raises a different data type exception if we remove those lines?
https://github.com/openvinotoolkit/training_extensions/blob/cf3e4cf8d14f536302112c69cb933e1686109871/external/mmdetection/detection_tasks/apis/detection/nncf_task.py#L221-L225

**Comment by eugene123tw** [comment]
> > Hi @vinnamkim
> > `input_` and `scale` have different data types for this Op: https://github.com/openvinotoolkit/nncf/blob/develop/nncf/torch/quantization/quantize_functions.py#L183
> > We need to cast scale to FP16 with `scale = scale.to(dtype=input_.dtype)`
> > Do we have someone in MPA maintaining NNCF?
> 
> We have NNCF maintainers: https://github.com/orgs/openvinotoolkit/teams/nncf_pytorch-maintainers/members
> 
> However, do you mean that https://github.com/openvinotoolkit/nncf/blob/develop/nncf/torch/quantization/quantize_functions.py#L183 raises a different data type exception if we remove those lines?
> 
> https://github.com/openvinotoolkit/training_extensions/blob/cf3e4cf8d14f536302112c69cb933e1686109871/external/mmdetection/detection_tasks/apis/detection/nncf_task.py#L221-L225

yes, to be precise `input` is in FP16, and `scale` is in FP32.

**Review by vinnamkim — DISMISSED** [review]
LGTM

**Pull request merged**
