### PR TITLE
Enable nncf for Deit-tiny

### PR DESCRIPTION
**Pull request by sovrasov**
### Summary

It appears that NNCF is actually working for Deit

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Comment by jaegukhyun** [comment]
Is there no need to change intg test or e2e test??

**Comment by sovrasov** [comment]
> Is there no need to change intg test or e2e test??

These tests check if nncf entry point exists in template, and now it does

**Review by goodsong81 — COMMENTED** [review]
@sovrasov AFAIK, QAT is not must-have for Geti models anymore and our plan was to enable up to PTQ for DeiT. This looks like QAT setting. Was there any discussion for this enabling?
c.c. @wonjuleee

**Comment by sovrasov** [comment]
> @sovrasov AFAIK, QAT is not must-have for Geti models anymore and our plan was to enable up to PTQ for DeiT. This looks like QAT setting. Was there any discussion for this enabling? c.c. @wonjuleee

Does that mean we can drop QAT support in the future OTX releases? Instead, we can validate PTQ scenario more carefully and simplify code of OTX tasks.
Classification models look like an easy to quantize ones, so I discussed it with NCT team and performed a quick check.

**Comment by goodsong81** [comment]
> > @sovrasov AFAIK, QAT is not must-have for Geti models anymore and our plan was to enable up to PTQ for DeiT. This looks like QAT setting. Was there any discussion for this enabling? c.c. @wonjuleee
> 
> Does that mean we can drop QAT support in the future OTX releases? Instead, we can validate PTQ scenario more carefully and simplify code of OTX tasks. Classification models look like an easy to quantize ones, so I discussed it with NCT team and performed a quick check.

AFAIK, we'll keep them until the QAT-enabled models are deprecated from Geti recommended default models. Other models and newly added models would support PTQ only. So we can remove QAT tests for Geti-deprecated models one by one. Not now, though.

**Review by goodsong81 — CHANGES_REQUESTED** [review]
Mark requested not to merge this PR.

**Review by nikita-savelyevv — COMMENTED** [review]
Since this model is a transformer, I would recommend running PTQ with `model_type=ModelType.TRANSFORMER` parameter. This should improve the accuracy.

**Pull request closed without merging**
