### PR TITLE
Add Anomaly alias

### PR DESCRIPTION
**Pull request by ashwinvaidya17**
### Summary

- As requested in CVS-147611

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have ran e2e tests and there is no issues.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Comment by ashwinvaidya17** [comment]
When I run the same command `tox -vv -e pre-commit-all-py310-pt1`, it pases on my end
afbeelding

**Comment by harimkang** [comment]
> When I run the same command `tox -vv -e pre-commit-all-py310-pt1`, it pases on my end afbeelding

`tox -vv -e pre-commit-all-py310-pt1,` -> Does this command work? From what I've seen, we should run it with `tox -e pre-commit`. Your tox environment seems to be running an older version.

**Comment by harimkang** [comment]
> When I run the same command `tox -vv -e pre-commit-all-py310-pt1`, it pases on my end afbeelding

image
It looks like the automatically modified files were not added.

**Comment by ashwinvaidya17** [comment]
> > When I run the same command `tox -vv -e pre-commit-all-py310-pt1`, it pases on my end afbeelding
> 
> image It looks like the automatically modified files were not added.

I don't see any files to be added as it does not change anything on my end.

**Comment by A-Artemis** [comment]
Looks good!

**Comment by harimkang** [comment]
`tox -e pre-commit-all-py310-pt1`: This command reproduces exactly the same as CI: I pushed the change to the appropriate branch. https://github.com/openvinotoolkit/training_extensions/pull/3832/commits/ccba2e7ac98c0243754b33f83b161b13c8665c93 https://github.com/openvinotoolkit/training_extensions/pull/3832/commits/c261717f5a13b3b1d9a6069492abee1233e7367d

so now, let's see test

**Comment by ashwinvaidya17** [comment]
> `tox -e pre-commit-all-py310-pt1`: This command reproduces exactly the same as CI: I pushed the change to the appropriate branch. [ccba2e7](https://github.com/openvinotoolkit/training_extensions/commit/ccba2e7ac98c0243754b33f83b161b13c8665c93) [c261717](https://github.com/openvinotoolkit/training_extensions/commit/c261717f5a13b3b1d9a6069492abee1233e7367d)
> 
> so now, let's see test

Thanks for pushing the change. This is what I had tried based on the actions file.

```bash
conda create -n temp python=3.10 -y
conda activate temp
pip install --require-hashes --no-deps -r requirements/gh-actions.txt
pip-compile --generate-hashes -o /tmp/otx-dev-requirements.txt requirements/dev.txt
pip install --require-hashes --no-deps -r /tmp/otx-dev-requirements.txt
rm /tmp/otx-dev-requirements.txt
tox -vv -e pre-commit-all-py310-pt1
```

But even with this I got the same result.

**Comment by chuneuny-emily** [comment]
@ashwinvaidya17 - OTX1.6.4 was already released into Geti 2.3.0 and develop branches. What is the Geti target version for this PR ?

**Comment by ashwinvaidya17** [comment]
> @ashwinvaidya17 - OTX1.6.4 was already released into Geti 2.3.0 and develop branches. What is the Geti target version for this PR ?

I am assuming the next version then. Maybe @A-Artemis can say more about this.

**Comment by A-Artemis** [comment]
> @ashwinvaidya17 - OTX1.6.4 was already released into Geti 2.3.0 and develop branches. What is the Geti target version for this PR ?

The Geti target is 2.5.0.

**Comment by chuneuny-emily** [comment]
@A-Artemis @ashwinvaidya17 - It is difficult to merge the code changes targeting Geti 2.5 into the official OTX1.6.5 aimed at integrating Geti 2.3/2.4. For Geti 2.5, OTX2.x integration is scheduled. If an early drop is required due to preliminary work by other teams, it seems necessary to create a separate branch to check updated features. What do you think?

**Comment by chuneuny-emily** [comment]
@ashwinvaidya17 - Please target this PR to OTX develop branch.
@A-Artemis - Please create a your own branch from Geti develop, then I'll integrate the latest OTX develop into the branch for your work.

**Comment by ashwinvaidya17** [comment]
@chuneuny-emily This pr https://github.com/openvinotoolkit/training_extensions/pull/3818 targets develop branch

**Comment by samet-akcay** [comment]
As suggested by @chuneuny-emily, this is not needed and can be closed.

**Pull request closed without merging**
