### PR TITLE
Add nncf graph references for tests

### PR DESCRIPTION
**Pull request by vinnamkim**
- Custom_Counting_Instance_Segmentation_MaskRCNN_EfficientNetB2B
 - Custom_Counting_Instance_Segmentation_MaskRCNN_ResNet50

https://jira.devtools.intel.com/browse/CVS-84530
https://jira.devtools.intel.com/browse/CVS-84533

Signed-off-by: Kim, Vinnam <vinnam.kim@intel.com>

### CODE REVIEW

**Comment by vinnamkim** [comment]
Tests were passed
http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=pr-ote-test-291&environment=iotg-dev-workstation-08

**Review by goodsong81 — APPROVED** [review]
LGTM

**Review by sstrehlk — APPROVED** [review]

**Comment by vinnamkim** [comment]
run tests

**Comment by vinnamkim** [comment]
run ote-test

**Pull request merged**
