### PR TITLE
Fix regression tests

### PR DESCRIPTION
**Pull request by kprokofi**
### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Comment by kprokofi** [comment]
@chuneuny-emily , could you please check?

**Review by chuneuny-emily — DISMISSED** [review]

**Comment by chuneuny-emily** [comment]
> @chuneuny-emily , could you please check?

The regression test results for the litehrnet series failed. Is this an expected result?
image

**Comment by kprokofi** [comment]
> > @chuneuny-emily , could you please check?
> 
> The regression test results for the litehrnet series failed. Is this an expected result? image

I depends on what metric considered as "passed". I don't know those metrics

**Comment by jaegukhyun** [comment]
> > > @chuneuny-emily , could you please check?
> > 
> > 
> > The regression test results for the litehrnet series failed. Is this an expected result? image
> 
> I depends on what metric considered as "passed". I don't know those metrics

Currently regression tests do not check metrics, that is the failures mean that the models cannot be trained or tested.
@chuneuny-emily Could you share error logs during segmentation regression tests?

**Comment by chuneuny-emily** [comment]
> > > > @chuneuny-emily , could you please check?
> > > 
> > > 
> > > The regression test results for the litehrnet series failed. Is this an expected result? image
> > 
> > 
> > I depends on what metric considered as "passed". I don't know those metrics
> 
> Currently regression tests do not check metrics, that is the failures mean that the models cannot be trained or tested. @chuneuny-emily Could you share error logs during segmentation regression tests?

image RuntimeError: adaptive_avg_pool2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation, or you can use the 'warn_only=True' option, if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.

**Comment by jaegukhyun** [comment]
> > > > > @chuneuny-emily , could you please check?
> > > > 
> > > > 
> > > > The regression test results for the litehrnet series failed. Is this an expected result? image
> > > 
> > > 
> > > I depends on what metric considered as "passed". I don't know those metrics
> > 
> > 
> > Currently regression tests do not check metrics, that is the failures mean that the models cannot be trained or tested. @chuneuny-emily Could you share error logs during segmentation regression tests?
> 
> image RuntimeError: adaptive_avg_pool2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation, or you can use the 'warn_only=True' option, if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.

@kprokofi Could you check this issue? If you can run regression tests for semantic segmentation in your environment, then it is related with environment. However, I think it is just deterministic issue. You can simply turn off deterministic for semantic segmentation case or give warn_only=True flags if you want to keep same performance between each regression test trial

**Review by sungmanc — DISMISSED** [review]

**Comment by chuneuny-emily** [comment]
> > > > > > @chuneuny-emily , could you please check?
> > > > > 
> > > > > 
> > > > > The regression test results for the litehrnet series failed. Is this an expected result? image
> > > > 
> > > > 
> > > > I depends on what metric considered as "passed". I don't know those metrics
> > > 
> > > 
> > > Currently regression tests do not check metrics, that is the failures mean that the models cannot be trained or tested. @chuneuny-emily Could you share error logs during segmentation regression tests?
> > 
> > 
> > image RuntimeError: adaptive_avg_pool2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation, or you can use the 'warn_only=True' option, if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.
> 
> @kprokofi Could you check this issue? If you can run regression tests for semantic segmentation in your environment, then it is related with environment. However, I think it is just deterministic issue. You can simply turn off deterministic for semantic segmentation case or give warn_only=True flags if you want to keep same performance between each regression test trial

A RuntimeError of Deterministic: True occurs only on lithrnet series models as below. Other model templates work fine.
If I set Deterministic: False, lithrnet series models also work well.

@kprokofi - Please update the settings so that it works well with all templates.

15 Failed TCs:
FAILED tests/regression/test_regression.py::TestSemanticSegmentation::test_regression[gpu-kvasir_small_1-litehrnet_18]
FAILED tests/regression/test_regression.py::TestSemanticSegmentation::test_regression[gpu-kvasir_small_1-litehrnet_s]
FAILED tests/regression/test_regression.py::TestSemanticSegmentation::test_regression[gpu-kvasir_small_1-litehrnet_x]
FAILED tests/regression/test_regression.py::TestSemanticSegmentation::test_regression[gpu-kvasir_small_2-litehrnet_18]
FAILED tests/regression/test_regression.py::TestSemanticSegmentation::test_regression[gpu-kvasir_small_2-litehrnet_s]
FAILED tests/regression/test_regression.py::TestSemanticSegmentation::test_regression[gpu-kvasir_small_2-litehrnet_x]
FAILED tests/regression/test_regression.py::TestSemanticSegmentation::test_regression[gpu-kvasir_small_3-litehrnet_18]
FAILED tests/regression/test_regression.py::TestSemanticSegmentation::test_regression[gpu-kvasir_small_3-litehrnet_s]
FAILED tests/regression/test_regression.py::TestSemanticSegmentation::test_regression[gpu-kvasir_small_3-litehrnet_x]
FAILED tests/regression/test_regression.py::TestSemanticSegmentation::test_regression[gpu-kvasir_medium-litehrnet_18]
FAILED tests/regression/test_regression.py::TestSemanticSegmentation::test_regression[gpu-kvasir_medium-litehrnet_s]
FAILED tests/regression/test_regression.py::TestSemanticSegmentation::test_regression[gpu-kvasir_medium-litehrnet_x]
FAILED tests/regression/test_regression.py::TestSemanticSegmentation::test_regression[gpu-kvasir_large-litehrnet_18]
FAILED tests/regression/test_regression.py::TestSemanticSegmentation::test_regression[gpu-kvasir_large-litehrnet_s]
FAILED tests/regression/test_regression.py::TestSemanticSegmentation::test_regression[gpu-kvasir_large-litehrnet_x]

**Review by jaegukhyun — APPROVED** [review]

**Review by chuneuny-emily — APPROVED** [review]

**Review by sungmanc — APPROVED** [review]

**Pull request merged**
