### PR TITLE
[release/0.4.0][OTX] Enabling GPU execution for exported code

### PR DESCRIPTION
**Pull request by GalyaZalesskaya**
Apply changes in [develop PR](https://github.com/openvinotoolkit/training_extensions/pull/1403) to release branch as well

### CODE REVIEW

**Comment by GalyaZalesskaya** [comment]
run ote-test

**Review by goodsong81 — APPROVED** [review]
LGTM

**Review by sovrasov — APPROVED** [review]
LGTM, but let's wait for the build finishes prior to merging.

**Comment by sovrasov** [comment]
run ote-test

**Comment by harimkang** [comment]
This PR requires modification of deploy-related test code. please add

**Pull request merged**
