### PR TITLE
Update evaluation iou_thr values

### PR DESCRIPTION
**Pull request by harimkang**
## Summary
Validation time is too long due to the issue of selecting too many iou_thr values ​​as a table during validation on a relatively large size dataset. Fix this to iou_thr = [0.5]
only instance-segmentation & rotated-detection

### This PR includes :
- Update iou_thr = [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9] -> [0.5]

### CODE REVIEW

**Comment by harimkang** [comment]
run ote-test

**Review by goodsong81 — APPROVED** [review]
LGTM. @eugene123tw Could you confirm?

**Comment by sungmanc** [comment]
Is this successfully reflected to mmdetection's COCO evaluation? AFIAK, there is mis-matching for argument `iou_thr` between mmdetection backend and OTE. I'll look into it.

**Comment by harimkang** [comment]
> Is this successfully reflected to mmdetection's COCO evaluation? AFIAK, there is mis-matching for argument `iou_thr` between mmdetection backend and OTE. I'll look into it.

Yes, it would be nice if you could see it :). When I simply checked it with this PR, only 'iou_thr = 0.5' print out well.

**Comment by sungmanc** [comment]
> > Is this successfully reflected to mmdetection's COCO evaluation? AFIAK, there is mis-matching for argument `iou_thr` between mmdetection backend and OTE. I'll look into it.
> 
> Yes, it would be nice if you could see it :). When I simply checked it with this PR, only 'iou_thr = 0.5' print out well.

Ah, then LGTM for myside

**Comment by harimkang** [comment]
> > > Is this successfully reflected to mmdetection's COCO evaluation? AFIAK, there is mis-matching for argument `iou_thr` between mmdetection backend and OTE. I'll look into it.
> > 
> > 
> > Yes, it would be nice if you could see it :). When I simply checked it with this PR, only 'iou_thr = 0.5' print out well.
> 
> Ah, then LGTM for myside

could you please approve?

**Review by sungmanc — APPROVED** [review]
LGTM

**Pull request merged**
