### PR TITLE
Add a tool to help conduct experiments

### PR DESCRIPTION
**Pull request by eunwoosh**
### Summary
Add a helper tool for conducting experiments (A.K.A research framework).
Unlike original implementation which implemented it as CLI, I implemented it as tools outside OTX package.
To use this feature, you need to execute this file instead of `otx experiment`.
This implementation is almost same as `otx experiment` but there are a few differences as below.

- There is no `otx run` but you still can run list of otx commands by writing a list at `command` as sample yaml below
- This file includes both `otx experiment` and `otx run` features. It means that when `otx eval` is executed, proper model file is automatically used depending on which command was executed just before.
- You can parse single workspace using `--parse` argument. If values exist, they're parsed and saved as a file.

This is sample yaml file for this file.
image

### How to test
For running experiments:
`python tools/experiment.py -f exp_recipe.yaml`

For parsing workspace:
`python tools/experiment.py -p workspace_path`

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [x] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Review by sungmanc — APPROVED** [review]
LGTM

**Review by goodsong81 — APPROVED** [review]
Thank you for the great tool. What a pity that this is not included the PyPI package yet. Let's try to promote sooner or later after OTX2.0. :)

**Comment by sungmanc** [comment]
Ah, could you please add a document or guideline to use this easily?

**Comment by eunwoosh** [comment]
> Ah, could you please add a document or guideline to use this easily?

Sure. But I'm not sure it's ok to write it at our official documentation. I'll make a PR for docs after discussion about that.

**Pull request merged**
