### PR TITLE
[OTX][TEST] Align TC for Integration Test & Move CLI tests to E2E

### PR DESCRIPTION
**Pull request by harimkang**
## Summary
Redefine Integration Test and copy existing CLI tests to E2E.

## Changes
- Copy existing tests/integration/cli -> tests/e2e/cli
- Segmentation model  -> Use only one model for testing, Because all 5 models have the same architecture
- Tiling -> ATSS, Resnet50-MaskRCNN only test
- Update to 1 iteration & score threshold = 1.0
- Semi, Self, etc -> Train only
- Multi-label cls & H-label cls -> Use only default model (Effnet-B0)
- Remove or modify TC like Result's table (Deleted TC will be covered in E2E test)

## Results
TC decision: OTX group members
> All model: Performed on all models corresponding to each task
> Default model: Only performed on representative models of each task

|TC|Target|
|------|---|
|test_otx_train|All model|
|test_otx_resume|Default model|
|test_otx_export|All model|
|test_otx_eval|All model|
|test_otx_eval_openvino|Default model|
|test_otx_eval_demo|X|
|test_otx_eval_demo_openvino|X|
|test_otx_eval_deploy_openvino|Default model|
|test_otx_eval_eval_deployment|Default model|
|test_otx_demo_deployment|X|
|test_otx_hpo|Default model|
|test_otx_nncf_optimize|All model|
|test_otx_nncf_export|X|
|test_otx_nncf_eval|X|
|test_otx_nncf_eval_openvino|X|
|test_otx_pot_optimize|X|
|test_otx_pot_eval|X|
|test_otx_multi_gpu_train|Default model|
|test_otx_train_semisl|Default model|
|test_otx_train_selfsl|Default model|
|test_otx_train_supcon|Default model|

In Local Env (single 3090 GPU)
image

### CODE REVIEW

**Review by jaegukhyun — APPROVED** [review]
LGTM. Do you have plan for reducing cli test dataset volume?

**Comment by jaegukhyun** [comment]
@samet-akcay @eugene123tw OTX developer TF have discussed about reducing integration test time. Considering current situation(release of OTX1.0 due date), we agreed on moving current cli test to e2e test and bring some key cli test for integration test. So we can concentrate on adding unit test. We divided each cli test to 3 groups[Test for all model, Test for default model, Do not test for intg]. Could you look at this PR for Anomaly tasks and Tiling tasks? If you have any opinion for this decision please let us know

**Review by goodsong81 — APPROVED** [review]
Good enough to me.
Original tests will be run as nightly build so that we don't lose any test coverage at least in daily basis.
Let's deal w/ test "optimization" in future PRs.

**Review by eunwoosh — APPROVED** [review]
LGTM. Thanks for your effort.

**Comment by harimkang** [comment]
> LGTM. Do you have plan for reducing cli test dataset volume?

As far as I know, while integrating datumaro, the test dataset size has decreased considerably. @sungmanc Do you think we need to reduce more?

**Review by sungmanc — APPROVED** [review]
Thanks for nice work.

**Comment by sungmanc** [comment]
> > LGTM. Do you have plan for reducing cli test dataset volume?
> 
> As far as I know, while integrating datumaro, the test dataset size has decreased considerably. @sungmanc Do you think we need to reduce more?

Right, the amount of datasets is quite reduced now. So, don't need to focus with volume of dataset

**Pull request merged**
