### PR TITLE
Remove randomness in DINO unit tests

### PR DESCRIPTION
**Pull request by jaegukhyun**
### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Comment by jaegukhyun** [comment]
I tested 3 times using our CI, and their results are same.

**Comment by sungmanc** [comment]
How about applying this manual seed logic to all other tests? to remove further uncertainty

**Comment by jaegukhyun** [comment]
I'm doubting to control overall test randomness in one file. I believe test should control its own randomness.

**Comment by sungmanc** [comment]
> I'm doubting to control overall test randomness in one file. I believe test should control its own randomness.

Hmm,, I don't mind the current way. it seems to be a little bit tricky.
If the user inputs another seed, then could the `len(losses)` be different? If so, then we need to consider randomness in our test case. I'm not sure that adding deterministic for the test to resolve the test error is the right direction. 

If the changed value of `len(losses)` is okay, then changing the `assert` line would be a great option.

**Review by sungmanc — APPROVED** [review]
Although I left a concern, I think that this is not important factor. So, want to review as approve.

**Comment by jaegukhyun** [comment]
I understand your concern. Errors occur when some tensors have nan value during forward function. It is highly related initialized weights for bbox_head, so I set random seed to control it. The best way to solve this issue is mock inner forward function. However, the calculation which give NaN value changes randomly, therefore I had to set random seed to control those randomness.

**Review by sovrasov — APPROVED** [review]
I propose merging this to unblock other PRs, and make an issue for further discussion if required.

**Pull request merged**
