### PR TITLE
Upgrade nncf version for 1.4 release

### PR DESCRIPTION
**Pull request by sovrasov**
### Summary
Apparently, we'll settle down with github installation of NNCF

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Comment by sovrasov** [comment]
E2E passed: https://github.com/openvinotoolkit/training_extensions/actions/runs/6048911917

**Review by jaegukhyun — DISMISSED** [review]

**Review by sungmanc — DISMISSED** [review]

**Comment by sovrasov** [comment]
@yunchu can we merge this, or regression results are still WIP?

**Comment by yunchu** [comment]
> @yunchu can we merge this, or regression results are still WIP?

@sovrasov I'm sorry for the late response. the testing is running now and will be completed within today. but the tests were triggered on the develop branch base so I think this PR could be merged to the releases/1.4.0 and then we can update nncf version when it published through the pypi.

**Comment by sovrasov** [comment]
> > @yunchu can we merge this, or regression results are still WIP?
> 
> @sovrasov I'm sorry for the late response. the testing is running now and will be completed within today. but the tests were triggered on the develop branch base so I think this PR could be merged to the releases/1.4.0 and then we can update nncf version when it published through the pypi.

This nncf version won't be pushed to pypi till the release of OpenVINO. Please, sync with Mark, if we need to merge this before the end of September.

**Review by goodsong81 — COMMENTED** [review]
Is it OK for us to install NNCF from commit?
It means that we should install OTX on Geti also by commit for a while.

**Comment by sovrasov** [comment]
> Is it OK for us to install NNCF from commit? It means that we should install OTX on Geti also by commit for a while.

From the technical perspective, that works. Go / not go depends on Mark's decision and schedule. On the last related sync we agreed to use commit, but maybe something has changed

**Review by goodsong81 — APPROVED** [review]

**Review by goodsong81 — CHANGES_REQUESTED** [review]
Let's wait for the official 2.6.0 package as @yunchu suggested.

**Comment by sovrasov** [comment]
> Let's wait for the official 2.6.0 package as @yunchu suggested.

The package was released, and requirements are updated correspondingly.

**Review by goodsong81 — APPROVED** [review]

**Review by eunwoosh — APPROVED** [review]

**Pull request merged**
