### PR TITLE
Modify e2e tests properly

### PR DESCRIPTION
**Pull request by jaegukhyun**
### Summary
This PR is for patching E2E tests
This PR covers 

1. Remove JIRA tickets for skip reason and add more suitable reason
2. Skip nncf tests in tiling detection and tiling ins-segmentation
3. Add fq reference for segmentation POT

### How to test
tox -e pre-merge-all-py310 -- tests/e2e/cli/

**tiling instance segmentation**
image

**tiling_detection**
image

**detection**
image

**segmentation**
image

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Review by eunwoosh — DISMISSED** [review]

**Comment by sungmanc** [comment]
Could you also attach the `tox -e pre-merge-all-py310 -- tests/e2e/cli/` results? There are only tiling cases

**Comment by jaegukhyun** [comment]
> Could you also attach the `tox -e pre-merge-all-py310 -- tests/e2e/cli/` results? There are only tiling cases

Recent daily shows errors for only tiling detection, tiling instance segmentation, and semantic segmentation. Semantic segmentation results will be added.

**Review by sungmanc — CHANGES_REQUESTED** [review]
We should change this value to 0.05. And need to make proper issue if this TC still cause FAILs

https://github.com/jaegukhyun/training_extensions/blob/39aebc594c8a6071b551ac8edc443c648888c0d3/tests/e2e/cli/detection/test_detection.py#L155

It was included in this PR https://github.com/openvinotoolkit/training_extensions/pull/2032/files

**Comment by jaegukhyun** [comment]
> We should change this value to 0.05. And need to make proper issue if this TC still cause FAILs
> 
> https://github.com/jaegukhyun/training_extensions/blob/39aebc594c8a6071b551ac8edc443c648888c0d3/tests/e2e/cli/detection/test_detection.py#L155
> 
> It was included in this PR https://github.com/openvinotoolkit/training_extensions/pull/2032/files

After reverting to 0.05, there is no defected issue. Let's keep watching for a while

**Review by sungmanc — APPROVED** [review]
Thanks for the hard work :)

**Review by eunwoosh — APPROVED** [review]

**Pull request merged**
