### PR TITLE
[DEV] Fix deprecated np.bool issue from numpy==1.24.0

### PR DESCRIPTION
**Pull request by goodsong81**
- Restrict numpy<=1.23.5 which allows np.bool (OpenVINO runtime is using it)
- Enhance CLI test run for better error message
  - Now we can see stack trace from CLI test failure.
image

### CODE REVIEW

**Comment by goodsong81** [comment]
run ote-test

**Comment by goodsong81** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/851/

**Comment by goodsong81** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/852/

**Comment by goodsong81** [comment]
run ote-test

**Comment by goodsong81** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/853/

**Comment by goodsong81** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/854/

**Comment by goodsong81** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/858/

**Comment by goodsong81** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/859/
The only failure was precommit test, which was resolved now.
image

**Review by sungmanc — DISMISSED** [review]
LGTM. we need to answer #1456

**Review by harimkang — DISMISSED** [review]

**Comment by goodsong81** [comment]
> LGTM. we need to answer #1456

Will do. I'm testing. Might need minor change.

**Review by harimkang — APPROVED** [review]
LGTM

**Review by sungmanc — APPROVED** [review]

**Pull request merged**
