### PR TITLE
anomaly save_model bugfix

### PR DESCRIPTION
**Pull request by eunwoosh**
# Summary
This PR solves bug that error raises when run HPO on anomaly tasks.

### CODE REVIEW

**Review by goodsong81 — COMMENTED** [review]
Could this change resolve the Geti issue? This is just function renaming + OTE CLI side change.

**Comment by samet-akcay** [comment]
> Could this change resolve the Geti issue? This is just function renaming + OTE CLI side change.

Same comment here. If the change in cli fixes the issue, I'm fine with it

**Comment by yunchu** [comment]
@goodsong81 I think @eunwoosh want to make task.model_info() method to public for using in the Geti's initial model saving routine (refer this Geti PR https://github.com/intel-innersource/frameworks.ai.interactive-ai-workflow.sonoma-creek/pull/3987/files#). but i'm not sure only such changes are enough to resolve the Geti's issue (https://jira.devtools.intel.com/browse/CVS-94317)

**Comment by yunchu** [comment]
@goodsong81 , @samet-akcay 
i've added a commit to fix this issue on top of EW's one and using that i've got successful result from the Geti build.
http://validationreports.sclab.intel.com:8004/reports/build_number_report?test_session_build_number=IMPTOps-43643&environment=mclx81
please review again.

**Review by goodsong81 — APPROVED** [review]
Thank you for the fix.

**Comment by goodsong81** [comment]
@eunwoosh Don't forget to apply this change to OTE develop and Geti develop when you come back. :)

**Review by harimkang — APPROVED** [review]

**Pull request merged**
