### PR TITLE
[Release branch] Disable NNCF optimization for FP16 models 

### PR DESCRIPTION
**Pull request by daniil-lyakhov**
FP16 model optimization by NNCF will be supported only in OTX2.0. Until then NNCF optimization for that models should be disabled.

### CODE REVIEW

**Comment by daniil-lyakhov** [comment]
Changes are checked on my local SC instance

**Review by alexsu52 — APPROVED** [review]

**Comment by goodsong81** [comment]
run ote-test

**Comment by goodsong81** [comment]
run ote-test

**Comment by goodsong81** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/669/

**Comment by goodsong81** [comment]
I've merged this PR as RC2 candidate. Could be reverted if we find some side effects.

**Pull request merged**
