### PR TITLE
⚠️ [PreCommit Fix] Address pre-commit issues that causes CI to fail

### PR DESCRIPTION
**Pull request by samet-akcay**
This is a huuuge formatting PR. Sorry reviewers, but we had to do this :/

`develop` branch currently fails due to `pre-commit run --all-files`. This PR addresses the files affecting the pre-commit fail.

- Re-configure `.pre-commit-config.yaml`.
- Add version number to hooks to avoid discrepancies. 
- Re-configure `prettier` in `pre-commit to format any files, not just yaml. (Markdown files are formatted now.)
- Remove mypy config argument. `mypy.ini` file is moved to the root.
- Address pylint issues
- Format the code throughout by `black`. (Not sure how the CI didn't fail before.)

CI - [Link](https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/486/) ⏳

### CODE REVIEW

**Comment by samet-akcay** [comment]
@openvinotoolkit/ote-maintainers, can we prioritise this PR please? It's easy to get merge conflicts due to its size.

**Comment by samet-akcay** [comment]
run ote-test

**Review by goodsong81 — DISMISSED** [review]
LGTM. Most of changes are re-formatting.
Let's merge this PR after checking the test result.

**Comment by samet-akcay** [comment]
run ote-test

**Review by goodsong81 — APPROVED** [review]
LGTM!

**Review by harimkang — APPROVED** [review]
LGTM

**Pull request merged**
