### PR TITLE
[OTE_SDK] Add label resolver to label schema

### PR DESCRIPTION
**Pull request by sovrasov**

### CODE REVIEW

**Comment by sovrasov** [comment]
run ote_sdk tests

**Comment by nervana-ff** [comment]
Can one of the admins verify this patch?

**Comment by sovrasov** [comment]
```
FAILED tests/ote_cli/test_ote_cli_tools_rotated_detection.py::TestToolsRotatedDetection::test_ote_eval_openvino[Custom_Rotated_Detection_via_Instance_Segmentation_MaskRCNN_ResNet50]
```

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
Can you add some test for this functionality?

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by sovrasov** [comment]
run ote_sdk tests

**Comment by sovrasov** [comment]
run ote_sdk tests

**Comment by sovrasov** [comment]
run ote_sdk tests

**Comment by sovrasov** [comment]
ВMM 25565 - passed

**Comment by sovrasov** [comment]
TestToolsRotatedDetection::* and TestToolsSegmentation::* were failed

**Comment by sovrasov** [comment]
ote-test/1047/ - failed

**Comment by sovrasov** [comment]
ote-test/1065/ - passed

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Pull request merged**
