### PR TITLE
Fix h-label: per-group softmax

### PR DESCRIPTION
**Pull request by goodsong81**
- Trying to resolve: https://jira.devtools.intel.com/browse/CVS-95551
- Dependent to: https://github.com/openvinotoolkit/model_preparation_algorithm/pull/74

### CODE REVIEW

**Comment by goodsong81** [comment]
run ote-test

**Comment by goodsong81** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/679/

**Review by JihwanEom — DISMISSED** [review]
LGTM

**Comment by goodsong81** [comment]
run ote-test

**Comment by goodsong81** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/680/

**Comment by goodsong81** [comment]
Verified via local OTE CLI test.
image

**Pull request merged**
