### PR TITLE
Improve Vitens Kiemgetal OTX 1.6.x

### PR DESCRIPTION
**Pull request by eugene123tw**
### Summary

* Remove the maximum number of detections from the tile adaptor and make it manually configurable. 
  * e.g. `otx train --workspace=... params --tiling_parameters.enable_tiling=true --tiling_parameters.tile_max_number=200`
* Remove random affine and color augmentation for YOLOX and ATSS tile recipes.

### Checklist

- [x] I have added unit tests to cover my changes.​
- [x] I have added integration tests to cover my changes.​
- [x] I have ran e2e tests and there is no issues.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Review by chuneuny-emily — DISMISSED** [review]

**Review by sovrasov — DISMISSED** [review]

**Comment by sovrasov** [comment]
@eugene123tw CI is not working for this branch, since all workers were moved to AWS.
Could you run linters, unit & tiling detection integration tests manually?

**Comment by eugene123tw** [comment]
image

**Comment by eugene123tw** [comment]
image

**Comment by eugene123tw** [comment]
`tests/integration/cli/instance_segmentation/test_tiling_instseg.py`

image

`pytest tests/integration/cli/detection/test_tiling_detection.py`

image

**Review by chuneuny-emily — APPROVED** [review]

**Review by eunwoosh — APPROVED** [review]

**Pull request merged**
