### PR TITLE
Update mmsegmentation

### PR DESCRIPTION
**Pull request by LeonidBeynenson**
Build on BMM: 20827 ✔️
Train on BMM: finished ✔️

### CODE REVIEW

**Comment by LeonidBeynenson** [comment]
This PR was created at the request of Eugene Izutov to update the mmsegmentation submodule.

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Review by evgeny-izutov — APPROVED** [review]

**Comment by Ilya-Krylov** [comment]
BMM ?

**Comment by evgeny-izutov** [comment]
BMM 20798 running

**Comment by evgeny-izutov** [comment]
Previous BMM failed during platform installation. New build BMM: 20827

**Comment by evgeny-izutov** [comment]
Build on BMM: 20827 ✔️
Train on BMM: finished ✔️

**Pull request merged**
