### PR TITLE
[Anomaly Task] Expose more params to the UI

### PR DESCRIPTION
**Pull request by ashwinvaidya17**
# Changes
- Add more parameters to configuration file.
- It does not include `layers`

# 🧪
http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=ote-test-1744&environment=iotg-dev-workstation-12 - 8 Failed. A few are segmentation and others are in ote_sdk. Not sure if they are related.

### CODE REVIEW

**Review by djdameln — APPROVED** [review]
Thanks. Removing the code duplication is a huge improvement.

**Review by samet-akcay — APPROVED** [review]
Thanks for the effort!

**Comment by ashwinvaidya17** [comment]
@openvinotoolkit/ote-maintainers There is an issue with the CI. The tests die as soon as I start the pipeline https://ci-ote.iotg.sclab.intel.com/job/ote/job/ote-test/1761/console

**Comment by sstrehlk** [comment]
@ashwinvaidya17 it seems that problem with CI was caused by my mistake in configuration. It's fixed already.

**Comment by ashwinvaidya17** [comment]
> @ashwinvaidya17 it seems that problem with CI was caused by my mistake in configuration. It's fixed already.

Okay thanks. I see you have triggered a new test.

**Comment by ashwinvaidya17** [comment]
@sstrehlk The tests are still failing https://ci-ote.iotg.sclab.intel.com/job/ote/job/ote-test/1783/. These don't seem to be related to anomaly tasks.

**Pull request merged**
