### PR TITLE
[OTX][Unit-test] Unit tests for otx/mpa/seg

### PR DESCRIPTION
**Pull request by supersoob**
This PR includes

- Unit tests for mpa/seg
- Minor bug-fix in trainer/inferrer
- Remove unused evaluator.py and create properly working data config

[Coverage report]
image
**unit tests for incremental and semisl will be included in other PR.

### CODE REVIEW

**Review by harimkang — DISMISSED** [review]
LGTM!
As I said in other PRs, it would be nice to run a CI test with the latest commit and check it.

**Comment by supersoob** [comment]
Rebased and add incr/semisl stage files because they are few. Also revised the typo in filename. The coverage of this mpa/seg dir is above 80%
image

**Comment by jaegukhyun** [comment]
image
Could you check this test failure(test_run_with_hpopt)

**Comment by supersoob** [comment]
Failed with one issue which was existing one. Could you review again?
image

**Review by goodsong81 — APPROVED** [review]
LGTM!

**Review by JihwanEom — APPROVED** [review]

**Pull request merged**
