### PR TITLE
Remove background label from RT Info for segmentation task

### PR DESCRIPTION
**Pull request by kprokofi**
### Summary
CVS-154607

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have ran e2e tests and there is no issues.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Review by sungchul1 — DISMISSED** [review]
LGTM, I have a minor question.
Is background in dataset from geti always in the first index?

**Review by sovrasov — CHANGES_REQUESTED** [review]
Please refactor to avoid further damaging core entities. Similar PR: https://github.com/openvinotoolkit/training_extensions/pull/4013

**Comment by kprokofi** [comment]
> LGTM, I have a minor question. Is background in dataset from geti always in the first index?

Yes, we manually insert the background index as 0 label in label_names

**Comment by kprokofi** [comment]
1) Since we don't want to erase real background class from datasets like VOC, I renamed it to "otx_background_lbl"
2) Unfortunately, to have a possibility to test IR Model after Geti training, we need to reassign label_info from dataset. I deleted the code that restricts to do that since there is no point in setter which blocks the setting a new label info.

**Comment by kprokofi** [comment]
> Please refactor to avoid further damaging core entities. Similar PR: #4013

Done

**Review by sungchul1 — APPROVED** [review]

**Review by chuneuny-emily — APPROVED** [review]

**Review by sovrasov — APPROVED** [review]

**Pull request merged**
