### PR TITLE
Fix broken links in documentation

### PR DESCRIPTION
**Pull request by yunchu**
### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Review by goodsong81 — CHANGES_REQUESTED** [review]
Why don't we use 1.4.0 instead of "stable"?
If we update "stable" doc in 1.5.0 release, on PyPI otx==1.4.0 page it will show wrong (too latest) information.

**Comment by yunchu** [comment]
> Why don't we use 1.4.0 instead of "stable"? If we update "stable" doc in 1.5.0 release, on PyPI otx==1.4.0 page it will show wrong (too latest) information.

if so, it should be releases/1.4.1 since 1.4.0 is already published, right?

**Comment by goodsong81** [comment]
> > Why don't we use 1.4.0 instead of "stable"? If we update "stable" doc in 1.5.0 release, on PyPI otx==1.4.0 page it will show wrong (too latest) information.
> 
> if so, it should be releases/1.4.1 since 1.4.0 is already published, right?

If your intention is for 1.4.1 release, stable looks fine.
We'll use releases/1.4.0 for 1.4.1 so that releases/1.4.1 would not work if I correctly understand.

**Review by goodsong81 — DISMISSED** [review]

**Comment by yunchu** [comment]
> > > Why don't we use 1.4.0 instead of "stable"? If we update "stable" doc in 1.5.0 release, on PyPI otx==1.4.0 page it will show wrong (too latest) information.
> > 
> > 
> > if so, it should be releases/1.4.1 since 1.4.0 is already published, right?
> 
> If your intention is for 1.4.1 release, stable looks fine. We'll use releases/1.4.0 for 1.4.1 so that releases/1.4.1 would not work if I correctly understand.

I've checked gh-pages and realized that once created a release, the name of "tag" will be used to create a subfolder for holding documentations for that release. so, I need to update "build docs" workflow as well as some docs links.

**Review by eunwoosh — APPROVED** [review]

**Review by jaegukhyun — APPROVED** [review]

**Pull request merged**
