### PR TITLE
Async inference in OV tasks

### PR DESCRIPTION
**Pull request by sovrasov**
### Summary

OpenVINO Inference in classification, detection/instance segmentation, semantic segmentation tasks is async by default.
This can be disabled via InferenceParameters.
Some performance results:
Model | Ref acc | time sync | time async default | Speedup | time async tp mode
-- | -- | -- | -- | -- | -- 
mobilenetv2_atss | 0.7781 | 1.77 | 1.11 | 1.59 | 0.77
mobilenet_v3_large_1_cls_incr | 0.9335 | 25.37 | 16.42 | 1.55 | 12.19
ocr_lite_hrnet_18 | 0.826 | 7.02 | 4.33 | 1.62 | 4.47
resnet50_maskrcnn | 0.5169 | 239.57 | 233.17 | 1.03 | 150.71
efficientnetb2b_maskrcnn | 0.35406 | 64.47 | 73.4 | 0.88 | 40.5

Env: OV 2023 RC1, CPU Intel(R) Core(TM) i9-12900K

Due to contradictive results of instance segmentation models, the number of infer requests for these models was set to 2.
If tiling is enabled, async inference in detection task is disabled.

### Checklist

- [x] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [x] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [x] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Review by eunwoosh — DISMISSED** [review]

**Review by supersoob — DISMISSED** [review]

**Review by sungmanc — DISMISSED** [review]

**Comment by sungmanc** [comment]
Thanks for the new feature !

BTW, just question about the async feature. I'm not sure about the OV inference task.

In my benchmark experiments, I got the results below by using MaskR-CNN.
image

When I checked this PR, we only handled the `async_num_reqs(maybe related to the number of threads?)` by using `num_cpu_core/2`. Could we also handle the `n_streams`? Does `n_streams` only works for benchmark_app ?

**Comment by sovrasov** [comment]
> Thanks for the new feature !
> 
> BTW, just question about the async feature. I'm not sure about the OV inference task.
> 
> In my benchmark experiments, I got the results below by using MaskR-CNN. image
> 
> When I checked this PR, we only handled the `async_num_reqs(maybe related to the number of threads?)` by using `num_cpu_core/2`. Could we also handle the `n_streams`? Does `n_streams` only works for benchmark_app ?

Benchmark app is a C++ application that doesn't consider pre and post processing. It reveals the maximum possible perf improvement. BTW in your comparison suboptimal setting were set for sync mode, normally the difference is about 2x. 
We have python code with postprocessing callback, which can't be run in parallel due to limitations of python.
OV documentation suggests not touching n_streams, because it is set automatically. I found that `plugin_config={'PERFORMANCE_HINT': 'THROUGHPUT'}` could improve the throughput for all models, but  obviously it leads to worse performance for sync mode. 

We may switch to `THROUGHPUT` mode by default, scarifying ~20% performance of sync mode (assuming it could be used only for debug purposes). Instead we'd get async speedup for all algos (including M-RCNN)
@goodsong81 @sungmanc what do you say?

**Comment by goodsong81** [comment]
@sovrasov I would say "cool" :)

**Comment by sovrasov** [comment]
> @sovrasov I would say "cool" :)

I added results in throughput mode to the last column of the table in PR description.

**Comment by sungmanc** [comment]
Thank you for the kind explanation, let's check the results together

**Review by eugene123tw — DISMISSED** [review]
Looks good to me! :)

**Review by goodsong81 — APPROVED** [review]

**Review by eunwoosh — APPROVED** [review]

**Pull request merged**
