### PR TITLE
Fix nncf optimization for anomaly task

### PR DESCRIPTION
**Pull request by ashwinvaidya17**
### Summary

- Since modelAPI transforms the image internally, and nncf optimization works on the bare graph, this PR adds transformation to the nncf dataloader. 

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [x] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Comment by ashwinvaidya17** [comment]
image
E2E tests. I had to set `update=True` in `_validate_fq_in_xml`

**Review by samet-akcay — DISMISSED** [review]
Thanks for chasing this down @ashwinvaidya17

**Review by goodsong81 — DISMISSED** [review]
Thank you for the fix. What do you think of copying this change to releases/1.5.0 branch if needed? Retargeting might also work.

**Comment by ashwinvaidya17** [comment]
> Thank you for the fix. What do you think of copying this change to releases/1.5.0 branch if needed? Retargeting might also work.

I'll create another PR for that. Basically just pick the merge commit like last time. Or possibly add it to this PR https://github.com/openvinotoolkit/training_extensions/pull/2531

**Comment by sovrasov** [comment]
> image E2E tests. I had to set `update=True` in `_validate_fq_in_xml`

Please, add the updated FQ refs to this PR. Otherwise, daily tests won't pass

**Review by sovrasov — APPROVED** [review]

**Review by goodsong81 — APPROVED** [review]

**Pull request merged**
