### PR TITLE
Fix DINOv2 data transform, add linear probe recipe

### PR DESCRIPTION
**Pull request by sungmanc**
### Summary

image

As you can see in the figure above, DINOv2 with linear probe showed faster & better performance in our 3 datasets including small, medium, large datasets. So, I added the recipe for the linear probing of the DINO v2 Classification.

Since linear probing is not mandatory recipe to us, I didn't added the linear probing recipe to the Regression tests

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Comment by jaegukhyun** [comment]
If dinov2 works better on linear probe, how about move src/otx/recipe/classification/otx_dino_v2_linear_probe.yaml to src/otx/recipe/classification/otx_dino_v2.yaml. In my opinion, a recipe would be the best config for each model.

**Comment by sungmanc** [comment]
> If dinov2 works better on linear probe, how about move src/otx/recipe/classification/otx_dino_v2_linear_probe.yaml to src/otx/recipe/classification/otx_dino_v2.yaml. In my opinion, a recipe would be the best config for each model.

I also agree with your opinion. Want to hear other guys opinions also. Please share your thoughts.
@vinnamkim @harimkang

**Comment by vinnamkim** [comment]
> > If dinov2 works better on linear probe, how about move src/otx/recipe/classification/otx_dino_v2_linear_probe.yaml to src/otx/recipe/classification/otx_dino_v2.yaml. In my opinion, a recipe would be the best config for each model.
> 
> I also agree with your opinion. Want to hear other guys opinions also. Please share your thoughts. @vinnamkim @harimkang

From my experience, in almost all cases, the finetuning cannot be worse than the linear probing. If the target dataset is too small and has significant domain similarity with the pretrained dataset, the linear probing may have better generalization than the finetuning.

Keeping this in mind, I don't like `multiclass-CUB-*` benchmarks. I personally think that we should not use only these datasets to decide our decision. However, for now, we have to use them because we should compare OTX 2.0 with OTX 1.0.

Therefore, I recommend to include both of them. However, it seems that we should invent a new clever way to concise our configurations to cover those model variants.

**Comment by sungmanc** [comment]
> it seems that we should invent a new clever way to concise our configurations to cover those model variants.

I prefer this way, So, how about considering the better way to organize our recipes in the future ? @jaegukhyun

**Review by vinnamkim — APPROVED** [review]

**Review by jaegukhyun — APPROVED** [review]
Let's organize recipes later.

**Review by harimkang — APPROVED** [review]

**Pull request merged**
