### PR TITLE
[POT] Progress bar support

### PR DESCRIPTION
**Pull request by nikita-savelyevv**
Added the simplest progress updating for POT task. There are three discrete changes to the progress bar:
- 10% -- model is loaded
- 90% -- model is compressed
- 100% -- model is serialized

#ref 73631

### CODE REVIEW

**Comment by nikita-savelyevv** [comment]
run ote_sdk tests

**Comment by nikita-savelyevv** [comment]
run ote_sdk tests

**Comment by nikita-savelyevv** [comment]
run ote_sdk tests

**Comment by nikita-savelyevv** [comment]
run ote_sdk tests

**Comment by nikita-savelyevv** [comment]
run ote_sdk tests

**Comment by nikita-savelyevv** [comment]
run ote_sdk tests

**Comment by nikita-savelyevv** [comment]
ote-test/1567

**Review by alexsu52 — DISMISSED** [review]
As a first approximation is ok.

**Comment by druzhkov-paul** [comment]
run ote-test

**Comment by nikita-savelyevv** [comment]
run ote_sdk tests

**Comment by nikita-savelyevv** [comment]
run ote-test

**Comment by aiarkinx** [comment]
run ote-test

**Pull request merged**
