### PR TITLE
Demo package based on ModelAPI (2)

### PR DESCRIPTION
**Pull request by Ilya-Krylov**
BMM 20934 🕐

### CODE REVIEW

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Review by akorobeinikov — DISMISSED** [review]

**Comment by akorobeinikov** [comment]
ModelAPI is required to `exportable_code/demo/demo_package/utils`

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
BMM 20692 🕐

**Review by druzhkov-paul — APPROVED** [review]

**Comment by druzhkov-paul** [comment]
Build 21041 ✔️

**Pull request merged**
