### PR TITLE
Send full dataset to POT optimization function

### PR DESCRIPTION
**Pull request by AlexanderDokuchaev**
For anomaly task need use anomalous images from full dataset for quantization by POT.
For another tasks changes not affects, call `get_subset` inside optimize function.

Issue: 86003, 96371

### CODE REVIEW

**Review by alexsu52 — COMMENTED** [review]
Please, check your changes on BMM

**Review by samet-akcay — APPROVED** [review]
Thanks @AlexanderDokuchaev. Looks good to me too. As @alexsu52 pointed out, it would be good to check the CI and BMM to validate this. We could merge it then..

**Review by samet-akcay — DISMISSED** [review]
Forgot to mention, Is it possible to reflect these changes to `feature/otx` too?

**Review by ashwinvaidya17 — APPROVED** [review]

**Review by alexsu52 — APPROVED** [review]

**Review by alexsu52 — APPROVED** [review]
BMM, 47627

**Comment by goodsong81** [comment]
run ote-test

**Comment by goodsong81** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/801/

**Review by goodsong81 — APPROVED** [review]
LGTM.
BTW, if you want this PR to be included in the next release (OTE0.4.0->Geti1.1) you need to duplicate this PR to the release branch.

**Comment by goodsong81** [comment]
This change will be included to the release via other PR. No need for new PR duplicate.
https://github.com/openvinotoolkit/training_extensions/pull/1413

**Pull request merged**
