### PR TITLE
[OTX][MMCLS] Update mmcls to 0.24.1

### PR DESCRIPTION
**Pull request by GalyaZalesskaya**
- Updated MPA otx branch: [PR](https://github.com/openvinotoolkit/model_preparation_algorithm/pull/110)
- Tested training and evaluation of all classification models (classic, multilabel, hierarhical scenarios), using OTX CLI

### CODE REVIEW

**Comment by GalyaZalesskaya** [comment]
@goodsong81 Hi, Songki, because of major changes in [Public MMDetection PR](https://github.com/openvinotoolkit/training_extensions/pull/1382), that I'm bringing from `feature/otx-new-mmcv/base`, it makes the review of my PR quite difficult. 
So, maybe it's better to change target branch to `feature/otx-new-mmcv/base` instead of `feature/otx`, what do you think?

**Comment by harimkang** [comment]
Any decisions or updates on this?
+
PRs for the `feature/otx` target should not reflect `external` changes.
If this PR is ready, please request me to review it :)

**Comment by goodsong81** [comment]
@GalyaZalesskaya Let's retarget this PR to feature/otx-new-mmcv/base.
@harimkang Could you defer your task depending on new mmcls? I might take some time.

**Comment by GalyaZalesskaya** [comment]
Closing this PR, since changes here were applied as a part of merged [PR](https://github.com/openvinotoolkit/training_extensions/pull/1435) to feature/otx-new-mmcv/base

**Pull request closed without merging**
