### PR TITLE
Upgrade MAPI to v 0.1.6

### PR DESCRIPTION
**Pull request by sovrasov**
### Summary

This version contains a fix for merging iseg explain maps in ISeg tiler

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Review by eunwoosh — DISMISSED** [review]

**Review by goodsong81 — DISMISSED** [review]

**Comment by chuneuny-emily** [comment]
Is this a change that needs to be applied to the releases/1.5.0 branch as well?

**Comment by jaegukhyun** [comment]
Could you check e2e tests too?

**Comment by sovrasov** [comment]
> Is this a change that needs to be applied to the releases/1.5.0 branch as well?

Yes, because it contains a bugfix.

**Comment by sovrasov** [comment]
> Could you check e2e tests too?

I'll run them, as soon CI failures on precommit will be resolved.

**Comment by sovrasov** [comment]
> Could you check e2e tests too?

https://github.com/openvinotoolkit/training_extensions/actions/runs/6418837535

**Review by jaegukhyun — APPROVED** [review]
Daily tests seem fine.

**Review by goodsong81 — APPROVED** [review]

**Pull request merged**
