### PR TITLE
Fix incorrect matching of device in semisl_head

### PR DESCRIPTION
**Pull request by harimkang**
### Summary

Find some strange code. -> CPU training is not working in Semi-SL
Remove cuda() things in semisl_cls_head -> Now Semi-SL with CPU is working

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Review by sungmanc — COMMENTED** [review]
Is this case occurs when users have GPUs but don't want to use?

**Comment by harimkang** [comment]
> Is this case occurs when users have GPUs but don't want to use?

Exactly.The reason we didn't find out for a long time is because there is no cpu test. :)

**Review by sungmanc — APPROVED** [review]
Sounds great, we should need that for the future dev.

**Review by jaegukhyun — COMMENTED** [review]
Is this for cpu training while machine contain gpu? So the root cause is training is run by cpu but torch.cuda.is_available() returns True.

**Comment by harimkang** [comment]
> Is this for cpu training while machine contain gpu? So the root cause is training is run by cpu but torch.cuda.is_available() returns True.

Yes, that's right.

**Review by eunwoosh — APPROVED** [review]

**Review by jaegukhyun — APPROVED** [review]

**Pull request merged**
