### PR TITLE
[OTE_SDK_TESTS] Increase code coverage f_measure.py

### PR DESCRIPTION
**Pull request by saltykox**
Test list:
• ote_sdk/ote_sdk/tests/usecases/evaluation/test_f_measure.py

Task: CVS-74378

### CODE REVIEW

**Comment by saltykox** [comment]
run ote_sdk tests

**Comment by saltykox** [comment]
run ote_sdk tests

**Comment by saltykox** [comment]
@LeonidBeynenson @Ilya-Krylov please review

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Pull request merged**
