### PR TITLE
Restrict configurable parameters to avoid unreasonable cost for SaaS trial

### PR DESCRIPTION
**Pull request by harimkang**
### Summary

Restrict the following configurable parameters to avoid unreasonable cost for SaaS trial.
https://jira.devtools.intel.com/browse/CVS-131605

### Change Max value
- Max number of training iterations to 1k
- Max POT number of data samples to 1k

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Review by sungchul1 — APPROVED** [review]

**Review by MarkByun — APPROVED** [review]
LGTM

**Review by sungmanc — COMMENTED** [review]
Does it working well ? although we have training logcis based on epoch based runner

**Comment by harimkang** [comment]
> Does it working well ? although we have training logcis based on epoch based runner

There are no cases in OTX that use more than 1k num_iters other than selfsl (But in this case, we decided to reduce it to 1K.), and probably no test cases over 1k.

**Comment by MarkByun** [comment]
If batch size is one or two (ex, detection case) and number of dataset is more than 200 then max epoch is less than 10. It could make some problem. I will check this case with Andru.

**Comment by sungmanc** [comment]
> > Does it working well ? although we have training logcis based on epoch based runner
> 
> There are no cases in OTX that use more than 1k num_iters other than selfsl (But in this case, we decided to reduce it to 1K.), and probably no test cases over 1k.

I just want to make sure the restriction means the `number of iteration` itself. We usually controls the `number of epochs` by using `--learning_parameters.num_iters`

**Pull request merged**
