### PR TITLE
[OTX]Feature/otx mpa integ

### PR DESCRIPTION
**Pull request by sungmanc**
# Description
In the previous development environment, we need to merge MPA and OTX separately. And due to the separate PR process, we met difficulties to test w/the OTX environment, and many MPA issues were merged before checking.

# Objective
Integrate the latest MPA into the Feature/OTX

# Status
- [X] Local CLI test: Classification (100% PASS except for OPENVINO export accuracy issue)
image

- [X] Local CLI test: Detection (100% PASS)
image

- [X] Local CLI test: Instance Segmentation (100% PASS)
image

- [X] Local CLI test: Semantic Segmentation (100% PASS)
image

- [X] Local Pre-commit test (100% PASS)
image

- [x]  CI test

### CODE REVIEW

**Comment by sungmanc** [comment]
In my local pre-commit tests, there were many errors in
* `recording_forward_hooks.py`
* `early_stopping_hook.py`
* `cancel_interface_hook.py`
* `mpa/modules/ov/**`
* `mpa/seg/**`

@negvet  could you check for the `recording_forward_hooks.py` pre-commit test? I'll handle others

**Comment by harimkang** [comment]
That's a good progress!
However, I think this PR needs content to remove mpa from `requirements`.
Also, how about not checking the pre-commit test for the `otx/mpa` folder and `recipe` folder temporarily?
(I know that this can probably be adjusted in `tox.ini`.)

**Comment by sungmanc** [comment]
> However, I think this PR needs content to remove mpa from `requirements`.

Ah, I missed requirements things  ! Thanks, I'll edit

**Comment by sungchul1** [comment]
I'd like to know if this PR is for permanent or temporary integration.
If it's the former, is there any plan to update modules like `adapters` and remove unused modules or recipes?

**Comment by sungmanc** [comment]
> I'd like to know if this PR is for permanent or temporary integration. If it's the former, is there any plan to update modules like `adapters` and remove unused modules or recipes?

This is the first step to integrating MPA into the OTX. So, this step is a kind of temporary solution. 
We'll remove useless files and folders in the near future

**Review by harimkang — APPROVED** [review]
LGTM!
Thank you for your effort.

**Review by eunwoosh — APPROVED** [review]

**Review by supersoob — APPROVED** [review]

**Pull request merged**
