### PR TITLE
Apply changes from releases/v0.3.1-geti1.0.0

### PR DESCRIPTION
**Pull request by goodsong81**
* Merge release branches to develop (including submodules)

Test build: https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/694/
Related PR: https://github.com/openvinotoolkit/model_preparation_algorithm/pull/77 (merged)

### CODE REVIEW

**Comment by goodsong81** [comment]
run ote-test

**Comment by goodsong81** [comment]
run ote-test

**Comment by goodsong81** [comment]
run ote-test

**Comment by goodsong81** [comment]
run ote-test

**Review by ashwinvaidya17 — DISMISSED** [review]
I had a look at the anomaly stuff. Looks good to me. Thanks!

**Comment by harimkang** [comment]
The CI test results are strange. we have to take a look.
image

**Comment by harimkang** [comment]
run ote-test

**Comment by harimkang** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/708/

**Comment by harimkang** [comment]
I just realized this (https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/701) is the latest build. Please ignore the above comments.  ->But this has been stuck for a long time in the seg side test.

**Comment by harimkang** [comment]
Just created one more build to confirm. https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/708/

**Comment by sungmanc** [comment]
run ote-test

**Comment by sungmanc** [comment]
run ote-test

**Review by sungmanc — APPROVED** [review]
LGTM

**Review by yunchu — APPROVED** [review]

**Pull request merged**
