### PR TITLE
[CVS-88098] Remove initialize from export functions

### PR DESCRIPTION
**Pull request by harimkang**
### This PR includes:
- Remove initialize() function from export function (All of tasks)

### CODE REVIEW

**Comment by harimkang** [comment]
All local CLI tests have been PASSED.
but I haven't checked it in SC UI yet.

**Review by goodsong81 — DISMISSED** [review]
LGTM. You can merge this one after checking the test reuslt.

**Review by JihwanEom — DISMISSED** [review]
LGTM

**Comment by harimkang** [comment]
The previous commit still had an issue in the UI, so I revised it again.
This PR has passed the CLI test on local, and it has been confirmed that the POT works on the SC UI.
https://github.com/openvinotoolkit/training_extensions/pull/1225 -> Combined with this PR

**Review by goodsong81 — APPROVED** [review]

**Review by JihwanEom — APPROVED** [review]
LGTM

**Pull request merged**
