### PR TITLE
Change the cls head to make them same with the otx1.5

### PR DESCRIPTION
**Pull request by sungmanc**
### Summary

To ensure backward compatibility, we need to use the same head architecture.
So, I changed the head architecture to make the same head with OTX 1.5.

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Review by vinnamkim — COMMENTED** [review]
Where were the previous configs coming from?

**Review by jaegukhyun — DISMISSED** [review]

**Comment by sungmanc** [comment]
> Where were the previous configs coming from?

It comes from the default ImageClassifier of MobileNet-v3 from MMPretrain

**Comment by vinnamkim** [comment]
> > Where were the previous configs coming from?
> 
> It comes from the default ImageClassifier of MobileNet-v3 from MMPretrain

Did you compare the model accuracy results between the previous configs and this PRs? It is important to keep in mind that if some of legacy are found to be not good, we should throw it away rather than maintaining it blindly.

**Comment by sungmanc** [comment]
> Did you compare the model accuracy results between the previous configs and this PRs? It is important to keep in mind that if some of legacy are found to be not good, we should throw it away rather than maintaining it blindly.

Now I'm checking the results. In my opinion, we should keep the head architecture with OTX 1.5. 
If there was a user who used the Geti classification with OTX1.5, we should keep the accuracy if the user used the same dataset.
However, if the head architecture is different, we can't guarantee the previous model's accuracy due to the difference in the head.

That's the reason why I reverted the head architecture to the OTX1.5. 

I'm not sure we should change the head architecture although some backward compatibilities could be broken.

**Comment by sungmanc** [comment]
I discussed with the Mark, and we're going to support the backward compatible model (***_light.yaml) and otx model (otx_****).
Since I don't want to use the `Geti` word into the recipe, I used the `light` word. cc. @vinnamkim

**Review by eugene123tw — APPROVED** [review]

**Review by vinnamkim — APPROVED** [review]
LGTM.

**Review by harimkang — APPROVED** [review]

**Pull request merged**
