### PR TITLE
[OTE_SDK_TESTS] Rework test of nncf graph 

### PR DESCRIPTION
**Pull request by AlexanderDokuchaev**
Create special test for check NNCF graph, instead of run check after optimization.

### CODE REVIEW

**Review by alexsu52 — COMMENTED** [review]
I have the following major comments:
- Does the graph test work for MobilenetV3?
- How can a developer generate/update reference graphs?
- Do you have any regression relative to the current develop? I ask because you update nncf version.

**Comment by AlexanderDokuchaev** [comment]
https://github.com/openvinotoolkit/deep-object-reid/pull/175 - ote-test/916
https://github.com/openvinotoolkit/mmsegmentation/pull/65 - ote-test/927
https://github.com/openvinotoolkit/mmdetection/pull/315 - ote-test/926

mmdet: fail test_ote_api.py::API::test_training_maskrcnn_resnet50 under investigation (possible nncf issue)

**Comment by AlexanderDokuchaev** [comment]
ote-test/929/

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
BMM 25064 🕐

**Comment by Ilya-Krylov** [comment]
BMM 25064 ✔️

**Pull request merged**
