### PR TITLE
[Anomaly Classification] Add check to logger

### PR DESCRIPTION
**Pull request by ashwinvaidya17**
Fixes: https://jira.devtools.intel.com/browse/CVS-76094
BMM: https://10.211.120.58/projects/6200f29b61caa56c8b6b3bf3/models

### CODE REVIEW

**Comment by ashwinvaidya17** [comment]
run ote_sdk tests

**Review by djdameln — COMMENTED** [review]
Thanks for addressing this! It is still a bit unclear to me how it would be possible how the number of items in the GT and prediction dataset could differ. Also, I imagine this difference could cause problems elsewhere in the task?

**Comment by samet-akcay** [comment]
yeah, it's still a bit unclear how/why they are not the same. This would maybe avoid the error; however, i'm not sure what would be the behaviour when the metrics are computed with GT and predicted sets don't have the same lengths

**Comment by atwinand** [comment]
Same comment, better not to hide the issue like this. But you guys can confirm that the code is not playing around with the subsets?

**Comment by samet-akcay** [comment]
@atwinand, can confirm that subsets are not modified

**Comment by samet-akcay** [comment]
Closing this since this doesn't fully solve the issue, but silence it instead. The actual issue is thought to be on the backend

**Pull request closed without merging**
