### PR TITLE
[POT][develop] HRNet-x and HRNet-18-mod2 configs update

### PR DESCRIPTION
**Pull request by daniil-lyakhov**
Updated configs for big HRNets 
| Task         | Backend | OTE commit | Model         | FP32           | INT8 short ignored scope | INT8 updated ignored scope |
|--------------|---------|------------|---------------|----------------|--------------------------|----------------------------|
| Segmentation | MPA     | fbc22a09   | HRNet-18-mod2 | 0.8808         | 0.8637(-1.71%)           |  0.8712 (-0.96%)           |
| Segmentation | MPA     | fbc22a09   | Hrnet-X       | 0.8886         | 0.8396 (-4.9%)           | 0.8829(-0.57%)             |

ticket: 91663

### CODE REVIEW

**Review by alexsu52 — CHANGES_REQUESTED** [review]
Please, add a test that check the ignore scope is correct.

**Comment by daniil-lyakhov** [comment]
> Please, add a test that check the ignore scope is correct.

Tests will be implemented in a separate pr. Related ticket: 95650

**Review by alexsu52 — APPROVED** [review]

**Comment by goodsong81** [comment]
run ote-test

**Comment by goodsong81** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/798/

**Review by goodsong81 — APPROVED** [review]
Thank you for the update. I'll merge this PR after CI test check.

**Comment by goodsong81** [comment]
http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=pr-ote-test-798&environment=iotg-dev-workstation-08

**Comment by goodsong81** [comment]
@daniil-lyakhov Could you apply this change to release/v0.4.0-geti1.1.0 branch so that this PR could be included in the next release?

**Comment by daniil-lyakhov** [comment]
> @daniil-lyakhov Could you apply this change to release/v0.4.0-geti1.1.0 branch so that this PR could be included in the next release?

@goodsong81, please see #1419

**Pull request merged**
