### PR TITLE
[feature/otx] init_venv.sh for all tasks

### PR DESCRIPTION
**Pull request by harimkang**
## Summary
Add init_venv.sh for all task training once

This PR includes :
- Creating venv scripts for all tasks
  - anomaly
  - classification
  - detection & instance-segmentation
  - segmentation
  
**test in progress..**

Test command
```
# Set Environments
bash otx/algorithms/init_venv.sh ./venv python3.8
source venv/bin/activate
```

### CODE REVIEW

**Comment by sungmanc** [comment]
I am not sure that whether "classfication, detection, segmentation" are proper for the name of venvs or not. However, it can be merged. LGTM !

**Comment by samet-akcay** [comment]
@harimkang, these `init_venv.sh` scripts are temporary, right?

**Comment by goodsong81** [comment]
> @harimkang, these `init_venv.sh` scripts are temporary, right?

Yes, the next step is to implement the same functionality using pip install :)

**Comment by samet-akcay** [comment]
> > @harimkang, these `init_venv.sh` scripts are temporary, right?
> 
> Yes, the next step is to implement the same functionality using pip install :)

Great thanks! :)

**Comment by harimkang** [comment]
> @harimkang, these `init_venv.sh` scripts are temporary, right?

As Songki said, this is a temporary venv configuration script :)

**Pull request merged**
