### PR TITLE
Temporary fix override_configs bug

### PR DESCRIPTION
**Pull request by JihwanEom**
### Summary
- Fixed `override_configs` bug that does not update custom hooks  for cls/det/seg tasks. Reported by @sungchul2 

Command: `otx train --train-data-roots tests/assets/common_semantic_segmentation_dataset/train --val-data-roots tests/assets/common_semantic_segmentation_dataset/val/ params --learning_parameters.enable_supcon True`

### Before => override configs does not work
```
before_train_epoch:
(VERY_HIGH   ) ReduceLROnPlateauLrUpdaterHook     
(NORMAL      ) TaskAdaptHook                      
(LOW         ) IterTimerHook                      
(VERY_LOW    ) TextLoggerHook                     
(VERY_LOW    ) OTXLoggerHook                      
(VERY_LOW    ) MemCacheHook                       
(LOWEST      ) ForceTrainModeHook                 
```

### After => override configs works well (TwoCropTransformHook added)
```
before_train_epoch:
(VERY_HIGH   ) ReduceLROnPlateauLrUpdaterHook     
(NORMAL      ) TwoCropTransformHook               
(NORMAL      ) TaskAdaptHook                      
(LOW         ) IterTimerHook                      
(VERY_LOW    ) TextLoggerHook                     
(VERY_LOW    ) OTXLoggerHook                      
(VERY_LOW    ) MemCacheHook                       
(LOWEST      ) ForceTrainModeHook                 
```

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Review by sungchul1 — DISMISSED** [review]
LGTM

**Review by jaegukhyun — DISMISSED** [review]

**Review by sungmanc — APPROVED** [review]

**Review by sungmanc — DISMISSED** [review]

**Comment by eunwoosh** [comment]
It's not a bug. `override_config` is just for updating a config while runtime. As far as I understand, it's for updating the custom hook in supcon, but custom hook can be merged automatically just setting as below. How about to change supcon.py as below?
```
custom_hooks=[dict(type="TwoCropTransformHook", interval=5)]
```

**Comment by JihwanEom** [comment]
> 

Reflected, thanks.

**Review by eunwoosh — DISMISSED** [review]

**Review by sungmanc — DISMISSED** [review]

**Comment by sungchul1** [comment]
> It's not a bug. `override_config` is just for updating a config while runtime. As far as I understand, it's for updating the custom hook in supcon, but custom hook can be merged automatically just setting as below. How about to change supcon.py as below?
> 
> ```
> custom_hooks=[dict(type="TwoCropTransformHook", interval=5)]
> ```

You mean that a hook `A` to be updated in `custom_hooks` can be set like `custom_hooks = [A]`, maintaining `B` previously set in `_base_`?
If so, this change is okay for this case, but how to do it if the user wants to newly assign `custom_hooks` removing the previous one?

**Comment by eunwoosh** [comment]
> > It's not a bug. `override_config` is just for updating a config while runtime. As far as I understand, it's for updating the custom hook in supcon, but custom hook can be merged automatically just setting as below. How about to change supcon.py as below?
> > ```
> > custom_hooks=[dict(type="TwoCropTransformHook", interval=5)]
> > ```
> 
> You mean that a hook `A` to be updated in `custom_hooks` can be set like `custom_hooks = [A]`, maintaining `B` previously set in `_base_`? If so, this change is okay for this case, but how to do it if the user wants to newly assign `custom_hooks` removing the previous one?

Sorry for my mistake. I checked it and `custom_hooks` in latest one overrides the previous one. I look over how other recipe deals with it and I found that latest `custom_hooks` includes previous one explicitly if necessary.
When I check which hooks exists as custom_hooks before supcon.py, there is only `LazyEarlyStoppingHook`. So it can updated as below.
```
custom_hooks = [
    dict(
        type="LazyEarlyStoppingHook",
        patience=8,
        iteration_patience=0,
        metric="mDice",
        interval=1,
        priority=75,
        start=1,
    ),
    dict(type="TwoCropTransformHook", interval=5)
]
```

**Comment by sungchul1** [comment]
> > > It's not a bug. `override_config` is just for updating a config while runtime. As far as I understand, it's for updating the custom hook in supcon, but custom hook can be merged automatically just setting as below. How about to change supcon.py as below?
> > > ```
> > > custom_hooks=[dict(type="TwoCropTransformHook", interval=5)]
> > > ```
> > 
> > 
> > You mean that a hook `A` to be updated in `custom_hooks` can be set like `custom_hooks = [A]`, maintaining `B` previously set in `_base_`? If so, this change is okay for this case, but how to do it if the user wants to newly assign `custom_hooks` removing the previous one?
> 
> Sorry for my mistake. I checked it and `custom_hooks` in latest one overrides the previous one. I look over how other recipe deals with it and I found that latest `custom_hooks` includes previous one explicitly if necessary. When I check which hooks exists as custom_hooks before supcon.py, there is only `LazyEarlyStoppingHook`. So it can updated as below.
> 
> ```
> custom_hooks = [
>     dict(
>         type="LazyEarlyStoppingHook",
>         patience=8,
>         iteration_patience=0,
>         metric="mDice",
>         interval=1,
>         priority=75,
>         start=1,
>     ),
>     dict(type="TwoCropTransformHook", interval=5)
> ]
> ```

You are right. There is only `LazyEarlyStoppingHook` previously set in `_base_` and we can add it together for this case.
But I think it is very annoying and it may occur human error during copy-paste.
Users must find previous `custom_hooks` whenever they want to update `custom_hooks`.
If a config is wrapped by `dict`, we just can add a new parameter we want to add or can use `_delete_` to initialize the `dict` config.
But AFAIK, if a config is wrapped by `list` like `custom_hooks`, there is no way to update the `list` config and I think using `override_configs` is one of the ways to update `custom_hooks`.

Only for this case or otx recipes, I think current change is okay and it is needed to change this PR's scope such as 'fix supcon recipe'.

**Comment by jaegukhyun** [comment]
Yeah, I think we need to implement clean methods for updating custom_hooks. @JihwanEom How about fix this issue temporary by @eunwoosh solution and make another PR for implementing proper method to develop branch?

**Comment by jaegukhyun** [comment]
And maybe rebase will solve pre-commit issue

**Comment by eunwoosh** [comment]
Thanks for your opinion, @sungchul2 and @jaegukhyun . I also agree with your opinions. But I concern a little that `override_configs` is also one of same `custom_hooks` actually. So it also can be overrided by latest one. I think fundamental solution is necessary, but it's hard to find due to limitation of mmcv. Nevertheless, maybe there are some solutions for that. I think we can think this with time.

**Comment by jaegukhyun** [comment]
Yes, due to limited time for release, let's apply temporary solution and seek appropriate way to patch custom hooks in 1.4.0

**Comment by JihwanEom** [comment]
Thanks for good comments, I rebased and applied temporary solution proposed by @eunwoosh.

**Review by eunwoosh — DISMISSED** [review]

**Review by sungchul1 — DISMISSED** [review]

**Review by eunwoosh — APPROVED** [review]

**Review by sungchul1 — APPROVED** [review]

**Pull request merged**
