### PR TITLE
Remove unused LabelGraph class

### PR DESCRIPTION
**Pull request by sovrasov**
### Summary
LabelGraph was removed.

### Checklist

- [x] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Review by harimkang — APPROVED** [review]
LGTM,
Is this a class that will never be used?

**Comment by sovrasov** [comment]
> LGTM, Is this a class that will never be used?

This class just wraps the LabelTree and doesn't bring new functionality. Anyway, there are no plans to modify the implementation of label schema.

**Review by jaegukhyun — APPROVED** [review]
LGTM, could you add change log?

**Comment by sovrasov** [comment]
> LGTM, could you add change log?

Do we actually need this in that case? The PR just removes dead code, which doesn't affect OTX functionality.

@goodsong81 what is our policy for the changelog? Do we need to log even microscopic changes which may be interesting only for developers and updating changelog is a thing that must happen in every PR, or we can hide similar PRs behind something like "other minor improvements and cleanup in otx core"? Omitting minor changes might be also an option if the changelog is targeted to otx users.

**Comment by goodsong81** [comment]
> > LGTM, could you add change log?
> 
> Do we actually need this in that case? The PR just removes dead code, which doesn't affect OTX functionality.
> 
> @goodsong81 what is our policy for the changelog? Do we need to log even microscopic changes which may be interesting only for developers and updating changelog is a thing that must happen in every PR, or we can hide similar PRs behind something like "other minor improvements and cleanup in otx core"? Omitting minor changes might be also an option if the changelog is targeted to otx users.

No. As you said, we need to log anything worth noting to the change log.
If you think it's not that informative to OTX users, you can omit. :)

**Pull request merged**
