### PR TITLE
[CLASSIFICATION]: a bunch of minor fixes

### PR DESCRIPTION
**Pull request by kprokofi**
build 22686 - WIP

### CODE REVIEW

**Comment by kprokofi** [comment]
run ote_sdk tests

**Comment by kprokofi** [comment]
run ote_sdk tests

**Comment by sovrasov** [comment]
One anomaly test has failed: `21:23:10  tests/test_ote_anomaly_classification.py::TestAnomalyClassification::test_ote_train_export_and_optimize[anomaly_classification-padim] PASSED [ 62%]
21:23:32  tests/test_ote_anomaly_classification.py::TestAnomalyClassification::test_ote_train_export_and_optimize[anomaly_classification-stfpm] FAILED [ 75%]`

**Comment by sovrasov** [comment]
- do not crash if empty dataset is passed to infer()
- do not crash if some classes are presented in label schema, but not actually annotated
- remove model statuses everywhere

build 22692 on BMM is passed, manually tested

**Pull request merged**
