### PR TITLE
Add nncf configs for segmentation models

### PR DESCRIPTION
**Pull request by AlexanderDokuchaev**
+ add configs for segmentation models
+ update mmsegmetation   and mmdetection submudules to fix nncf bugs  https://github.com/openvinotoolkit/mmsegmentation/pull/86 https://github.com/openvinotoolkit/mmdetection/pull/344

Reopened https://github.com/openvinotoolkit/training_extensions/pull/1017

### CODE REVIEW

**Comment by AlexanderDokuchaev** [comment]
run ote_sdk tests

**Review by alexsu52 — COMMENTED** [review]
I want to highlight that the mmdetection includes @eugene123tw commits. I have added @eugene123tw to reviewers.

**Review by alexsu52 — DISMISSED** [review]

**Comment by Ilya-Krylov** [comment]
run ote-test

**Comment by goodsong81** [comment]
@eugene123tw Is this PR for OTE0.2.0 or SC1.1?

**Review by eugene123tw — DISMISSED** [review]

**Comment by eugene123tw** [comment]
run ote-test

**Comment by eugene123tw** [comment]
run ote-test

**Comment by goodsong81** [comment]
@sooahleex Does this PR need to be applied to SC1.2? Then please retarget it to releases/v0.2.0-sc1.1. If it's not, 'develop' is the right branch.

**Comment by wonjuleee** [comment]
> @sooahleex Does this PR need to be applied to SC1.2? Then please retarget it to releases/v0.2.0-sc1.1. If it's not, 'develop' is the right branch.

This work is related to https://jira.devtools.intel.com/browse/CVS-85209 targeting SC v1.1 to provide NNCF functionality in OTE semantic segmentation models. So it would be good to merge into releases/v0.2.0-sc1.1. @sooahleex, please retarget to releases/v0.2.0-sc1.1 as following @goodsong81's comment.

**Comment by goodsong81** [comment]
run ote-test

**Review by goodsong81 — CHANGES_REQUESTED** [review]
Could you update the mmseg/submodule commit to the latest 'ote' branch?
(I've merged the release branch back to ote branch.)

**Comment by goodsong81** [comment]
> run ote-test

https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/301/

**Comment by goodsong81** [comment]
run ote-test

**Comment by goodsong81** [comment]
run ote-test

**Comment by goodsong81** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/305/

**Comment by sooahleex** [comment]
run ote-test

**Comment by goodsong81** [comment]
run ote-test

**Review by goodsong81 — APPROVED** [review]

**Pull request merged**
