### PR TITLE
[PreCommit Fix] Address pre-commit issues that causes CI to fail

### PR DESCRIPTION
**Pull request by samet-akcay**
`develop` branch currently fails due to `pre-commit run --all-files`. This PR addresses the files affecting the pre-commit fail.

### CODE REVIEW

**Comment by samet-akcay** [comment]
run ote_test

**Comment by samet-akcay** [comment]
run ote-test

**Review by ashwinvaidya17 — APPROVED** [review]
Thanks for addressing this!

**Comment by samet-akcay** [comment]
Closing this to create a better solution

**Pull request closed without merging**
