### PR TITLE
[OTE] Added mmsegmentation input parameters validation and tests

### PR DESCRIPTION
**Pull request by saltykox**
Added input parameters validations for functions and methods in external/mmsegmentation/segmentation_tasks directory

Task: CVS-80221

### CODE REVIEW

**Comment by sstrehlk** [comment]
run ote-test

**Comment by sstrehlk** [comment]
run ote-test

**Review by sstrehlk — APPROVED** [review]

**Comment by goodsong81** [comment]
Is this PR for OTE0.2.0?

**Comment by sstrehlk** [comment]
It's related to SDL part - input parameters validation. If possible should be in OTE0.2.0

**Comment by goodsong81** [comment]
> It's related to SDL part - input parameters validation. If possible should be in OTE0.2.0

I see. Max & Tomasz said validation & SDL related PRs do not need to be included RC1. So let's merge this one after RC1 delivery.

**Comment by hlewando** [comment]
Tests passed:
http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=ote-test-1729&environment=iotg-dev-workstation-12

**Review by goodsong81 — APPROVED** [review]

**Comment by goodsong81** [comment]
Could you replicate this PR to releases/v0.2.0 branch, too?
(If it is intended to be included in this release. Restored the branch just in case.)
@sstrehlk @hlewando

**Pull request merged**
