### PR TITLE
[CI] Updated snyk-scan workflow

### PR DESCRIPTION
**Pull request by yunchu**
* Enabled to report as SARIF file to the security tab in the GH repo
* Enabled to upload the HTML formatted SNYK report as the workflow artifact

### CODE REVIEW

**Review by goodsong81 — DISMISSED** [review]

**Review by jaegukhyun — COMMENTED** [review]
LGTM, Why don't we remove commented part if they are unnecessary?

**Comment by yunchu** [comment]
To all reviewers, Sorry for the early opening the PR. I need to check whether it works as expected by running the workflow on our runner instance & Github. 
I'm not sure whether all you can see the results due to the permission to see it but if you are proper right, you can check the result here: https://github.com/openvinotoolkit/training_extensions/security/code-scanning?query=is%3Aopen+branch%3Ayunchule%2Ftest-snyk

**Comment by yunchu** [comment]
> LGTM, Why don't we remove commented part if they are unnecessary?

I think there are too much testenv in the tox.ini but i'm not sure it would be used for the others in the team.
that's why i've commented out all those. is it okay to remove them?

**Comment by goodsong81** [comment]
> > LGTM, Why don't we remove commented part if they are unnecessary?
> 
> I think there are too much testenv in the tox.ini but i'm not sure it would be used for the others in the team. that's why i've commented out all those. is it okay to remove them?

Per-task envs seem to be not well used. I think they are OK to be deleted.

**Comment by yunchu** [comment]
all things were checked and worked as expected. please give approval to merge it.

**Review by sungmanc — DISMISSED** [review]

**Review by goodsong81 — APPROVED** [review]

**Review by sungmanc — APPROVED** [review]

**Pull request merged**
