### PR TITLE
[FIX] nncf statistic error

### PR DESCRIPTION
**Pull request by cih9088**
### Summary
It makes sure to take the onnx branch when extracting ROI for two stage model series.

### Jira ticket
[CVS-104503](https://jira.devtools.intel.com/browse/CVS-104503)

### CODE REVIEW

**Comment by sungmanc** [comment]
To make sure, 
Could this problem also be occurred in any `Twostage Architecture (i.e. Faster R-CNN, ...)`?
Could this patch prevent these problems ?

IMO, maybe the answer is right, isn't it?

**Review by sungmanc — DISMISSED** [review]

**Review by harimkang — DISMISSED** [review]
I have confirmed that the issue in the ticket is not reproducible, thank you.

**Comment by harimkang** [comment]
BTW, this PR seems like a good idea to change and merged right into the release branch, do you agree? @goodsong81 @sungmanc

**Comment by cih9088** [comment]
> To make sure, Could this problem also be occurred in any `Twostage Architecture (i.e. Faster R-CNN, ...)`? Could this patch prevent these problems ?
> 
> IMO, maybe the answer is right, isn't it?

I haven't tested them but if they used `SingleRoIExtracotr`, the answer would be yes.

**Comment by sungmanc** [comment]
> BTW, this PR seems like a good idea to change and merged right into the release branch, do you agree? @goodsong81 @sungmanc

Exactly, we should do. @cih9088  could you change the target branch as releases/v1.0.0?

**Comment by cih9088** [comment]
> BTW, this PR seems like a good idea to change and merged right into the release branch, do you agree?

Do you want me to change the target branch to v1.0.0?

**Comment by sungmanc** [comment]
> > To make sure, Could this problem also be occurred in any `Twostage Architecture (i.e. Faster R-CNN, ...)`? Could this patch prevent these problems ?
> > IMO, maybe the answer is right, isn't it?
> 
> I haven't tested them but if they used `SingleRoIExtracotr`, the answer would be yes.

Thanks for giving the nice remedy

**Review by sungmanc — APPROVED** [review]

**Review by harimkang — APPROVED** [review]

**Review by goodsong81 — APPROVED** [review]

**Pull request merged**
