### PR TITLE
CVS-88175 Resolve issue when warmup_iters=0

### PR DESCRIPTION
**Pull request by harimkang**
### This PR includes :
- Update `warmup=None` when `warmup_iters=0`
- Resolve MPA task flake8 issues

### CODE REVIEW

**Review by JihwanEom — DISMISSED** [review]
LGTM

**Comment by harimkang** [comment]
run ote-test

**Review by jaegukhyun — COMMENTED** [review]
I think we can avoid reduplication via defining set_lr_config function. What do you think?, @harimkang

**Comment by harimkang** [comment]
> I think we can avoid reduplication via defining set_lr_config function. What do you think?, @harimkang

In fact, all three tasks' `_init_recipe_hparam` functions are redundant. However, there was an opinion to divide it by task, and it is currently separated for that reason. I think the idea would be good to proceed with another PR.

**Review by jaegukhyun — DISMISSED** [review]
Okay, then it looks good to me.

**Review by chuneuny-emily — DISMISSED** [review]

**Comment by harimkang** [comment]
@JihwanEom Can you check this fail in classification test (https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-model-preparation-algorithm-test/53/)

**Comment by JihwanEom** [comment]
Hi @eugene123tw , this PR is failing by feature map key error. Could you review this PR and tell us this issue can be resolved by merging your PR? (https://github.com/openvinotoolkit/training_extensions/pull/1166)

**Comment by harimkang** [comment]
re-run test : https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-model-preparation-algorithm-test/55/

**Review by jaegukhyun — APPROVED** [review]
LGTM

**Review by JihwanEom — APPROVED** [review]
LGTM

**Comment by harimkang** [comment]
Test Results: http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=pr-model-preparation-algorithm-test-55&environment=iotg-dev-workstation-16

**Pull request merged**
