### PR TITLE
[OTE_SDK_TESTS] Added input parameters validation and tests. Part 2 Shapes

### PR DESCRIPTION
**Pull request by saltykox**
Added input parameters validations for Shapes classes of OTE SDK:
•	Ellipse class: initialization and get_evenly_distributed_ellipse_coordinates methods
•	Point class: initialization, normalize_wrt_roi and denormalize_wrt_roi_shape methods
•	Polygon class: initialization method
•	Rectangle class: initialization, is_full_box and crop_numpy_array methods
•	Shape class: initialization, intersects, contains_center, get_labels, append_label, set_labels and _validate_coordinates methods
Tests updated according to above changes: 
•	test_rectangle.py: test_rectangle_is_full_box
Added tests/parameters_validation/test_shapes_input_parameters_validation.py with negative scenarios to check that ValueError exception is raised when unexpected type object is specified in Shape methods

Task: CVS-77259

### CODE REVIEW

**Comment by saltykox** [comment]
run ote_sdk tests

**Comment by saltykox** [comment]
run ote_sdk tests

**Comment by nervana-ff** [comment]
Can one of the admins verify this patch?

**Comment by Ilya-Krylov** [comment]
draft?

**Comment by saltykox** [comment]
This pull request is in the “Draft” state due to unmerged base PR https://github.com/openvinotoolkit/training_extensions/pull/890, but the approach to check input parameters is ready for review

**Comment by saltykox** [comment]
ote-test/1262

**Comment by saltykox** [comment]
run ote_sdk tests

**Comment by saltykox** [comment]
run ote-test

**Comment by saltykox** [comment]
@LeonidBeynenson @Ilya-Krylov please review

**Comment by saltykox** [comment]
run ote_sdk tests

**Comment by saltykox** [comment]
run ote-test

**Comment by yunchu** [comment]
closed due to clean up the stale branches

**Pull request closed without merging**
