### PR TITLE
Updated NNCF config for hrnet18-mod2 

### PR DESCRIPTION
**Pull request by daniil-lyakhov**
Updated config to train nncf compressed model in 2e2 with expected accuracy drop.
Please see details in a ticket 84131

### CODE REVIEW

**Comment by goodsong81** [comment]
Is this PR for SC1.2? Then please retarget to release branch.

**Review by alexsu52 — DISMISSED** [review]

**Comment by alexsu52** [comment]
> Is this PR for SC1.2? Then please retarget to release branch.

Hi @goodsong81! Can it get into SC 1.2?

**Comment by goodsong81** [comment]
> > Is this PR for SC1.2? Then please retarget to release branch.
> 
> Hi @goodsong81! Can it get into SC 1.2?

We think that we have still some chance to cut into SC1.2 by creating OTE RC2.
If it fails, we would just merge the branch back to develop.
Why don't we give it a try?
@chuneuny-emily Do you agree with this strategy?

**Comment by goodsong81** [comment]
run ote-test

**Comment by goodsong81** [comment]
@daniil-lyakhov Could you resolve the conflict? The rebased release branch seems to have something to fix.

**Comment by daniil-lyakhov** [comment]
> @daniil-lyakhov Could you resolve the conflict? The rebased release branch seems to have something to fix.

Done

**Review by alexsu52 — APPROVED** [review]

**Review by harimkang — APPROVED** [review]

**Review by goodsong81 — APPROVED** [review]

**Pull request merged**
