### PR TITLE
[SEGMENTATION] Fix OTESeg tests

### PR DESCRIPTION
**Pull request by evgeny-izutov**

### CODE REVIEW

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by aiarkinx** [comment]
run ote-test

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by evgeny-izutov** [comment]
run ote-test

**Comment by Ilya-Krylov** [comment]
13:51:56  prettier.................................................................Failed
13:51:56  - hook id: prettier
13:51:56  - files were modified by this hook
13:51:56  
13:51:56  external/mmsegmentation/segmentation_tasks/apis/segmentation/configuration.yaml
13:51:56  external/mmsegmentation/tests/expected_metrics/metrics_test_ote_training.yml

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by evgeny-izutov** [comment]
run ote-test

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by evgeny-izutov** [comment]
run ote-test

**Comment by Ilya-Krylov** [comment]
12:58:33  isort (ote_sdk)..........................................................Passed
12:58:33  isort (ote_cli|external).................................................Passed
12:58:35  black (ote_sdk|ote_cli)..................................................Passed
12:58:35  black (rest).............................................................Passed
12:58:38  flake8...................................................................Passed
12:58:38  prettier.................................................................Failed
12:58:38  - hook id: prettier
12:58:38  - files were modified by this hook
12:58:38  
12:58:38  external/mmsegmentation/tests/expected_metrics/metrics_test_ote_training.yml
12:58:38  
12:58:43  mypy (ote_sdk)...........................................................Passed
12:58:44  mypy (ote_cli)...........................................................Passed
12:58:44  mypy (external)..........................................................Passed
12:59:11  pylint...................................................................Passed

**Comment by evgeny-izutov** [comment]
run ote-test

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by evgeny-izutov** [comment]
run ote-test

**Pull request merged**
