### PR TITLE
Feature/multi batch validation

### PR DESCRIPTION
**Pull request by sungmanc**
* Set the default num_workers as 2 for classification / detection tasks
* Update MPA submodule to enable multi-batch validation

### CODE REVIEW

**Comment by sungmanc** [comment]
run ote-test

**Comment by sungmanc** [comment]
@harimkang I've checked with local OTE tests and found that there is no fail cases about num_workers and reflected MPA repo's latest change related to multi-batch for instance segmentation (@eugene123tw).

**Comment by sungmanc** [comment]
The below figure represents the test results for classification, and instance segmentation. In the detection case, there is no FAILED case

image

**Comment by harimkang** [comment]
> @harimkang I've checked with local OTE tests and found that there is no fail cases about num_workers and reflected MPA repo's latest change related to multi-batch for instance segmentation (@eugene123tw).

Cool!
In summary, the validation batch size is flexible for detection, and instance-segmentation is currently fixed at 1, right?

**Comment by harimkang** [comment]
> The below figure represents the test results for classification, and instance segmentation. In the detection case, there is no FAILED case

When I ran the instance segmentation cli test based on develop in the morning, there was no fail case. Do you know what kind of issue it is?

**Comment by sungmanc** [comment]
> > @harimkang I've checked with local OTE tests and found that there is no fail cases about num_workers and reflected MPA repo's latest change related to multi-batch for instance segmentation (@eugene123tw).
> 
> Cool! In summary, the validation batch size is flexible for detection, and instance-segmentation is currently fixed at 1, right?

Yeah, for the detection multi-batch is enabled. However, it will be not enabled for instance segmentation cases.

**Comment by sungmanc** [comment]
> > The below figure represents the test results for classification, and instance segmentation. In the detection case, there is no FAILED case
> 
> When I ran the instance segmentation cli test based on develop in the morning, there was no fail case. Do you know what kind of issue it is?

I'll recheck it. In my case, all of the failed cases was occurred due to Counting algorithm

**Comment by sungmanc** [comment]
> > The below figure represents the test results for classification, and instance segmentation. In the detection case, there is no FAILED case
> 
> When I ran the instance segmentation cli test based on develop in the morning, there was no fail case. Do you know what kind of issue it is?

@harimkang , Was the develop branch latest? I just checked with the latest develop branch before 5 minutes, I still got 15 errors related to Custom_Counting_Instance_Segmentation as below. 

image

**Comment by harimkang** [comment]
> @harimkang , Was the develop branch latest? I just checked with the latest develop branch before 5 minutes, I still got 15 errors related to Custom_Counting_Instance_Segmentation as below.
> 

...! I did it on develop, which I pulled this morning. I'll check it one more time.

**Comment by sungmanc** [comment]
> > @harimkang , Was the develop branch latest? I just checked with the latest develop branch before 5 minutes, I still got 15 errors related to Custom_Counting_Instance_Segmentation as below.
> 
> ...! I did it on develop, which I pulled this morning. I'll check it one more time.

Thx a lot. please let me know if there is no problem on your side

**Comment by eugene123tw** [comment]
@sungmanc Could you merge the upstream `develop`, [external/mmdetection/detection_tasks/apis/detection/configuration.py](https://github.com/openvinotoolkit/training_extensions/pull/1302/files#diff-3949ce452ff393847ea9bc3cea9e9357910660c45684781e88c4082b43c2780e) and external/model-preparation-algorithm/mpa_tasks/apis/detection/task.py were both merged in `develop`

**Comment by eugene123tw** [comment]
> > @harimkang I've checked with local OTE tests and found that there is no fail cases about num_workers and reflected MPA repo's latest change related to multi-batch for instance segmentation (@eugene123tw).
> 
> Cool! In summary, the validation batch size is flexible for detection, and instance-segmentation is currently fixed at 1, right?

@harimkang yes, this should be fixed in instance seg for the time being as there's a bug. I have added a stopgap: https://github.com/openvinotoolkit/training_extensions/pull/1305. AFAIK, Sungman will look into it

**Comment by harimkang** [comment]
run ote-cli

**Comment by harimkang** [comment]
run ote-test

**Comment by harimkang** [comment]
This will be addressed with the same content in [PR](https://github.com/openvinotoolkit/training_extensions/pull/1314).

@sungmanc I think it can be closed, what do you think?

**Comment by sungmanc** [comment]
> This will be addressed with the same content in [PR](https://github.com/openvinotoolkit/training_extensions/pull/1314).
> 
> @sungmanc I think it can be closed, what do you think?

Sure ! Let's close this PR

**Pull request closed without merging**
