### PR TITLE
[NNCF] Remove ability to enable model pruning in UI

### PR DESCRIPTION
**Pull request by nikita-savelyevv**
Disabled ability to turn on filter pruning for a model if it is not supported for this model. Added `pruning_supported` boolean parameter that is false by default and is true for couple of models that currently support filter pruning. #ref 80370

### CODE REVIEW

**Comment by MaximProshin** [comment]
@AlexanderDokuchaev , @nikita-savelyevv , please sync about Anomaly where it should also be added

**Comment by AlexanderDokuchaev** [comment]
@nikita-savelyevv  @MaximProshin I will add same changes to anomaly in my PR

**Comment by nikita-savelyevv** [comment]
run ote_sdk tests

**Comment by nikita-savelyevv** [comment]
run ote_sdk tests

**Comment by nikita-savelyevv** [comment]
run ote_sdk tests

**Comment by nikita-savelyevv** [comment]
run ote_sdk tests

**Comment by nikita-savelyevv** [comment]
run ote_sdk tests

**Comment by nikita-savelyevv** [comment]
run ote_sdk tests

**Review by alexsu52 — DISMISSED** [review]

**Comment by nikita-savelyevv** [comment]
run ote_sdk tests

**Comment by nikita-savelyevv** [comment]
@Ilya-Krylov, the two failed tests from CI:
```
20:17:02  FAILED tests/ote_cli/external/mmdetection/test_ote_cli_tools_detection.py::TestToolsDetection::test_pot_optimize[Custom_Object_Detection_Gen3_ATSS]
20:17:02  FAILED tests/ote_cli/external/mmdetection/test_ote_cli_tools_detection.py::TestToolsDetection::test_pot_eval[Custom_Object_Detection_Gen3_ATSS]
```
pass when I run them locally

UPD: I was suggested to rebase and re-run tests as the issue should be fixed in the newer openvino pre-release

**Comment by nikita-savelyevv** [comment]
run ote_sdk tests

**Review by AlexanderDokuchaev — APPROVED** [review]

**Comment by nikita-savelyevv** [comment]
@Ilya-Krylov, should be ready for merge, @alexsu52 won't be able to review this week

**Pull request merged**
