### PR TITLE
Fix h-label loss normalization issue w/ exclusive label group of singe label

### PR DESCRIPTION
**Pull request by goodsong81**
### Summary

* Exclusive label groups are expected to have more than 1 labels. If it has just 1 label,
the group is regarded as single label group which corresponds to a label in multi-label classification.
image
* In case that a batch has samples with that label only, the `num_effective_heads_in_batch` below
could be 0 even if the `num_multiclass_heads` > 0.
image
* This fix is an workaround in OTX side; not to divide by 0. "Exclusive group with single label" should be prevented by UX or other user frontend because it's not correct by definition.

### How to test

* Hard to reproduce on OTX side

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Review by sovrasov — DISMISSED** [review]

**Review by sungmanc — COMMENTED** [review]
Don't we need to consider the below?
https://github.com/openvinotoolkit/training_extensions/blob/c22c683664a28b076187311cecaa8e7cc048b2ee/src/otx/algorithms/classification/adapters/mmcls/models/heads/custom_hierarchical_non_linear_cls_head.py#L138

**Comment by goodsong81** [comment]
> Don't we need to consider the below?
> 
> https://github.com/openvinotoolkit/training_extensions/blob/c22c683664a28b076187311cecaa8e7cc048b2ee/src/otx/algorithms/classification/adapters/mmcls/models/heads/custom_hierarchical_non_linear_cls_head.py#L138

Thanks, I've fixed it, too.

**Comment by sovrasov** [comment]
Do we have to apply this in 1.5 as well?

**Comment by goodsong81** [comment]
> Do we have to apply this in 1.5 as well?

Yes, right. But there are a few other changes in 1.4.0 branch that are not yet applied to 1.5.0.
Let's merge-back all at once. @yunchu @chuneuny-emily What do you think?

**Review by sungmanc — APPROVED** [review]

**Review by sovrasov — APPROVED** [review]

**Comment by sovrasov** [comment]
> > Do we have to apply this in 1.5 as well?
> 
> Yes, right. But there are a few other changes in 1.4.0 branch that are not yet applied to 1.5.0. Let's merge-back all at once. @yunchu @chuneuny-emily What do you think?

I was replicating all the fixes, because as far as I remember, there are some incompatible changes.

I'd appreciate merge-back 1.5 -> develop though

**Pull request merged**
