### PR TITLE
edit num_workers and change MPA repo as a latest

### PR DESCRIPTION
**Pull request by sungmanc**
* Change the num_workers for classification, detection tasks
* Change MPA submodule as latest

### CODE REVIEW

**Comment by sungmanc** [comment]
@eugene123tw , @harimkang In previous [PR](https://github.com/openvinotoolkit/training_extensions/pull/1302), since there was complex commit history hard to resolve, I want to use this new branch to enable multi-batch & num-workers. 

If you have no concerns for this PR, let use this PR instead of previous one.

**Comment by sungmanc** [comment]
run ote-test

**Comment by harimkang** [comment]
[This ](http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=pr-ote-test-642&environment=iotg-dev-workstation-09) is the OTE CI test result based on the previous [PR](https://github.com/openvinotoolkit/training_extensions/pull/1302) (As far as I understand it is the same as this PR).
There seems to be no problem with basic detection and instance-segmentation training tests.
FAILED test cases:
- classification
- segmentation (nncf tests)
- tiling (nncf_eval & pot_optimize)

@eugene123tw It seems that nncf evaluation and some pot tests fail on the tiling side. Could you please take a look at this?

**Review by harimkang — APPROVED** [review]
I would like to hear Eugene's opinion and suggest merging this PR.

**Comment by harimkang** [comment]
run ote-test

**Review by eugene123tw — APPROVED** [review]
LGTM

**Comment by sungmanc** [comment]
The below link represents the CI test result and there is no FAILED cases related to this PR 
: http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=pr-ote-test-643&environment=iotg-dev-workstation-08

**Comment by kprokofi** [comment]
what is the reason to set num_workers to 0?

**Comment by goodsong81** [comment]
> what is the reason to set num_workers to 0?

This PR sets it to 2 for classification & detection.
We had some hanging issue due to multi-process deadlock in segmentation so that we didn't enable it at this time.
There are other concerns like instability regarding CPU usage in torch official site; it seems that generally 0 is recommend for stability. We tested and 2 looks fine for now.

**Pull request merged**
