### PR TITLE
Fliter NaN score prediction in inference

### PR DESCRIPTION
**Pull request by eugene123tw**
Fliter NaN score prediction in inference

### CODE REVIEW

**Comment by eugene123tw** [comment]
run ote-test

**Comment by eugene123tw** [comment]
> What do you think of adding an input exception handling in OTE SDK (ScoredLabel, maybe) side as well as preventing NaN in inference side as Andru's suggestion?

@goodsong81 I added a variable check for `ScoredLabel`. CI log: https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/371/console

**Comment by goodsong81** [comment]
run ote-test

**Comment by goodsong81** [comment]
Re-run test due to too many CUDA OoM errors.

**Review by goodsong81 — APPROVED** [review]
LGTM.
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/374/

**Review by JihwanEom — APPROVED** [review]
LGTM.

**Pull request merged**
