### PR TITLE
[TEST] Remove unused files in mpa/modules

### PR DESCRIPTION
**Pull request by JihwanEom**
## This PR includes:
- Rename `MPAClsDataset` to `OTXClsDataset`
- Remove `ClsDirDataset`, replace `ClsDirDataset` with `OTXClsDataset` (by this, test codes are updated.)
- Delete duplicated backbones (effcientnet-b0, effcientnet-v2-s, mobilenet-v3 by `otx.algorithms.common.adapters.mmcv.models`)
- Clear `lwf` legacies (multi_classifier_head, task_incremental_classifier_head)
- Remove outdated `otx.mpa.modules.datasets.samplers.distributed_sampler`

### CODE REVIEW

**Review by supersoob — COMMENTED** [review]
Could you rebase and make it run ci test? and hope I can check the e2e local test result.

**Comment by JihwanEom** [comment]
> 

Please wait patiently until the issues are resolved. [WIP] will be removed from title after that, I will attach all the test results on this PR. Thank you.

**Comment by JihwanEom** [comment]
Passed pre-merge tests, local e2e tests except known issues.
image

I also believe below fails are not related with this PR.
```
15 failed cases are:
1. TestToolsAnomalyClassification.test_pot_validate_fq[ote_anomaly_classification_stfpm]: AssertionError: Incorrect number of FQs in optimized model: 68 != 69
2. TestToolsAnomalyDetection.test_otx_eval_openvino[ote_anomaly_detection_stfpm]: AssertionError: trained_performance[k]=0.9310344827586206, exported_performance[k]=0.8999999999999999
3. TestToolsAnomalyDetection.test_otx_eval_openvino[ote_anomaly_detection_padim]: AssertionError: trained_performance[k]=0.6779661016949152, exported_performance[k]=0.6666666666666665
4. TestToolsAnomalyDetection.test_pot_validate_fq[ote_anomaly_detection_stfpm]: AssertionError: Incorrect number of FQs in optimized model: 68 != 69
5. TestToolsAnomalySegmentation.test_pot_validate_fq[ote_anomaly_segmentation_stfpm]: AssertionError: Incorrect number of FQs in optimized model: 68 != 69
6. TestToolsMultiClassClassification.test_pot_validate_fq[Custom_Image_Classification_MobileNet-V3-large-1x]: AssertionError: Incorrect number of FQs in optimized model: 146 != 102
7. TestToolsMultilabelClassification.test_pot_validate_fq[Custom_Image_Classification_MobileNet-V3-large-1x]: AssertionError: Incorrect number of FQs in optimized model: 146 != 106
8. TestToolsMPADetection.test_nncf_validate_fq[Custom_Object_Detection_Gen3_ATSS]: AssertionError: Incorrect number of FQs in optimized model: 155 != 160
9. TestToolsMPADetection.test_nncf_eval[Custom_Object_Detection_YOLOX]: AssertionError: trained_performance[k]=0.21621621621621612, evaluated_performance[k]=0.2105263157894736
10. TestToolsMPADetection.test_nncf_eval[Custom_Object_Detection_Gen3_SSD]: AssertionError: trained_performance[k]=0.14634146341463408, evaluated_performance[k]=0.14285714285714277
11. TestToolsMPAInstanceSegmentation.test_otx_eval_openvino[Custom_Counting_Instance_Segmentation_MaskRCNN_EfficientNetB2B]: AssertionError: trained_performance[k]=0.049999999999999885, exported_performance[k]=0.0
12. TestToolsMPASegmentation.test_nncf_validate_fq[Custom_Semantic_Segmentation_Lite-HRNet-18-mod2_OCR]: AssertionError: Incorrect number of FQs in optimized model: 580 != -1
13. TestToolsMPASegmentation.test_nncf_validate_fq[Custom_Semantic_Segmentation_Lite-HRNet-s-mod2_OCR]: AssertionError: Incorrect number of FQs in optimized model: 432 != -1
14. TestToolsMPASegmentation.test_nncf_validate_fq[Custom_Semantic_Segmentation_Lite-HRNet-x-mod3_OCR]: AssertionError: Incorrect number of FQs in optimized model: 1130 != -1
15. TestToolsMPASegmentation.test_nncf_validate_fq[Custom_Semantic_Segmentation_Lite-HRNet-18_OCR]: AssertionError: Incorrect number of FQs in optimized model: 580 != -1
```

**Review by sungmanc — APPROVED** [review]
Thank you for the nice work !

**Review by goodsong81 — APPROVED** [review]
Wow, what a work, indeed.

**Pull request merged**
