### PR TITLE
Change dataset to enhance the E2E detection tests (including tiling, ins-seg)

### PR DESCRIPTION
**Pull request by sungmanc**
### Summary

This PR adds car-tree-bug dataset samples to resolve the E2E fail cases.
In the current status, we have 4 FAILS in latest E2E tests.
and 3 tests were `openvino_eval` or `nncf_eval` in detection / tiling / ins-seg tasks.
I believe more dataset could resolve this error.

About 1 remaining fail case, I'll take a look 

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Comment by sungmanc** [comment]
image
Since this PR couldn't resolve the issue, I converted this PR as DRAFT.

**Comment by jaegukhyun** [comment]
Tiling uses different dataset

**Comment by sungmanc** [comment]
> Tiling uses different dataset

Thanks for letting me know :)

**Comment by sungmanc** [comment]
A weird error was detected. Need to investigate more. (test_tiling_detection.py::TestToolsTilingDetection::test_otx_resume[SSD])
Excepting for this, all FAIL cases were resolved.

image

**Comment by jaegukhyun** [comment]
Where the experiments are conducted? I think it should be ik server

**Comment by sungmanc** [comment]
> Where the experiments are conducted? I think it should be ik server

In the workstation05. Above error randomly occurs even in the workstation.

**Comment by jaegukhyun** [comment]
Since model performance vary for gpu, performance should be checked in IK server. What do you think?

**Comment by sungmanc** [comment]
> Since model performance vary for gpu, performance should be checked in IK server. What do you think?

It could be. However, since this is the E2E test that doesn't measure performance itself, the server doesn't make the problem.
E2E tests just measuring the performance difference between trained model and exported, optimized model.

**Pull request closed without merging**
