### PR TITLE
Add doc for fast data loading

### PR DESCRIPTION
**Pull request by cih9088**
### Summary
Added doc for fast data loading

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Review by sungmanc — COMMENTED** [review]
Could you also update the cli_commands document? It missed the contents to introduce how to use ArrowFormat in OTX CLI.

**Comment by cih9088** [comment]
> Could you also update the cli_commands document? It missed the contents to introduce how to use ArrowFormat in OTX CLI.

Added in https://github.com/openvinotoolkit/training_extensions/pull/2069/commits/6fb391bb1846fed533630eebe7e0f2feb89cc5e5

**Review by sungmanc — DISMISSED** [review]

**Comment by sungmanc** [comment]
@goodsong81 , How about changing the target `develop` --> `release/1.2.1` ?
This PR includes the documents of 1.2.0's features

**Comment by goodsong81** [comment]
> @goodsong81 , How about changing the target `develop` --> `release/1.2.1` ? This PR includes the documents of 1.2.0's features

I agree, for the completeness. Thanks for the suggestion.

**Comment by goodsong81** [comment]
@cih9088 If you retarget this PR to 1.2.1, I would merge it right away. Thanks!

**Review by goodsong81 — DISMISSED** [review]
LGTM!

**Review by goodsong81 — APPROVED** [review]

**Review by sungmanc — APPROVED** [review]

**Pull request merged**
