### PR TITLE
[OTE_SDK_TESTS] Increase code coverage. utils/shape_drawer.py

### PR DESCRIPTION
**Pull request by saltykox**
Test list:
•	ote_sdk/ote_sdk/tests/utils/test_shape_drawer.py
•	ote_sdk/ote_sdk/tests/entities/test_result_media.py
•	ote_sdk/ote_sdk/tests/entities/test_tensor.py

Task: CVS-73927

### CODE REVIEW

**Comment by saltykox** [comment]
run ote_sdk tests

**Comment by saltykox** [comment]
run ote_sdk tests

**Comment by saltykox** [comment]
run ote_sdk tests

**Comment by saltykox** [comment]
run ote_sdk tests

**Comment by saltykox** [comment]
@LeonidBeynenson @Ilya-Krylov please review

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Pull request merged**
