### PR TITLE
Upgrade torch version to 2.0.1 & pre-commit in v2

### PR DESCRIPTION
**Pull request by harimkang**
### Summary

- Upgrade to torch==2.0.1
- Remove black
Replace black with ruff. According to the author of ruff, it is 30x faster than black and 99% compatible. As can be seen from the changes, it is indeed compatible in our case. For more details, you could refer to this [link](https://twitter.com/charliermarsh/status/1716861072374657497?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Etweet).
image

- Update pre-commit version (mypy & ruff)

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Comment by goodsong81** [comment]
Please note that there is some known issues in OTX1.x with torch2.0.1.
https://github.com/openvinotoolkit/training_extensions/issues/2451

I'm not sure whether we have plan to enable NNCF QAT on OTX2.0, though.

**Comment by harimkang** [comment]
> Please note that there is some known issues in OTX1.x with torch2.0.1. #2451
> 
> I'm not sure whether we have plan to enable NNCF QAT on OTX2.0, though.

Yes, that's right, I'm afraid that optimization for OTX 2.0 is still uncharted territory.
@samet-akcay We don't think hard enough about optimization. We need a good design and I think we need to find an issue with optimization side.

**Review by jaegukhyun — APPROVED** [review]

**Comment by samet-akcay** [comment]
> > Please note that there is some known issues in OTX1.x with torch2.0.1. #2451
> > I'm not sure whether we have plan to enable NNCF QAT on OTX2.0, though.
> 
> Yes, that's right, I'm afraid that optimization for OTX 2.0 is still uncharted territory. @samet-akcay We don't think hard enough about optimization. We need a good design and I think we need to find an issue with optimization side.

I think we need to have a clear list of requirements first. There is a bit of uncertainty there unfortunately. Once we know what exactly we need to support, we could then initiate some discussions with the nncf folks to have a clear design

**Review by samet-akcay — APPROVED** [review]
Thanks for addressing, this. It is time to say goodbye to our good old `black`

**Review by eugene123tw — APPROVED** [review]

**Pull request merged**
