### PR TITLE
[PreCommit Fix] MPA precommit fail issue fix

### PR DESCRIPTION
**Pull request by chuneuny-emily**
This PR includes
- Update the expected criteria for semantic segmentation task
- Rename the model_template_id as original mmseg ones
- Update warmup_iters/num_iters in template.yaml in sseg

### CODE REVIEW

**Comment by chuneuny-emily** [comment]
run ote-test

**Review by jaegukhyun — DISMISSED** [review]
LGTM

**Review by goodsong81 — DISMISSED** [review]
LGTM.
Please check for the IDs carefully.

**Review by jaegukhyun — APPROVED** [review]
LGTM

**Review by goodsong81 — APPROVED** [review]

**Pull request merged**
