### PR TITLE
Update ModelAPI in 1.4 release

### PR DESCRIPTION
**Pull request by sovrasov**
### Summary
A minor upgrade with a bugfix in fit_to_windows resize

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Review by sungmanc — DISMISSED** [review]
Thanks for the quick update :)

**Review by goodsong81 — DISMISSED** [review]

**Review by jaegukhyun — CHANGES_REQUESTED** [review]
Let's merge after e2e test

**Comment by jaegukhyun** [comment]
https://github.com/openvinotoolkit/training_extensions/actions/runs/5528981268
If this PR is fine to merge, there should be only classification test failures

**Review by sungchul1 — DISMISSED** [review]

**Review by goodsong81 — DISMISSED** [review]

**Comment by jaegukhyun** [comment]
After fixing intg tests, I'll re-run daily

**Comment by jaegukhyun** [comment]
https://github.com/openvinotoolkit/training_extensions/actions/runs/5542442246 new daily tests.
I hope all pass

**Review by jaegukhyun — APPROVED** [review]
Daily are passed! LGTM

**Review by sungchul1 — APPROVED** [review]

**Review by sungmanc — APPROVED** [review]

**Pull request merged**
