### PR TITLE
Update algo backends and fix bandit issues

### PR DESCRIPTION
**Pull request by LeonidBeynenson**

### CODE REVIEW

**Comment by LeonidBeynenson** [comment]
run ote tests

**Comment by LeonidBeynenson** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
BMM 22190 🕐

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
BMM 22192 🕐

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Pull request merged**
