### PR TITLE
fliter object less than 1 pixel 

### PR DESCRIPTION
**Pull request by eugene123tw**
Please check this blocking MPA PR first: https://github.com/openvinotoolkit/model_preparation_algorithm/pull/70

### CODE REVIEW

**Comment by eugene123tw** [comment]
run ote-test

**Comment by eugene123tw** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/647/

**Review by goodsong81 — DISMISSED** [review]
LGTM.
BTW, was the issue related to only size? Anyway, we have no mechanism for clipping the rotated box into image area (different from normal bbox case).
It's up to you. :)

**Comment by goodsong81** [comment]
@eugene123tw Ah, BTW, could you replicate this change to release branch? The bug should be fixed in this version.

**Review by harimkang — DISMISSED** [review]
It looks good, but in the CI test, I see a FAIL case that was not seen in the instance-segmentation side. It's an nncf test, so it doesn't seem to be related to this PR. right?
[validation-report](http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=pr-ote-test-647&environment=iotg-dev-workstation-08)

Also, it seems that the submodule needs to be updated.

**Comment by eugene123tw** [comment]
> LGTM. BTW, was the issue related to only size? Anyway, we have no mechanism for clipping the rotated box into image area (different from normal bbox case). It's up to you. :)

I think the message is a bit misleading. The issue is caused by an object area smaller than 1 pixel. 
```
Could not save annotations due to a server issue.
Error: Shape out of bounds for annotation with type ROTATED_RECTANGLE and dimensions x=496.25, y=272.25, width=1.4142, height=0.7071, angle=135: this shape needs to have at least 1 pixels within the image.
```

**Comment by eugene123tw** [comment]
> It looks good, but in the CI test, I see a FAIL case that was not seen in the instance-segmentation side. It's an nncf test, so it doesn't seem to be related to this PR. right? [validation-report](http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=pr-ote-test-647&environment=iotg-dev-workstation-08)
> 
> Also, it seems that the submodule needs to be updated.

no, the NNCF test failure it's not related to this change. And I updated the submodule

**Review by goodsong81 — DISMISSED** [review]
LGTM. But could you apply this change to release branch?
(Or, you can just re-target this PR to release branch.)

**Comment by eugene123tw** [comment]
> LGTM. But could you apply this change to release branch? (Or, you can just re-target this PR to release branch.)

I've created another PR for realeses: https://github.com/openvinotoolkit/training_extensions/pull/1326

**Review by goodsong81 — CHANGES_REQUESTED** [review]
Could you resolve the conflicts?

**Comment by eugene123tw** [comment]
run ote-test

**Comment by eugene123tw** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/675/

**Review by goodsong81 — APPROVED** [review]

**Pull request merged**
