### PR TITLE
Valid POT configs for small HRNet models

### PR DESCRIPTION
**Pull request by daniil-lyakhov**
Quantization results for small segmentation models, dataset = kvasir
| Task         | Backend | Model         | Result metric | POT results (ignored scope, quantile, fb=false, ss=500) | POT results(ignored scope, quantile)  | POT default config w/o ignoring scope |
|--------------|---------|---------------|---------------|----------------------------------------------|-----------------|-----------------|
| Segmentation | MPA     | Hrnet-18      | 0.8723        | 0.8743(+0.2%)                                | 0.8742 (+0.19%) | 0.7875 (-8.48%) |
| Segmentation | MPA     | Hrnet-s-mod2  | 0.8682        | 0.8713(+0.31%)                               | 0.8674 (-0.08%) | 0.8281(-4.01%) |

### CODE REVIEW

**Comment by JihwanEom** [comment]
Could you share the accuracy before updating NNCF configs?

**Review by alexsu52 — APPROVED** [review]

**Comment by goodsong81** [comment]
Thank you for the PR. BTW, is this just an improvement or a fix?
If it's related to the "temporary disable NNCF and ensure POT fallback", why don't you replicate this PR also to release branch so that we can apply this to Geti1.0 gold?
(Same goes for NNCF PR)

**Comment by daniil-lyakhov** [comment]
> Thank you for the PR. BTW, is this just an improvement or a fix? If it's related to the "temporary disable NNCF and ensure POT fallback", why don't you replicate this PR also to release branch so that we can apply this to Geti1.0 gold? (Same goes for NNCF PR)

This is a bug, required POT configs are missing for some reason. Please see ticket 95122 for details.
I'll open PR to the release branch

**Comment by daniil-lyakhov** [comment]
Release branch PR:  #1317

**Review by goodsong81 — APPROVED** [review]

**Pull request merged**
