### PR TITLE
Enable resume

### PR DESCRIPTION
**Pull request by JihwanEom**
### Summary:
- Enable resume for all tasks & add cli test for resume. (cls/det/seg)
- Change MPA commit to latest develop
- Change DOR commit to latest develop (ote)
- Bugfix for ReduceOnLRPleateau leanring rate
- Related MPA PR: https://github.com/openvinotoolkit/model_preparation_algorithm/pull/52
- Related DOR PR: https://github.com/openvinotoolkit/deep-object-reid/pull/233

### CODE REVIEW

**Comment by JihwanEom** [comment]
This PR will be merged after merging both MPA & DOR PR.

**Comment by JihwanEom** [comment]
CI is not working properly, so I attach CLI test result from local environment. You can reproduce same result on this branch with this command: `pytest -rs ./external/model-preparation-algorithm/tests/ote_cli/test_[multiclass, det, seg]_cls_il.py`

Classification


Detection


Segmentation

Passed all the test cases.

**Review by harimkang — CHANGES_REQUESTED** [review]
Is there any information on how to use it? (I can't see documentation change) Also, I wonder which of the `--load_weights` and `--resume` we can get is the preferred use of the existing stored ckpt. 
and what's the difference between the `--load_weights resume_ckpt` and `--resume`

**Comment by JihwanEom** [comment]
> Is there any information on how to use it? (I can't see documentation change) Also, I wonder which of the `--load_weights` and `--resume` we can get is the preferred use of the existing stored ckpt. and what's the difference between the `--load_weights resume_ckpt` and `--resume`

Thank you for suggestion, document is updated now, changed `--resume` to `--resume-from`. If user inputs both `--load-weights` and `--resume-from`, `--resume-from` will be applied.

**Review by chuneuny-emily — DISMISSED** [review]

**Comment by JihwanEom** [comment]
run ote-test

**Comment by JihwanEom** [comment]
run ote-test

**Comment by harimkang** [comment]
run ote-test

**Comment by harimkang** [comment]
Could you add ote_cli tests for resume?

**Review by jaegukhyun — DISMISSED** [review]
LGTM

**Comment by JihwanEom** [comment]
run ote-test

**Comment by JihwanEom** [comment]
run ote-test

**Comment by JihwanEom** [comment]
run ote-test

**Comment by JihwanEom** [comment]
run ote-test

**Comment by JihwanEom** [comment]
run ote-test

**Comment by JihwanEom** [comment]
run ote-test

**Comment by JihwanEom** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/653/
http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=pr-ote-test-653&environment=iotg-dev-workstation-10
Passed all resume related test cases.

**Comment by JihwanEom** [comment]
run ote-test

**Comment by JihwanEom** [comment]
run ote-test

**Comment by JihwanEom** [comment]
run ote-test

**Comment by JihwanEom** [comment]
run ote-test

**Comment by JihwanEom** [comment]
run ote-test

**Comment by JihwanEom** [comment]
Closing by enabling resume on feature/otx #1470

**Pull request closed without merging**
