### PR TITLE
[FIX] Fix e2e tests segmentation and classification SelfSL

### PR DESCRIPTION
**Pull request by kprokofi**
### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Comment by kprokofi** [comment]
Classification:
image

**Comment by kprokofi** [comment]
Segmentation SelfSL
image

**Review by jaegukhyun — APPROVED** [review]
Thanks for the quick fix

**Review by sungmanc — COMMENTED** [review]
Couldn't we use the `--algo_backend.train_type Selfsupervised / Semisupervised`?

**Review by eunwoosh — COMMENTED** [review]
LGTM. But how about to set `Semisupervised` explicitly to prepare some possibility later?

**Comment by kprokofi** [comment]
> Couldn't we use the `--algo_backend.train_type Selfsupervised / Semisupervised`?

Not anymore. Now only --train-type. --algo-backend used when args are ignored (otx train after the environment is built)

**Comment by kprokofi** [comment]
> LGTM. But how about to set `Semisupervised` explicitly to prepare some possibility later?

It is not required. --unlabeled-data-roots now is enough to start semi-sl + I add a check that semi-sl actually was launched

**Review by eunwoosh — APPROVED** [review]

**Pull request merged**
