### PR TITLE
[MPA] Apply Adaptive Training in Det/Ins-seg & Update model params

### PR DESCRIPTION
**Pull request by harimkang**
### This PR includes :
- Update model template params from recent experiments for tuning models in Det/Ins-seg Tasks
- Update Adaptive Training in Det/Ins-seg tasks (https://github.com/openvinotoolkit/model_preparation_algorithm/pull/38)
- EMA Fix(https://github.com/openvinotoolkit/model_preparation_algorithm/pull/39) merged in this PR

### CODE REVIEW

**Comment by harimkang** [comment]
run ote-test

**Comment by harimkang** [comment]
Currently, CI test is not working properly, so i am checking two CLI tests locally.
- pytest -s -v external/model-preparation-algorithm/tests/ote_cli/test_ins_seg_cls_il.py
- pytest -s -v external/model-preparation-algorithm/tests/ote_cli/test_det_cls_il.py

Also, I am going to check the sample including export.

**Comment by harimkang** [comment]
All of the CLI tests mentioned in the above comment were PASSED locally without any problems. (det/ins-seg)

@jaegukhyun There seems to be a problem with the YOLOX side of the sample (the IR export and inference side). 
This is a problem that does not seem to be relevant to the PR (all other models work well, det/ins-seg)

**Review by goodsong81 — APPROVED** [review]
LGTM.

**Review by chuneuny-emily — APPROVED** [review]

**Pull request merged**
