### PR TITLE
[CVS-91469] Add a deprecated sseg model template to support compatibility

### PR DESCRIPTION
**Pull request by chuneuny-emily**
### This PR includes :
- Add a deprecated sseg model template(litehrnet18) to support compatibility

### CODE REVIEW

**Comment by chuneuny-emily** [comment]
run ote-test

**Comment by harimkang** [comment]
Does it work well on SC?

**Review by jaegukhyun — APPROVED** [review]

**Comment by chuneuny-emily** [comment]
> Yes. It works fine.

**Comment by chuneuny-emily** [comment]
> Does it work well on SC?

Yes It works fine.

**Review by harimkang — APPROVED** [review]

**Review by JihwanEom — APPROVED** [review]
LGTM

**Pull request merged**
