### PR TITLE
[HPO] enable HPO with segmentation

### PR DESCRIPTION
**Pull request by eunwoosh**
This PR includes changes for HPO with segmentation task.

The list of changes are as follows:
- Implement code of setting epoch for segmentation task.
- Implement HPO test code in segmentation test.

### CODE REVIEW

**Comment by eunwoosh** [comment]
run ote_sdk test

**Comment by eunwoosh** [comment]
run ote_sdk tests

**Comment by nervana-ff** [comment]
Can one of the admins verify this patch?

**Comment by eunwoosh** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
10:30:35  isort (ote_sdk)..........................................................Passed
10:30:35  isort (ote_cli|external).................................................Passed
10:30:38  black (ote_sdk|ote_cli)..................................................Failed
10:30:38  - hook id: black
10:30:38  - files were modified by this hook
10:30:38  
10:30:38  reformatted ote_cli/ote_cli/utils/hpo.py
10:30:38  All done! ✨ 🍰 ✨
10:30:38  1 file reformatted, 228 files left unchanged.
10:30:38  
10:30:38  black (rest).............................................................Passed
10:30:40  flake8...................................................................Passed
10:30:40  prettier.................................................................Failed
10:30:40  - hook id: prettier
10:30:40  - files were modified by this hook
10:30:40  
10:30:40  .github/labeler.yml
10:30:40  
10:30:46  mypy (ote_sdk)...........................................................Passed
10:30:46  mypy (ote_cli)...........................................................Passed
10:30:47  mypy (external)..........................................................Passed
10:31:09  pylint...................................................................Failed
10:31:09  - hook id: pylint
10:31:09  - exit code: 12
10:31:09  
10:31:09  ************* Module ote_cli.utils.hpo
10:31:09  ote_cli/ote_cli/utils/hpo.py:98:0: R0914: Too many local variables (18/15) (too-many-locals)
10:31:09  ote_cli/ote_cli/utils/hpo.py:156:0: R1721: Unnecessary use of a comprehension (unnecessary-comprehension)
10:31:09  ote_cli/ote_cli/utils/hpo.py:159:57: W0108: Lambda may not be necessary (unnecessary-lambda)

**Comment by Ilya-Krylov** [comment]
update submodule?

add new ote_cli test for segmentation?

**Comment by eunwoosh** [comment]
run ote_sdk tests

**Comment by eunwoosh** [comment]
run ote_sdk tests

**Comment by eunwoosh** [comment]
run ote_sdk tests

**Comment by eunwoosh** [comment]
run ote_sdk tests

**Comment by eunwoosh** [comment]
run ote_sdk tests

**Comment by eunwoosh** [comment]
run ote_sdk tests

**Comment by eunwoosh** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by eunwoosh** [comment]
@Ilya-Krylov Could you check this PR?

**Pull request merged**
