### PR TITLE
Update ignored scopes for segmentation models

### PR DESCRIPTION
**Pull request by AlexanderDokuchaev**
Update for discuss https://github.com/openvinotoolkit/training_extensions/pull/1578#issuecomment-1411350794

Update ignored scopes after changed layer names in IR.

### CODE REVIEW

**Comment by sungmanc** [comment]
Could you attach the local e2e test results for segmentation? 
`pytest -s -v tests/e2e/cli/segmentation`

**Review by sungmanc — CHANGES_REQUESTED** [review]
Could you attach the local e2e test results for segmentation? 
`pytest -s -v tests/e2e/cli/segmentation`

**Comment by AlexanderDokuchaev** [comment]
> Could you attach the local e2e test results for segmentation?

@sungmanc, nope, optimization tests of segmentation are skipped and broken.

**Review by sungmanc — APPROVED** [review]
Let's merge first, then check the results w/ daily test

**Review by goodsong81 — APPROVED** [review]

**Pull request merged**
