### PR TITLE
[DETECTION] CVS-82705, CVS-82738

### PR DESCRIPTION
**Pull request by Ilya-Krylov**

### CODE REVIEW

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Review by druzhkov-paul — DISMISSED** [review]

**Comment by druzhkov-paul** [comment]
run ote-test

**Comment by druzhkov-paul** [comment]
run ote-test

**Comment by Ilya-Krylov** [comment]
set export_perf_delta_tolerance=0.001 to let the failed test pass

**Pull request merged**
