### PR TITLE
Pruning supported tweaks

### PR DESCRIPTION
**Pull request by nikita-savelyevv**
Tweaked some pruning related parameters:
- CVS-90400 Disabled pruning for EfficientNet-V2-S as it is not working as expected
- CVS-91015 Turned off pruning_supported parameter visibility for anomaly models

### CODE REVIEW

**Comment by nikita-savelyevv** [comment]
run ote-test

**Comment by nikita-savelyevv** [comment]
Test run: https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/591/
BMM: in the process of verifying, blocked by CVS-91472

**Comment by nikita-savelyevv** [comment]
run ote-test

**Comment by nikita-savelyevv** [comment]
Test run: https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/596/
BMM: https://10.211.120.60/

**Review by harimkang — APPROVED** [review]

**Review by chuneuny-emily — APPROVED** [review]

**Pull request merged**
