### PR TITLE
[feature/otx]: Supcon for Multilabel and Hierarchical classification

### PR DESCRIPTION
**Pull request by arrufat**
This PR completes the #1406 with support for Multiclass and Hierarchical classification.

### CODE REVIEW

**Comment by JihwanEom** [comment]
@sungchul2 Can we close this PR?

**Comment by sungchul1** [comment]
> @sungchul2 Can we close this PR?

It's not for me. I think you can close this if you need.

**Comment by arrufat** [comment]
Ah, this PR is "complete" already. It needs some more testing/tuning.
The only reason why I didn't merge it was because the Multi-label Classification with SupCon is not able to outperform the baseline (without SupCon). Hierarchical with SupCon works better than the baseline, though.

**Comment by sungchul1** [comment]
@arrufat Thanks for comment :)
@JihwanEom As adria said, some tests and tunings remain. Could you decide if closing this PR or remaining as draft? We can re-open or re-create a new PR when starting this task.

**Pull request closed without merging**
