### PR TITLE
[feature/otx] Add write permissions in Build-Docs

### PR DESCRIPTION
**Pull request by chuneuny-emily**
Add write permissions in Build-Docs

### CODE REVIEW

**Review by sungmanc — APPROVED** [review]

**Comment by GalyaZalesskaya** [comment]
I'm sorry, but is there a way to trigger docs-build action from this PR to check if these changes helped?

**Comment by chuneuny-emily** [comment]
Add write permissions in Build-Docs

**Comment by GalyaZalesskaya** [comment]
Or the only way to do it is to push these changes to feature/otx and trigger action?

**Comment by chuneuny-emily** [comment]
> I'm sorry, but is there a way to trigger docs-build action from this PR to check if these changes helped?

No But the root cause is clear. Once this PR is merged, then Build-Docs will be run, and will work fine.

**Review by GalyaZalesskaya — APPROVED** [review]

**Pull request merged**
