### PR TITLE
[OTE SDK] Input validation for numeric configurable parameters

### PR DESCRIPTION
**Pull request by ljcornel**
This PR enables strict input validation for numeric configurable parameters, to make sure that only values of the proper type can be set.

I have built the SC platform with this change, all tests passed:

- SC build test results: http://validationreports.sclab.intel.com:8004/reports/build_number_report?test_session_build_number=IMPTOps-21501&environment=ljcornel_config_validation

This PR addresses the following ticket: https://jira.devtools.intel.com/browse/CVS-71717

### CODE REVIEW

**Comment by ljcornel** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
@ljcornel some issues were detected

**Comment by ljcornel** [comment]
@Ilya-Krylov Thanks, I noticed the CI pipeline failure. I'll find out what the problem is and re-run the tests once I've fixed it.

**Comment by ljcornel** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
14:09:11  Fixing /home/jenkins/b/workspace/ote/precommit/ote_sdk_tests_runner/src/ote_sdk/ote_sdk/configuration/elements/primitive_parameters.py
14:09:11  
14:09:11  isort (ote_cli|external).................................................Passed
14:09:13  black (ote_sdk|ote_cli)..................................................Failed
14:09:13  - hook id: black
14:09:13  - files were modified by this hook
14:09:13  
14:09:13  reformatted ote_sdk/ote_sdk/configuration/elements/utils.py
14:09:13  All done! ✨ 🍰 ✨
14:09:13  1 file reformatted, 185 files left unchanged.
14:09:13  
14:09:13  black (rest).............................................................Passed
14:09:15  flake8...................................................................Passed
14:09:16  prettier.................................................................Passed
14:09:20  mypy (ote_sdk)...........................................................Passed
14:09:20  mypy (ote_cli)...........................................................Passed
14:09:21  mypy (external)..........................................................Passed
14:10:00  pylint...................................................................Failed
14:10:00  - hook id: pylint
14:10:00  - exit code: 12
14:10:00  
14:10:00  ************* Module ote_sdk.configuration.elements.utils
14:10:00  ote_sdk/ote_sdk/configuration/elements/utils.py:186:4: W0613: Unused argument 'instance' (unused-argument)
14:10:00  ote_sdk/ote_sdk/configuration/elements/utils.py:213:12: R1701: Consider merging these isinstance calls to isinstance(value, (float, int)) (consider-merging-isinstance)
14:10:00  ote_sdk/ote_sdk/configuration/elements/utils.py:223:4: W0613: Unused argument 'instance' (unused-argument)

**Comment by ljcornel** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
16:33:10  isort (ote_sdk)..........................................................Failed
16:33:10  - hook id: isort
16:33:10  - files were modified by this hook
16:33:10  
16:33:10  Fixing /home/jenkins/b/workspace/ote/precommit/ote_sdk_tests_runner/src/ote_sdk/ote_sdk/configuration/elements/primitive_parameters.py
16:33:10  
16:33:10  isort (ote_cli|external).................................................Passed
16:33:11  black (ote_sdk|ote_cli)..................................................Failed
16:33:11  - hook id: black
16:33:11  - files were modified by this hook
16:33:11  
16:33:11  reformatted ote_sdk/ote_sdk/configuration/elements/utils.py
16:33:11  All done! ✨ 🍰 ✨
16:33:11  1 file reformatted, 185 files left unchanged.
16:33:11  
16:33:11  black (rest).............................................................Passed
16:33:13  flake8...................................................................Passed
16:33:13  prettier.................................................................Passed
16:33:17  mypy (ote_sdk)...........................................................Passed
16:33:17  mypy (ote_cli)...........................................................Passed
16:33:18  mypy (external)..........................................................Passed
16:33:45  pylint...................................................................Passed

**Comment by ljcornel** [comment]
run ote_sdk tests

**Pull request merged**
