### PR TITLE
Fix collect_env_vars to use both uppercase and lowercase env vars

### PR DESCRIPTION
**Pull request by daniil-lyakhov**
I'm enclosed problem during local test launching: lowercase vars `http_proxy`, `https_proxy` and `no_proxy` is valid but don't forwarding to ote command launch

### CODE REVIEW

**Comment by alexsu52** [comment]
run ote_sdk tests

**Comment by alexsu52** [comment]
run ote-test

**Comment by goodsong81** [comment]
Being tested: https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/149/

**Comment by goodsong81** [comment]
Moved to https://github.com/openvinotoolkit/training_extensions/pull/1067

**Pull request merged**
