### PR TITLE
New metadata field 'step_size' for float configurable parameters

### PR DESCRIPTION
**Pull request by leoll2**
### Summary

Add a new optional field `step_size` to float configurable parameters to indicate the recommended increment/decrement step.
For example, if the parameter indicates a percentage (`some_ratio=(min_value=0, max_value=1.0, step_size=0.01)`), the step size suggests that values should be rounded at the second decimal digit that is 1%.
In Geti UI, this information can be used to display more user-friendly sliders (CVS-109311).

### Checklist

- [x] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [x] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [x] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Review by sovrasov — APPROVED** [review]

**Comment by goodsong81** [comment]
@leoll2 Do you need @ljcornel's approval? Or can we just merge this PR if it's OK?

**Comment by leoll2** [comment]
@goodsong81 e2e tests fail. I'm waiting for support from the validation team

**Comment by goodsong81** [comment]
> @goodsong81 e2e tests fail. I'm waiting for support from the validation team

If you mean the OTX tests, rebase might helps. @yunchu could you confirm? It might be due to changes in CI setting.

**Comment by leoll2** [comment]
I mean Geti e2e tests. I selected Geti develop branch and this PR as OTX commit, but a lot of tests fail without a clear reason:
https://ci.iotg.sclab.intel.com/job/IMPT/job/IMPTOps/61137/
Rebuilding didn't help unfortunately.

**Review by ljcornel — APPROVED** [review]
Looks good to me, thanks Leo!

**Comment by leoll2** [comment]
e2e pass after fix: 

validationreports.sclab.intel.com:8004/reports/build_number_report?test_session_build_number=IMPTOps-61299&environment=leo-step-size

**Review by harimkang — APPROVED** [review]

**Pull request merged**
