### PR TITLE
Num_workers=0 for classification tasks

### PR DESCRIPTION
**Pull request by JihwanEom**
### Summary:
- Disabled max_num_epochs on UI (we are only using num_iters)
- Changed to num_workers=0 for classification tasks
- Update MPA commit to disable persistent_workers (only operates with num_workers > 0)

### CODE REVIEW

**Comment by JihwanEom** [comment]
run ote-test

**Comment by JihwanEom** [comment]
run ote-test

**Comment by JihwanEom** [comment]
FYI, this PR will be merged after merging MPA PR:  https://github.com/openvinotoolkit/model_preparation_algorithm/pull/45

**Comment by JihwanEom** [comment]
CI is not working properly, tested CLI tests on local environment with below command:
• pytest -rs external/model-preparation-algorithm/tests/ote_cli/test_multilabel_cls_il.py
image
Passed all the test cases. (also include multiclass, hierarchical classification tests.)

**Review by chuneuny-emily — DISMISSED** [review]

**Review by supersoob — DISMISSED** [review]

**Review by goodsong81 — DISMISSED** [review]

**Review by chuneuny-emily — APPROVED** [review]

**Review by goodsong81 — APPROVED** [review]

**Review by supersoob — APPROVED** [review]

**Pull request merged**
