### PR TITLE
Add ImageColorChannel to ImageInfo

### PR DESCRIPTION
**Pull request by vinnamkim**
### Summary

- Same as title
- By default, the OpenVINO data pipeline (`src/otx/config/data/openvino.yaml`) will use BGR color channel.

### How to test
Added an unit test for this change.

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Comment by sovrasov** [comment]
@vinnamkim do these changes mean we always use RGB for all torch models and all image reading methods, excepting OV models?

**Comment by vinnamkim** [comment]
> @vinnamkim do these changes mean we always use RGB for all torch models and all image reading methods, excepting OV models?

It is recommended to use RGB as a default. This is because 1) our models' pretrained weights are almost based on RGB and 2) machine learning community has preferred to RGB. So I changed the default as RGB in this PR, https://github.com/openvinotoolkit/training_extensions/pull/2749.

In this PR, I wanted to introduce the color channel format which is selectable by the dataset configuration and trackable for ease of debugging. The reason why I expanded it is that I saw this comment https://github.com/openvinotoolkit/training_extensions/pull/2769#discussion_r1447229495

> I checked that BGR is by default used in our OTX. Answering to your question, OV requires BGR images, not RGB

**Review by sungmanc — APPROVED** [review]

**Review by jaegukhyun — APPROVED** [review]

**Review by samet-akcay — COMMENTED** [review]
Would it be an idea to use one library rather than multiple ones interchangibly? PIL and cv2 are "almost" doing the same thing,  so i was wondering whether we could just use one of them? This would mean one-less-dependency. Also easier-maintainability and so on?

**Comment by jaegukhyun** [comment]
https://github.com/openvinotoolkit/training_extensions/pull/2586#discussion_r1377534625
OpenCV can handle corrupted images which cannot be handled in PIL. However, I prefer to choose one framework also.

**Comment by vinnamkim** [comment]
> Would it be an idea to use one library rather than multiple ones interchangibly? PIL and cv2 are "almost" doing the same thing, so i was wondering whether we could just use one of them? This would mean one-less-dependency. Also easier-maintainability and so on?

We are using PIL because of the severe performance issue on decoding JPEG.

**Review by harimkang — APPROVED** [review]

**Pull request merged**
