### PR TITLE
[OTE] Update submodule & changelog for OTE 0.3.0 release

### PR DESCRIPTION
**Pull request by chuneuny-emily**
# Description
The changes in this PR are as follows:
- Update changelog for OTE 0.3.0 release
- Update the latest commit from each releases/OTE_0.3.0 branches of submodules

### CODE REVIEW

**Comment by chuneuny-emily** [comment]
run ote-test

**Comment by harimkang** [comment]
@JihwanEom @supersoob I think there is a mixture of resume & early-stop-related contents in the change, so is there any problem when this merges with the release branch? (this PR is not for develop)

**Comment by chuneuny-emily** [comment]
run ote-test

**Comment by chuneuny-emily** [comment]
> @JihwanEom @supersoob I think there is a mixture of resume & early-stop-related contents in the change, so is there any problem when this merges with the release branch? (this PR is not for develop)

Removed the code changes for develop branch

**Review by goodsong81 — DISMISSED** [review]

**Review by supersoob — APPROVED** [review]

**Review by JihwanEom — APPROVED** [review]

**Pull request merged**
