### PR TITLE
[SEGMENTATION] Updates OTESeg

### PR DESCRIPTION
**Pull request by evgeny-izutov**
* Updates model-zoo version according to [PR](https://github.com/openvinotoolkit/training_extensions/pull/921/files).
* Updates OTESegm to support new templates:
  * Lite-HRNet-18-mod2 (Middle template)
  * Lite-HRNet-x-mod3 (Heavy template)

Build on BMM: 25375 ✔️ (except unrelated tests)
Train on BMM: finished ✔️

### CODE REVIEW

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by nervana-ff** [comment]
Can one of the admins verify this patch?

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
BMM 25375 🕐

**Pull request merged**
