### PR TITLE
Add dumping of hierarchical config on export

### PR DESCRIPTION
**Pull request by sovrasov**
### Summary

This PR is blocked by two issues:
- In CLI tests semantic segmentation is created with a wrong number of classes / dataset is invalid, therefore, `self.model.label_info = lit_module.meta_info` raises an error (the model is created with default number of classes at first, changing the number of classes is not implemented)
- label_tree_edges is incorrect: it contains label (child node, group name) pairs, although it should contain (child node, parent node). MAPI can't work with wrong information. 

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Review by vinnamkim — APPROVED** [review]

**Comment by sungmanc** [comment]
>label_tree_edges is incorrect: it contains label (child node, group name) pairs, although it should contain (child node, parent node). MAPI can't work with wrong information. 

This means that what I made for the `label_tree_edges` is incorrect ? If so, I can't find the solution for this incorrect information.

**Comment by harimkang** [comment]
> * In CLI tests semantic segmentation is created with a wrong number of classes / dataset is invalid, therefore, `self.model.label_info = lit_module.meta_info` raises an error (the model is created with default number of classes at first, changing the number of classes is not implemented)

I'm not sure if I'm understanding this correctly.
I added the feature to update `num_classes` in the CLI (https://github.com/openvinotoolkit/training_extensions/pull/2861). 
What you mean is that in the semantic segmentation case, num_classes +1 if background is not included in the label_list is wrong?

**Comment by sovrasov** [comment]
> > label_tree_edges is incorrect: it contains label (child node, group name) pairs, although it should contain (child node, parent node). MAPI can't work with wrong information.
> 
> This means that what I made for the `label_tree_edges` is incorrect ? If so, I can't find the solution for this incorrect information.

In general yes, in OTX 1.x label schema could provide a parent label for each particular label, so I represented the hierarchical graph as a list of nodes (child label, parent label). To me it's not clear why we can't do the same thing in OTX 2.0, since we have the same datumaro dataset as an input.

**Comment by sovrasov** [comment]
> > * In CLI tests semantic segmentation is created with a wrong number of classes / dataset is invalid, therefore, `self.model.label_info = lit_module.meta_info` raises an error (the model is created with default number of classes at first, changing the number of classes is not implemented)
> 
> I'm not sure if I'm understanding this correctly. I added the feature to update `num_classes` in the CLI (#2861). What you mean is that in the semantic segmentation case, num_classes +1 if background is not included in the label_list is wrong?

I've seen the PR, it works for "normal" datasets with > 1 classes (but auto-config for h-cls is still missing). I'll dm you to describe the particular case with sseg. Probably, we need a workaround

**Comment by sungmanc** [comment]
> In general yes, in OTX 1.x label schema could provide a parent label for each particular label, so I represented the hierarchical graph as a list of nodes (child label, parent label). To me it's not clear why we can't do the same thing in OTX 2.0, since we have the same datumaro dataset as an input.

In this PR(https://github.com/openvinotoolkit/training_extensions/pull/2804), I added the information about the `label_tree_edges` to the `HLabelInfo` that means the [child label, parent label] information. So, what you mean is this implementation was invalid ? If so, I need to modify this. 

image

**Comment by sovrasov** [comment]
> > In general yes, in OTX 1.x label schema could provide a parent label for each particular label, so I represented the hierarchical graph as a list of nodes (child label, parent label). To me it's not clear why we can't do the same thing in OTX 2.0, since we have the same datumaro dataset as an input.
> 
> In this PR(#2804), I added the information about the `label_tree_edges` to the `HLabelInfo` that means the [child label, parent label] information. So, what you mean is this implementation was invalid ? If so, I need to modify this.
> 
> image

For instance, in this snipped, I see ['Rectangle', 'Object__Rigid Group'] pair. If this (child node, parent node) pair is correct, 'Object__Rigid Group' should be a tree node ~ a class -> it should be in label_to_idx dict -> I don't see this

**Comment by sovrasov** [comment]
I think for better understanding, we can load this dataset with OTX 1.6, and see the data generated. I'd be the simplest way

**Comment by sungmanc** [comment]
> For instance, in this snipped, I see ['Rectangle', 'Object__Rigid Group'] pair. If this (child node, parent node) pair is correct, 'Object__Rigid Group' should be a tree node ~ a class -> it should be in label_to_idx dict -> I don't see this

Got it, thanks. I'll modify. Please check this PR: https://github.com/openvinotoolkit/training_extensions/pull/2883

**Review by sungmanc — APPROVED** [review]

**Review by harimkang — APPROVED** [review]

**Pull request merged**
