### PR TITLE
[CVS-83781] [OTE] Hanging models Custom_Semantic_Segmentation_Lite-HRNet-18_OCR

### PR DESCRIPTION
**Pull request by JihwanEom**
### Summary:
- Set num_workers as 0 for OTE segmentation templates to prevent possible deadlock.

### CODE REVIEW

**Comment by JihwanEom** [comment]
run ote-test

**Review by chuneuny-emily — APPROVED** [review]

**Comment by JihwanEom** [comment]
run ote-test

**Comment by JihwanEom** [comment]
run ote-test

**Comment by JihwanEom** [comment]
run ote-test

**Comment by JihwanEom** [comment]
run ote-test

**Comment by JihwanEom** [comment]
run ote-test

**Comment by JihwanEom** [comment]
run ote-test

**Comment by JihwanEom** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/511/
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/513/
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/514/

Conducted 3 times to check hanging issue, no hanging occurred.

**Review by goodsong81 — APPROVED** [review]
LGTM

**Pull request merged**
