### PR TITLE
Fix for ssd

### PR DESCRIPTION
**Pull request by jaegukhyun**
### Summary
This PR is for recovering SSD performance in various datasets.
This PR recovered anchor clustering algorithm and reverted model's loss from FocalLoss to CrossEntropyLoss.

General experiments summary is below
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>

<div style='direction:ltr'>

Dataset | Original(lr 0.01) | After patching(lr: 0.01) | After patching(lr:0.001) | After patching(lr:0.0001)
-- | -- | -- | -- | --
bccd | 0.649213 | **0.89527** | 0.62499 | 0.54375
bccd-small | 0.583053 | **0.65477** | 0.55037 | 0.16545
fish | 0.764477 | 0.92602 | **0.93547** | 0.91042
fish-small | 0.368733 | **0.71402** | 0.6381 | 0.0
pothole | 0.524933 | **0.6536** | 0.63977 | 0.43677
pothole-small | 0.359793 | **0.56047** | 0.35459 | 0.06723
vitens | 0.6608 | 0.76366 | **0.77472** | 0.67276
vitens-small | 0.544617 | **0.62937** | 0.4723 | 0.06667
coco | 0.108813 | 0.17965 | 0.23709 | **0.2417**
voc | 0.25117 | 0.34927 | **0.42455** | 0.3571

</div>

</body>

</html>

### Checklist

- [x] I have added unit tests to cover my changes.​
- [x] I have added integration tests to cover my changes.​
- [x] I have added e2e tests for validation.
- [x] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [x] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [x] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [x] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Review by goodsong81 — DISMISSED** [review]
Impressive!

**Review by sungmanc — DISMISSED** [review]

**Comment by sungmanc** [comment]
BTW, how about changing the target of this PR to 1.3.1? @jaegukhyun , @goodsong81 . This is Huge improvements so introducing to external release is a good option for us

**Comment by goodsong81** [comment]
> BTW, how about changing the target of this PR to 1.3.1? @jaegukhyun , @goodsong81 . This is Huge improvements so introducing to external release is a good option for us

I'm OK for 1.3.1, but it's up to @jaegukhyun as the experiments were based on the develop branch, right?

**Comment by jaegukhyun** [comment]
@goodsong81 @sungmanc I changed base to 1.3.1

**Review by sungmanc — DISMISSED** [review]

**Review by goodsong81 — DISMISSED** [review]

**Review by sungmanc — APPROVED** [review]

**Review by goodsong81 — APPROVED** [review]

**Pull request merged**
