### PR TITLE
[OTX] Cythonize AugMixAugment

### PR DESCRIPTION
**Pull request by vinnamkim**
Target to `feature/otx` branch

- Cythonize AugMixAugment
- Add unit tests

### CODE REVIEW

**Review by goodsong81 — DISMISSED** [review]
Generally, looks good to me if it's working correctly. Let's see the test result.
BTW, the cython module paths are a little bit hard-coded. Can we generalize a little bit considering future work? (.gitignore, MANIFEST.in, setup.py...)

**Review by sungmanc — CHANGES_REQUESTED** [review]
LGTM, however, could you resolve the pre-commit issue (isort) and then re-run the tests?

**Comment by vinnamkim** [comment]
@goodsong81 
Cleaned up hard-coded paths to make it more concise.

@sungmanc 
Fixed isort error.

Let me know freely if more works is needed to merge this.

**Review by sungmanc — APPROVED** [review]
LGTM, thanks for the nice work

**Review by goodsong81 — APPROVED** [review]
LGTM!

**Comment by goodsong81** [comment]
Ignoring CUDA OOM errors.

**Pull request merged**
