### PR TITLE
Weight loading finite check

### PR DESCRIPTION
**Pull request by eugene123tw**
Reload and return the pre-trained weights in case saved weights contain infinite values

### CODE REVIEW

**Comment by eugene123tw** [comment]
run ote-test

**Comment by eugene123tw** [comment]
run ote-test

**Comment by eugene123tw** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/124/

**Review by goodsong81 — APPROVED** [review]
Looks having passed tests except for the anomaly pylint issue.

**Pull request merged**
