### PR TITLE
Promote OTXModel to PyTorchLightningModule and deprecate OTXLitModule

### PR DESCRIPTION
**Pull request by vinnamkim**
### Summary

 - Ticket no. 134585

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Review by harimkang — APPROVED** [review]
LGTM!

**Review by sungmanc — APPROVED** [review]

**Review by jaegukhyun — COMMENTED** [review]
Generally LGTM, I have some questions about f1 score metric for detection. There is f1-score evaluation implementation in otx/core/metrics/fmeasure.py, but it haven't changed yet. Is it because FMeasure in fmeaure.py do not require change? Furthermore can we change metrics by cli command? I'm a little bit confused about this.

**Comment by vinnamkim** [comment]
> Generally LGTM, I have some questions about f1 score metric for detection. There is f1-score evaluation implementation in otx/core/metrics/fmeasure.py, but it haven't changed yet. Is it because FMeasure in fmeaure.py do not require change?

I missed it. It can be dealt in the next PR.

> Furthermore can we change metrics by cli command? I'm a little bit confused about this.

We moved `MetricCallable` to `OTXModel.__init__()` argument. I don't know the reason that jsonargparse cannot handle it such as `--model.metric ...`.

**Comment by jaegukhyun** [comment]
> > Generally LGTM, I have some questions about f1 score metric for detection. There is f1-score evaluation implementation in otx/core/metrics/fmeasure.py, but it haven't changed yet. Is it because FMeasure in fmeaure.py do not require change?
> 
> I missed it. It can be dealt in the next PR.
> 
> > Furthermore can we change metrics by cli command? I'm a little bit confused about this.
> 
> We moved `MetricCallable` to `OTXModel.__init__()` argument. I don't know the reason that jsonargparse cannot handle it such as `--model.metric ...`.

I see, could you update regression tests for detection task in next PR? For regression test we use f1 score.

**Review by jaegukhyun — APPROVED** [review]

**Comment by vinnamkim** [comment]
> I see, could you update regression tests for detection task in next PR? For regression test we use f1 score.

I got it

**Pull request merged**
