### PR TITLE
Add active score evaluation to the classification task

### PR DESCRIPTION
**Pull request by sovrasov**
This functionality is restored from the original d-o-r based task implementation. Basically active score is defined as a difference between top1 and top2 predictions confidence.

### CODE REVIEW

**Comment by sovrasov** [comment]
run ote-test

**Review by goodsong81 — CHANGES_REQUESTED** [review]
Thank you for the prompt update, Vlad.
Could you add full "probabilities" metadata that was also requested by active learning research team?

**Comment by sovrasov** [comment]
run ote-test

**Comment by sovrasov** [comment]
run ote-test

**Comment by sovrasov** [comment]
run ote-test

**Comment by sovrasov** [comment]
http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=pr-ote-test-780&environment=iotg-dev-workstation-08

**Comment by sovrasov** [comment]
@goodsong81 please have a look

**Review by goodsong81 — APPROVED** [review]
Thank you for the quick update. Looks good to me!

**Comment by goodsong81** [comment]
@JihwanEom @kprokofi Could you guys double-check? :)

**Review by goodsong81 — CHANGES_REQUESTED** [review]
We got some merge conflicts. Could you amend?

**Comment by sovrasov** [comment]
run ote-test

**Review by goodsong81 — APPROVED** [review]
LGTM.
@sovrasov Sorry to bother you but could you replicate this change to release branch?

**Review by JihwanEom — APPROVED** [review]

**Comment by sovrasov** [comment]
@goodsong81 sure, I'll cherry-pick that stuff.

**Pull request merged**
