### PR TITLE
Fix OV Inference issues (tiling tests & detection tests)

### PR DESCRIPTION
**Pull request by eugene123tw**
Resolve:
- https://jira.devtools.intel.com/browse/CVS-96073
- https://jira.devtools.intel.com/browse/CVS-96065

### CODE REVIEW

**Comment by eugene123tw** [comment]
run ote-test

**Comment by harimkang** [comment]
run ote-test

**Comment by harimkang** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/726/

**Comment by harimkang** [comment]
image

**Review by harimkang — APPROVED** [review]

**Review by eunwoosh — APPROVED** [review]

**Pull request merged**
