### PR TITLE
Add Instance Segmentation (object counting) training tests.

### PR DESCRIPTION
**Pull request by sstrehlk**
Add Instance Segmentation (object counting) training tests
build: https://ci-ote.iotg.sclab.intel.com/job/ote/job/ote-test/1730/

build for model 'MaskRCNN_EfficientNetB2B'
build for 'tests/ --log-cli-level=DEBUG -k 'MaskRCNN_EfficientNetB2B and aeromonas'
https://ci-ote.iotg.sclab.intel.com/job/ote/job/ote-test/1732/

build for precommit ('aeromonas_short')
https://ci-ote.iotg.sclab.intel.com/job/ote/job/ote-test/1733/

### CODE REVIEW

**Comment by sstrehlk** [comment]
run ote-test

**Comment by sstrehlk** [comment]
Apart from nncf-graph (where reference files are not place in source-code) all precommit tests passed for both models -see http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=ote-test-1733&environment=iotg-dev-workstation-12 (you can filter by aeromonas)

**Comment by goodsong81** [comment]
> Apart from nncf-graph (where reference files are not place in source-code) all precommit tests passed for both models -see http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=ote-test-1733&environment=iotg-dev-workstation-12 (you can filter by aeromonas)

What would we do about nncf-graph failures? Are they not related to this PR?

**Comment by sstrehlk** [comment]
Real life tests for Resnet50 passed:
http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=ote-test-1730&environment=iotg-dev-workstation-12
Real life tests for EfficientNetB2B passed: 
http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=ote-test-1732&environment=iotg-dev-workstation-12

**Review by goodsong81 — APPROVED** [review]

**Pull request merged**
