### PR TITLE
[HPO] Update configurations for MPA

### PR DESCRIPTION
**Pull request by yunchu**
enables HPO to the templates of MPA for SC 1.2

### CODE REVIEW

**Comment by yunchu** [comment]
run ote-test

**Comment by eunwoosh** [comment]
run ote-test

**Comment by yunchu** [comment]
run ote-test

**Comment by yunchu** [comment]
test reports: 
http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=pr-ote-test-450&environment=iotg-dev-workstation-08

**Review by eunwoosh — APPROVED** [review]

**Review by goodsong81 — APPROVED** [review]
LGTM

**Pull request merged**
