### PR TITLE
[OTE] removed empty annotations

### PR DESCRIPTION
**Pull request by kprokofi**
bug fix for Geti 1.0.0 Gold
https://jira.devtools.intel.com/browse/CVS-93867

And 4 more issues related to this problem

### CODE REVIEW

**Review by goodsong81 — COMMENTED** [review]
Thank you for the nice catch.
I see one another call in detection task. Is it OK?

external/model-preparation-algorithm/mpa_tasks/apis/classification/task.py:133:        dataset = dataset.with_empty_annotations()
external/model-preparation-algorithm/mpa_tasks/apis/detection/task.py:478:        preds_val_dataset = val_dataset.with_empty_annotations()

**Comment by kprokofi** [comment]
> Thank you for the nice catch. I see one another call in detection task. Is it OK?
> 
> external/model-preparation-algorithm/mpa_tasks/apis/classification/task.py:133: dataset = dataset.with_empty_annotations() external/model-preparation-algorithm/mpa_tasks/apis/detection/task.py:478: preds_val_dataset = val_dataset.with_empty_annotations()

It is not an issue for the detection task as we don't have it as a second task in a chain. Also, this method was in the mmdetection task. 
If we want to remove it - we need to double-check the validation. Anyway for now - I propose to delete it only in classification. In the segmentation task (it is also could be the second task in a chain) everything is okay.

**Comment by harimkang** [comment]
Have you created a SC repo PR that reflects this?
Since it is a `release` branch, it would be good to check that the Geti side test passes before the merge. If you have a link related this, please post it.

**Comment by kprokofi** [comment]
> Have you created a SC repo PR that reflects this? Since it is a `release` branch, it would be good to check that the Geti side test passes before the merge. If you have a link related this, please post it.

http://validationreports.sclab.intel.com:8004/reports/build_number_report?test_session_build_number=IMPTOps-42904&environment=mclx80

I will create PR to SC after this merged

**Comment by kprokofi** [comment]
So, only new HPO tests are failed, we disregard them. Could you please approve PR?
I need to add it to SC

**Comment by kprokofi** [comment]
run ote-tests

**Comment by kprokofi** [comment]
run ote-test

**Review by goodsong81 — APPROVED** [review]

**Review by harimkang — APPROVED** [review]

**Pull request merged**
