### PR TITLE
🐞Fix Anomaly scores

### PR DESCRIPTION
**Pull request by ashwinvaidya17**
### Summary

- Fixes training from API
- Tested with CLI on Padim
image
- CLI with STFPM
image
```bash
otx train --config src/otx/recipe/anomaly_classification/stfpm.yaml --data_root ./datasets/otx/v2/anomaly/mvtec/hazelnut_large/ --engine.device gpu --seed 0 --deterministic False --work_dir otx-stfpm
```
- Fixes CVS-140359

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have ran e2e tests and there is no issues.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Review by chuneuny-emily — DISMISSED** [review]

**Review by harimkang — DISMISSED** [review]

**Comment by chuneuny-emily** [comment]
@ashwinvaidya17  - Can you check the failing integration tests below?
ERROR tests/integration/cli/test_cli.py::test_otx_e2e[gpu-anomaly_classification/stfpm.yaml]
ERROR tests/integration/cli/test_cli.py::test_otx_e2e[gpu-anomaly_classification/padim.yaml]
ERROR tests/integration/cli/test_cli.py::test_otx_e2e[gpu-anomaly_detection/stfpm.yaml]
ERROR tests/integration/cli/test_cli.py::test_otx_e2e[gpu-anomaly_detection/padim.yaml]
ERROR tests/integration/cli/test_cli.py::test_otx_e2e[gpu-anomaly_segmentation/padim.yaml]
ERROR tests/integration/cli/test_cli.py::test_otx_e2e[gpu-anomaly_segmentation/stfpm.yaml]
ERROR tests/integration/cli/test_cli.py::test_otx_explain_e2e[gpu-anomaly_classification/stfpm.yaml]
ERROR tests/integration/cli/test_cli.py::test_otx_explain_e2e[gpu-anomaly_classification/padim.yaml]
ERROR tests/integration/cli/test_cli.py::test_otx_explain_e2e[gpu-anomaly_detection/stfpm.yaml]
ERROR tests/integration/cli/test_cli.py::test_otx_explain_e2e[gpu-anomaly_detection/padim.yaml]
ERROR tests/integration/cli/test_cli.py::test_otx_explain_e2e[gpu-anomaly_segmentation/padim.yaml]
ERROR tests/integration/cli/test_cli.py::test_otx_explain_e2e[gpu-anomaly_segmentation/stfpm.yaml]
FAILED tests/integration/cli/test_auto_configuration.py::test_otx_cli_auto_configuration[gpu-ANOMALY_CLASSIFICATION]
FAILED tests/integration/cli/test_auto_configuration.py::test_otx_cli_auto_configuration[gpu-ANOMALY_DETECTION]
FAILED tests/integration/cli/test_auto_configuration.py::test_otx_cli_auto_configuration[gpu-ANOMALY_SEGMENTATION]
FAILED tests/integration/cli/test_cli.py::test_otx_hpo_e2e[gpu-ANOMALY_CLASSIFICATION]
FAILED tests/integration/cli/test_cli.py::test_otx_hpo_e2e[gpu-ANOMALY_DETECTION]
FAILED tests/integration/cli/test_cli.py::test_otx_hpo_e2e[gpu-ANOMALY_SEGMENTATION]
FAILED tests/integration/cli/test_cli.py::test_otx_adaptive_bs_e2e[gpu-Safe-ANOMALY_CLASSIFICATION]
FAILED tests/integration/cli/test_cli.py::test_otx_adaptive_bs_e2e[gpu-Safe-ANOMALY_DETECTION]
FAILED tests/integration/cli/test_cli.py::test_otx_adaptive_bs_e2e[gpu-Safe-ANOMALY_SEGMENTATION]
FAILED tests/integration/cli/test_cli.py::test_otx_adaptive_bs_e2e[gpu-Full-ANOMALY_CLASSIFICATION]
FAILED tests/integration/cli/test_cli.py::test_otx_adaptive_bs_e2e[gpu-Full-ANOMALY_DETECTION]
FAILED tests/integration/cli/test_cli.py::test_otx_adaptive_bs_e2e[gpu-Full-ANOMALY_SEGMENTATION]
= 12 failed, 3 passed, 15 skipped, 3 xfailed, 40 warnings, 12 errors in 333.00s (0:05:33) =

**Comment by harimkang** [comment]
A release branch has been created, so please retarget to `releases/2.0.0`

**Comment by ashwinvaidya17** [comment]
@harimkang I'll create another one to target 2.0. Not sure if the changes are going be be merged back. Some of the changes in this PR were already made to the 2.0 branch. But this issue is also with develop branch.

**Comment by chuneuny-emily** [comment]
@ashwinvaidya17 - When can this PR be merged into the releases/2.0.0 branch? Could you please tell me the ETA?

**Comment by ashwinvaidya17** [comment]
> @ashwinvaidya17 - When can this PR be merged into the releases/2.0.0 branch? Could you please tell me the ETA?

PR with same changes has already been merged to release/2 https://github.com/openvinotoolkit/training_extensions/pull/3452. Since the ticket (CVS-140359) refers to develop this targets develop

**Comment by harimkang** [comment]
https://github.com/openvinotoolkit/training_extensions/pull/3489 - merged

**Pull request closed without merging**
