### PR TITLE
Rename recipe files to unified name, 'incremental' and 'semisl'

### PR DESCRIPTION
**Pull request by supersoob**
**This PR includes**

- Rename recipe files to unified name, 'incremental' and 'semisl'
- It will pass tests after MPA PR is merged-> https://github.com/openvinotoolkit/model_preparation_algorithm/pull/88

### CODE REVIEW

**Review by JihwanEom — APPROVED** [review]

**Comment by sungmanc** [comment]
It seems that this PR didn't include the changes of the MPA submodule although they are required.

**Comment by sungmanc** [comment]
> It seems that this PR didn't include the changes of the MPA submodule although they are required.

Ah, sorry. I missed that currently MPA is installed via pip.

**Review by sungmanc — APPROVED** [review]
LGTM

**Comment by supersoob** [comment]
It only failed 1 test because of score comparison in nncf eval. 
image
image

**Pull request merged**
