### PR TITLE
[Classification] Fix OTE CLI test classification task saliency map bug

### PR DESCRIPTION
**Pull request by eugene123tw**
Torchreid PR: https://github.com/openvinotoolkit/deep-object-reid/pull/225

### CODE REVIEW

**Comment by eugene123tw** [comment]
run ote-test

**Comment by eugene123tw** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/462/

**Comment by eugene123tw** [comment]
run ote-test

**Comment by eugene123tw** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-model-preparation-algorithm-test/60/

**Review by JihwanEom — APPROVED** [review]
LGTM, could you add torchreid PR #224 on your description?

**Review by goodsong81 — APPROVED** [review]

**Pull request merged**
