### PR TITLE
[OTE-TEST] hot-fix for MPA performance tests

### PR DESCRIPTION
**Pull request by harimkang**
### This PR includes :
- Fix Import Error
- Fix file name too long OSError
- Fix anomaly template collection '/templates/' -> '/configs/'

### CODE REVIEW

**Comment by harimkang** [comment]
run ote-test

**Comment by harimkang** [comment]
run ote-test

**Comment by harimkang** [comment]
run ote-test

**Review by chuneuny-emily — DISMISSED** [review]

**Review by goodsong81 — DISMISSED** [review]

**Comment by harimkang** [comment]
run ote-test

**Comment by harimkang** [comment]
run ote-test

**Comment by harimkang** [comment]
run ote-test

**Comment by harimkang** [comment]
run ote-test

**Review by JihwanEom — APPROVED** [review]
LGTM

**Review by chuneuny-emily — APPROVED** [review]

**Comment by harimkang** [comment]
MPA performance-test validation report: http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=weekly-ote-test-65&environment=iotg-dev-workstation-17

**Pull request merged**
