### PR TITLE
[SEGMENTATION] Updates OTESeg to extend OTE templates

### PR DESCRIPTION
**Pull request by evgeny-izutov**
* Enables new templates:
   * Lite-HRNet-18-mod2 (middle)
   * Lite-HRNet-x-mod3 (heavy)
 
Note: Should be merged after [PR#73](https://github.com/openvinotoolkit/mmsegmentation/pull/73) and [PR#80](https://github.com/openvinotoolkit/mmsegmentation/pull/80).

Build on BMM: 25979 ✔️ - deprecated
Train on BMM: finished ✔️ - deprecated
OTE-test: 1334 🕥

### CODE REVIEW

**Comment by nervana-ff** [comment]
Can one of the admins verify this patch?

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Review by druzhkov-paul — DISMISSED** [review]

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by evgeny-izutov** [comment]
run ote-test

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Comment by evgeny-izutov** [comment]
run ote_sdk tests

**Pull request merged**
