### PR TITLE
Fix detection e2e tests

### PR DESCRIPTION
**Pull request by jaegukhyun**
### Summary
Run on 3090 machine
image

Run on V100 machine
image

### How to test
E2E Test

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Comment by sungmanc** [comment]
This fix is super heuristic,, Did the error comes from the uncertainty of training?

**Comment by sovrasov** [comment]
Which tests are fixed by this change? Or is it just to reduce the run time?

**Comment by jaegukhyun** [comment]
> This fix is super heuristic,, Did the error comes from the uncertainty of training?

I think this come from uncertainty of training, When I conducted on some public datasets there is no huge accuracy drop for YOLOX models

**Comment by jaegukhyun** [comment]
> Which tests are fixed by this change? Or is it just to reduce the run time?

Currently e2e tests for release1.4 branch failed due to accuracy drop for YOLOX. However I think this comes from uncertainty of training since we're using tiny datasets for e2e tests. When I verified on public dataset, there is no such a huge drop for YOLOX model. The best way for solving this problem is using public dataset for e2e test or enlarging toy dataset volume. However both approach will increase e2e test time, so I just manually find iterations for passing e2e test.

**Comment by sovrasov** [comment]
> > Which tests are fixed by this change? Or is it just to reduce the run time?
> 
> Currently e2e tests for release1.4 branch failed due to accuracy drop for YOLOX. However I think this comes from uncertainty of training since we're using tiny datasets for e2e tests. When I verified on public dataset, there is no such a huge drop for YOLOX model. The best way for solving this problem is using public dataset for e2e test or enlarging toy dataset volume. However both approach will increase e2e test time, so I just manually find iterations for passing e2e test.

Do you mean OV inference tests?

**Comment by jaegukhyun** [comment]
> > > Which tests are fixed by this change? Or is it just to reduce the run time?
> > 
> > 
> > Currently e2e tests for release1.4 branch failed due to accuracy drop for YOLOX. However I think this comes from uncertainty of training since we're using tiny datasets for e2e tests. When I verified on public dataset, there is no such a huge drop for YOLOX model. The best way for solving this problem is using public dataset for e2e test or enlarging toy dataset volume. However both approach will increase e2e test time, so I just manually find iterations for passing e2e test.
> 
> Do you mean OV inference tests?

Yes for ov inference test

**Review by sungmanc — APPROVED** [review]

**Comment by sovrasov** [comment]
For me e2e detection tests pass on current develop

**Comment by jaegukhyun** [comment]
> For me e2e detection tests pass on current develop

It highly depends on type of gpu.

**Review by sovrasov — APPROVED** [review]

**Pull request merged**
