### PR TITLE
Fix tests eval assert statement

### PR DESCRIPTION
**Pull request by harimkang**
## Summary
Fix the case of FAILED if the score is higher after optimization or export
- ote_eval_openvino_testing
- nncf_eval_testing

### CODE REVIEW

**Comment by harimkang** [comment]
run ote-cli

**Comment by harimkang** [comment]
run ote-test

**Comment by harimkang** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/661/

**Comment by harimkang** [comment]
run ote-test

**Comment by harimkang** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/677/

**Review by jaegukhyun — APPROVED** [review]
LGTM

**Review by JihwanEom — APPROVED** [review]
LGTM

**Pull request merged**
