### PR TITLE
[CVS-83536] updated task configuarions

### PR DESCRIPTION
**Pull request by yunchu**
to disable auto-hpo as default configurations for each tasks
and selectively enable auto-hpo which are tested.
for templates below will be enabled auto-hpo at this point.
* custom classifications
* custom object detections (bounding box)
* semantic segmentations
JIRA ticket: [CVS-83536](https://jira.devtools.intel.com/browse/CVS-83536)

### CODE REVIEW

**Comment by yunchu** [comment]
run ote_sdk tests

**Comment by ljcornel** [comment]
The PR looks good to me, have you tested this on an SC build? Would be nice to add the test report as a comment to the PR for reference in that case.

Also, I can approve the PR but I don't have the rights to merge it unfortunately, that can only be done by someone from ote-maintainers

**Comment by yunchu** [comment]
run ote_sdk tests

**Comment by yunchu** [comment]
@ljcornel, thanks for your comment. i've tried to test this on the SC build but result is not good. HPO options are same with previous one. (enabled for all detection, classification, and segmentation)
do you have any idea about this? (i've set OTE_VERSION parameter correctly in the IMPTOps build)
here is the build: https://ci.iotg.sclab.intel.com/job/IMPT/job/IMPTOps/28780/

**Comment by ljcornel** [comment]
@yunchu Not sure why it's not working, the PR looks good to me. You could try loading a model template locally and checking that the override from the model template is correctly applied (it should be, there are tests for this in the OTE SDK test suite but not for the auto_hpo_state particularly)

**Comment by yunchu** [comment]
@ljcornel thank you for your comment. I guess you are talking about this one https://github.com/openvinotoolkit/training_extensions/blob/develop/ote_sdk/ote_sdk/tests/entities/test_model_template.py, right?

**Comment by ljcornel** [comment]
Well that test checks that overriding properties from the template.yaml works correctly, but it doesn't check the `auto_hpo_state` explicitly. If it works for the other properties I can't imagine why it wouldn't work for the auto_hpo_state, but just to be sure you could try parsing a real model template to double check that the property is set correctly on the parameters involved.

**Comment by yunchu** [comment]
verified it on the SC build https://ci.iotg.sclab.intel.com/job/IMPT/job/IMPTOps/29290/

**Comment by yunchu** [comment]
run ote_test

**Comment by yunchu** [comment]
run ote_test

**Comment by goodsong81** [comment]
Being tested: https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/146/

**Comment by goodsong81** [comment]
Failures are not relevant to this PR.

**Pull request merged**
