### PR TITLE
[OTE][dev] Remove sklearn from each modules

### PR DESCRIPTION
**Pull request by sungmanc**
# Summary
* This PR is remedy for https://jira.devtools.intel.com/browse/CVS-99662. Even though it passed all local tests, I'll also check with CI.
image

* Also includes the .gitignore to exclude built file made by cython

### CODE REVIEW

**Comment by sungmanc** [comment]
run ote-test
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/874/

**Comment by sungmanc** [comment]
If all CI tests passed, I'll make PR for each modules (d-o-r, mmdet, mmseg)

**Comment by sungmanc** [comment]
CI results: 1FAILS (openvino eval performance) 
http://validationreports.sclab.intel.com:8006/reports/build_number_report?test_session_build_number=pr-ote-test-874&environment=iotg-dev-workstation-10

Related PRs
https://github.com/openvinotoolkit/deep-object-reid/pull/243
https://github.com/openvinotoolkit/mmdetection/pull/360
https://github.com/openvinotoolkit/mmsegmentation/pull/96

**Review by goodsong81 — APPROVED** [review]
Cheers!

**Review by supersoob — APPROVED** [review]

**Review by harimkang — APPROVED** [review]
LGTM

**Pull request merged**
