### PR TITLE
[Feature/OTX] Rebase develop to feature/otx before MPA refactoring

### PR DESCRIPTION
**Pull request by harimkang**
## Summary
This is to rebase the current develop branch to feature/otx before MPA refactoring (This excludes external/anomaly)

### This PR includes :
- Rebase develop -> feature/otx
- Exclude external/anomaly

### CODE REVIEW

**Comment by harimkang** [comment]
@ashwinvaidya17 Hi, Before starting the MPA task refactoring in feature/otx, I first reflected the changes in the develop branch. However, I have excluded the changes in the external/anomaly folder for now. Because I wasn't sure exactly what changes should be reflected here. With this in mind, take a look at the code. (And please let me know if I'm missing anything)

And, as I recall, we set the number of character limits in the code to 120. However, Codacy-Static-Code-Analysis (CSCA) is still checking based on 80 characters. Do you have any idea how to solve this? Currently, CSCA is in Fail status, but this is confirmed by the content related to the number of characters in quick_guide doc.

**Comment by samet-akcay** [comment]
@harimkang, thanks for creating this PR. 

I see that there are some changes in `ote_sdk`. These changes should also be added to `otx.api`. Otherwise, it would be hard to sync the changes between `ote_sdk` and `otx.api`.

Would you be able to add those changes to the corresponding location in `otx.api`?

**Comment by harimkang** [comment]
> @harimkang, thanks for creating this PR.
> 
> I see that there are some changes in `ote_sdk`. These changes should also be added to `otx.api`. Otherwise, it would be hard to sync the changes between `ote_sdk` and `otx.api`.
> 
> Would you be able to add those changes to the corresponding location in `otx.api`?

Hi @samet-akcay, Yes, I will look into it (ote_sdk & otx.api) and reflect on it.

**Comment by samet-akcay** [comment]
> And, as I recall, we set the number of character limits in the code to 120. However, Codacy-Static-Code-Analysis (CSCA) is still checking based on 80 characters. Do you have any idea how to solve this? Currently, CSCA is in Fail status, but this is confirmed by the content related to the number of characters in quick_guide doc.

This is because Codacy complains about the markdown file. We set the line length to 120 for the `.py` files, but not `.md` files. You could ignore that for now. We'll address that later.

**Review by samet-akcay — APPROVED** [review]
Thanks @harimkang

**Pull request merged**
