### PR TITLE
[CVS-89912] Fixed config path computation

### PR DESCRIPTION
**Pull request by nikita-savelyevv**
**Description** 
Fixed how a path to NNCF config file is computed so that optimization of anomaly classification task would start.

Ticket: https://jira.devtools.intel.com/browse/CVS-89912
BMM: https://10.211.120.60/

### CODE REVIEW

**Comment by goodsong81** [comment]
run ote-tests

**Comment by nikita-savelyevv** [comment]
run ote-test

**Comment by goodsong81** [comment]
Test build: https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/546/

**Comment by goodsong81** [comment]
Thank you for the update. I'm redirecting this PR to release branch.

**Review by samet-akcay — APPROVED** [review]

**Review by goodsong81 — APPROVED** [review]

**Pull request merged**
