### PR TITLE
🐞 Add metrics to openvino model

### PR DESCRIPTION
**Pull request by ashwinvaidya17**
### Summary

- Addresses https://github.com/openvinotoolkit/training_extensions/issues/3154
- I am a bit unclear on metric computation for OpenVINO models. Currently I am using Anomalib's metrics. It in turn relies on TorchMetrics.
- The DataLoader issue is probably unrelated. Also, I don't expect the results to be correct as the CLI does not run validation to select meaningful thresholds.
image

### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Comment by jaegukhyun** [comment]
Could you add unit tests for this update?.
And I think it is natural to use torch metrics for openvino model, so we can assure that torch model and openvino model show same performance if they return same output on same input.
What is your main concern about using torch metrics for openvino model?

**Comment by ashwinvaidya17** [comment]
> Could you add unit tests for this update?. And I think it is natural to use torch metrics for openvino model, so we can assure that torch model and openvino model show same performance if they return same output on same input. What is your main concern about using torch metrics for openvino model?

Alright! I'll add some tests.
I was just unsure about the approach for openvino model. I thought since we don't use torch tensors in openvino TorchMetrics was not the right approach. But thanks for the clarification.

**Comment by harimkang** [comment]
Please modify the target with this to the releases/2.0.0 branch.

**Review by jaegukhyun — DISMISSED** [review]

**Comment by harimkang** [comment]
I reapplied pre-commit in my environment. - https://github.com/openvinotoolkit/training_extensions/pull/3163/commits/f30e55176d334e5e03ce358805ce84a1bb594628

**Review by harimkang — APPROVED** [review]

**Review by jaegukhyun — APPROVED** [review]

**Pull request merged**
