### PR TITLE
[Develop CI-Fix] Add xfail mark for deprecated model template

### PR DESCRIPTION
**Pull request by harimkang**
## Summary
Add xfail mark for deprecated model template & Enable black format to model.py

## Resolves
- https://jira.devtools.intel.com/browse/CVS-96084

### CODE REVIEW

**Comment by harimkang** [comment]
run ote-test

**Comment by harimkang** [comment]
https://ci-ote.iotg.sclab.intel.com/job/ote/job/pr-ote-test/734/

**Comment by harimkang** [comment]
image

**Comment by harimkang** [comment]
@sungmanc It all seems to pass without modifying num_worker..?

**Review by goodsong81 — APPROVED** [review]

**Comment by sungmanc** [comment]
> @sungmanc It all seems to pass without modifying num_worker..?

How about conducting 3 trial CI experiments?

**Review by JihwanEom — APPROVED** [review]
LGTM

**Comment by harimkang** [comment]
> > @sungmanc It all seems to pass without modifying num_worker..?
> 
> How about conducting 3 trial CI experiments?

Sometimes OOM happens. It may affect other tests. Shall we try?

**Comment by sungmanc** [comment]
> > > @sungmanc It all seems to pass without modifying num_worker..?
> > 
> > 
> > How about conducting 3 trial CI experiments?
> 
> Sometimes OOM happens. It may affect other tests. Shall we try?

AFAIK, the num_workers problem not always happened. So, 3~5 trials can make more stable results for us.

**Comment by sungmanc** [comment]
I'll try 3 trial experiments w/ assigning different workstations for each test

**Pull request merged**
