### PR TITLE
[MMSegmentation] fixed model saving in the NNCF task

### PR DESCRIPTION
**Pull request by alexsu52**
Bug: 75706

### CODE REVIEW

**Comment by alexsu52** [comment]
run ote_sdk tests

**Comment by alexsu52** [comment]
BMM 23054

**Review by Ilya-Krylov — DISMISSED** [review]

**Comment by alexsu52** [comment]
run ote_sdk tests

**Comment by alexsu52** [comment]
BMM 23116

**Comment by alexsu52** [comment]
run ote_sdk tests

**Comment by alexsu52** [comment]
BMM 23190

**Pull request merged**
