### PR TITLE
Add license to deployed archive in algo backends

### PR DESCRIPTION
**Pull request by LeonidBeynenson**

### CODE REVIEW

**Comment by LeonidBeynenson** [comment]
Note that this PR should be merged only after the PR https://github.com/openvinotoolkit/training_extensions/pull/859 which contains the LICENSE file that should be used by algo backends to update for deploy

Also this PR should be **updated** after the following PR-s in algo backends are merged:
https://github.com/openvinotoolkit/mmdetection/pull/299
https://github.com/openvinotoolkit/deep-object-reid/pull/153
https://github.com/openvinotoolkit/mmsegmentation/pull/52
-- these PR-s contain changes that adds the LICENSE file to the deployed archives

(Note that all these PR-s are also depend on the PR https://github.com/openvinotoolkit/training_extensions/pull/859 )

**Comment by LeonidBeynenson** [comment]
run ote_sdk tests

**Comment by LeonidBeynenson** [comment]
run ote_sdk tests

**Comment by LeonidBeynenson** [comment]
Hi all

Since 
* PR #859 is merged, 
* and all PRs in all algo backends are merged, 

-- I updated in this PR all algo backends to the current state of `ote` branches .

So, now this PR is ready for final checks and merges!

@Ilya-Krylov , FYI

**Comment by Ilya-Krylov** [comment]
run ote_sdk tests

**Comment by LeonidBeynenson** [comment]
run ote_sdk tests

**Comment by LeonidBeynenson** [comment]
OTE CI lbeynens-655-test build is running 🏃‍♂️

**Pull request merged**
