### PR TITLE
Enable deit_tiny template by default

### PR DESCRIPTION
**Pull request by wonjuleee**
### Checklist

- [ ] I have added unit tests to cover my changes.​
- [ ] I have added integration tests to cover my changes.​
- [ ] I have added e2e tests for validation.
- [ ] I have added the description of my changes into CHANGELOG in my target branch (e.g., [CHANGELOG](https://github.com/openvinotoolkit/training_extensions/blob/develop/CHANGELOG.md) in develop).​
- [ ] I have updated the documentation in my target branch accordingly (e.g., [documentation](https://github.com/openvinotoolkit/training_extensions/tree/develop/docs) in develop).
- [ ] I have [linked related issues](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### License

- [ ] I submit _my code changes_ under the same [Apache License](https://github.com/openvinotoolkit/training_extensions/blob/develop/LICENSE) that covers the project.
      Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below).

```python
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
```

### CODE REVIEW

**Review by jaegukhyun — DISMISSED** [review]

**Review by harimkang — DISMISSED** [review]

**Comment by sungmanc** [comment]
@wonjuleee , is it okay to merge? or do you want to merge this PR after checking the effect of the Geti side?

**Review by goodsong81 — CHANGES_REQUESTED** [review]
Let's hold this PR until the Geti implements static model template mapping. It's OK for testing purpose.

**Comment by JihwanEom** [comment]
Sorry for interrupting, we need to check documentation coverage if we promote DeiT template as default.

FYI, the performance of multi-label and h-label classification is not validated for DeiT template. Thanks!

**Comment by wonjuleee** [comment]
> @wonjuleee , is it okay to merge? or do you want to merge this PR after checking the effect of the Geti side?

I am currently working on manual testing on Geti. 
I temporarily copied the data_cfg in mmcls task. @jaegukhyun, please let me know when you create the related PR. I will update this after merging your PR.

**Review by jaegukhyun — APPROVED** [review]

**Review by goodsong81 — APPROVED** [review]
Checked that DeiT is registered as custom model on Geti.

**Pull request merged**
