### PR TITLE
[CLASSIFICATION][SEGMENTATION][BUFGIX] Different type of classes OptimizationType in OTE_SDK

### PR DESCRIPTION
**Pull request by alexsu52**
#ref-74657

### CODE REVIEW

**Comment by alexsu52** [comment]
run ote_sdk tests

**Comment by Ilya-Krylov** [comment]
Maybe it is worth checking anomaly "export/optimize" at the same time ? :)

**Comment by alexsu52** [comment]
> 

I will open a separate PR for the anomaly.

**Comment by alexsu52** [comment]
Build 22087

**Pull request merged**
